### ISSUE TITLE
input buffer too short

### ISSUE THREAD

**Issue by alexlovar** [leocavalcante/encrypt#10]
hi, i use this code to set the plaintText value, this is get from a variable called: content.

```
1 final key = 'my32lengthsupersecretnooneknows1';
2    final encrypter = new Encrypter(new AES(key));
3    final plainText = content.toString();
4    print('plainText: '+plainText);
5    final encryptedText = encrypter.encrypt(plainText);
6     print('encrypt: '+encryptedText);
```
but i get this error:

I/flutter (30752): plainText: new text
I/flutter (30752): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════
I/flutter (30752): The following ArgumentError was thrown while handling a gesture:
I/flutter (30752): Invalid argument(s): Input buffer too short

the sample only work if plain text is: 
`plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit ........';`
if you change any word in the sample or add something more this fail

I/flutter ( 4277): plainText: Lorem ipsum dolor sit consectetur adipiscing elit .........
I/flutter ( 4277): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 4277): The following ArgumentError was thrown while handling a gesture:
I/flutter ( 4277): Invalid argument(s): Input buffer too short
I/flutter ( 4277): 
I/flutter ( 4277): When the exception was thrown, this was the stack:
I/flutter ( 4277): #0      AESFastEngine.processBlock (package:pointycastle/block/aes_fast.dart:113:7)
I/flutter ( 4277): #1      AES._processBlocks (package:encrypt/src/aes.dart:42:25)
I/flutter ( 4277): #2      AES.encrypt (package:encrypt/src/aes.dart:22:20)
I/flutter ( 4277): #3      Encrypter.encrypt (package:encrypt/encrypt.dart:17:17)

**Comment by leocavalcante** [comment]
This is the same as #8 

This is a "limitation" of the Block cipher specification, as the name says, it operate on blocks, fixed-length blocks, which means fixed-length sizes for both input and key. You should pad your input.
https://en.wikipedia.org/wiki/Block_cipher

If padding is a issue, you can try a Stream cipher, like Salsa20.

**Comment by alexlovar** [comment]
oh, thanks

**Comment by somdipdey** [comment]
Anyone knows how to modify the aforementioned code to encrypt and decrypt string messages using my own password using Salsa20?

How to modify this code for Salsa20->

```
final key = 'my32lengthsupersecretnooneknows1';
final encrypter = new Encrypter(new AES(key));
final plainText = content.toString();
print('plainText: '+plainText);
final encryptedText = encrypter.encrypt(plainText);
print('encrypt: '+encryptedText);
```

**Comment by ParmarPravin** [comment]
final plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
  final key = Key.fromUtf8('my 32 length key................');
  final iv = IV.fromLength(16);

  final encrypter = Encrypter(AES(key));

  final encrypted = encrypter.encrypt(plainText, iv: iv);
  final decrypted = encrypter.decrypt(encrypted, iv: iv);

  print(decrypted); // Lorem ipsum dolor sit amet, consectetur adipiscing elit
  print(encrypted.base64); 
 
Error issue
