### ISSUE TITLE
Can sha256withrsa signature be implemented？

### ISSUE THREAD

**Issue by CyJaySong** [leocavalcante/encrypt#101]
Can sha256withrsa signature be implemented？

**Comment by CyJaySong** [comment]
@leocavalcante Hello, sir, I'm trying to develop a desktop application with flutter. the application needs sha256withrsa (sign/verify). But at present, encrypt does not seem to support it.

**Comment by leocavalcante** [comment]
Working on it ;)

**Comment by leocavalcante** [comment]
```dart
 final publicKey = await parseKeyFromFile<RSAPublicKey>('test/public.pem');
 final privateKey = await parseKeyFromFile<RSAPrivateKey>('test/private.pem');
 final signer = Signer(RSASigner(RSASignDigest.SHA256, publicKey: publicKey, privateKey: privateKey));

 print(signer.sign('hello world').base64);
 print(signer.verify(Encrypted.from64('jfMhNM2v6hauQr6w3ji0xNOxGInHbeIH3DHlpf2W3vmSMyAuwGHG0KLcunggG4XtZrZPAib7oHaKEAdkHaSIGXAtEqaAvocq138oJ7BEznA4KVYuMcW9c8bRy5E4tUpikTpoO+okHdHr5YLc9y908CAQBVsfhbt0W9NClvDWegs=')));
```

Tell me if you need more digests.
To use it, please, upgrade to v4: https://pub.dev/packages/encrypt/versions/4.0.0

**Comment by CyJaySong** [comment]
it working for me。This has pushed my project forward。thank you，

**Comment by CyJaySong** [comment]
@leocavalcante Sir, there's something wrong with this part of the digests;

print(signer.verify(Encrypted.from64('jfMhNM2v6hauQr6w3ji0xNOxGInHbeIH3DHlpf2W3vmSMyAuwGHG0KLcunggG4XtZrZPAib7oHaKEAdkHaSIGXAtEqaAvocq138oJ7BEznA4KVYuMcW9c8bRy5E4tUpikTpoO+okHdHr5YLc9y908CAQBVsfhbt0W9NClvDWegs=')));

fix:
print(signer.verify('hello world',Encrypted.from64('jfMhNM2v6hauQr6w3ji0xNOxGInHbeIH3DHlpf2W3vmSMyAuwGHG0KLcunggG4XtZrZPAib7oHaKEAdkHaSIGXAtEqaAvocq138oJ7BEznA4KVYuMcW9c8bRy5E4tUpikTpoO+okHdHr5YLc9y908CAQBVsfhbt0W9NClvDWegs=')));

**Comment by leocavalcante** [comment]
@CyJaySong 
whoops, yeah, sorry. Actually the API for  `verify` gets the `input` being verified as the first argument.
There is also a `verify64` so you don't need to do this `Encrypt` wrapping:
```dart
 final publicKey = await parseKeyFromFile<RSAPublicKey>('test/public.pem');
 final privateKey = await parseKeyFromFile<RSAPrivateKey>('test/private.pem');
 final signer = Signer(RSASigner(RSASignDigest.SHA256, publicKey: publicKey, privateKey: privateKey));

 print(signer.sign('hello world').base64);
 print(signer.verify64('hello world', 'jfMhNM2v6hauQr6w3ji0xNOxGInHbeIH3DHlpf2W3vmSMyAuwGHG0KLcunggG4XtZrZPAib7oHaKEAdkHaSIGXAtEqaAvocq138oJ7BEznA4KVYuMcW9c8bRy5E4tUpikTpoO+okHdHr5YLc9y908CAQBVsfhbt0W9NClvDWegs='));
```
