### ISSUE TITLE
Decrypt json files

### ISSUE THREAD

**Issue by mehdidavarpanah66** [leocavalcante/encrypt#103]
Hi, I have a webservice that encrypt from server and i must decrypt json files for get data.

**Comment by leocavalcante** [comment]
Right, do you know the algorithm that the server used to encrypt the files?

**Comment by leocavalcante** [comment]
Closed due inactivity

**Comment by MohammedSalehelShazly** [comment]
@leocavalcante I need to encrypt and decrypt a large json file
I have this error
`Invalid length, must be multiple of four (at character 244)`
It's restricted by length?
