### ISSUE TITLE
decrypt  video 

### ISSUE THREAD

**Issue by MostafaDadkhah** [leocavalcante/encrypt#105]
Hi. How do I decrypt the movie I encrypted on the Mac OS Terminal? This is my code. If you would like to help me write about it in storage, thank you.

`Future<void>aes() async {

   final  plainText =  await rootBundle.load('assets/2.mp4');
   
  final encrypted = encrypt.Encrypted(plainText.buffer.asUint8List());
 
  final key = encrypt.Key.fromUtf8(('12345678911234567891123456789112'));
  
  final iv = encrypt.IV.fromUtf8('6274121184987725');
  

  final encrypter = encrypt.Encrypter(encrypt.AES(key, mode: encrypt.AESMode.cbc));
  final decrypted = encrypter.decrypt(encrypted, iv: iv);
  
  final path = await getApplicationDocumentsDirectory();
  final file = File('${path.path}/2.mp4');
  await file.writeAsString(decrypted);}
`

**Comment by leocavalcante** [comment]
It is just like you are already doing. Just a headsup, people are having problems using in large files https://github.com/leocavalcante/encrypt/issues/76 https://github.com/leocavalcante/encrypt/issues/40
