### ISSUE TITLE
FileSystemException: Cannot open file, path = 'assets/publickey.pem' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by iwansupratman** [leocavalcante/encrypt#106]
final publicKey = await parseKeyFromFile<RSAPublicKey>('assets/publickey.pem');
final privKey = await parseKeyFromFile<RSAPrivateKey>('assets/privatekey.pem');

return :
FileSystemException: Cannot open file, path = 'assets/publickey.pem' (OS Error: No such file or directory, errno = 2)

Please help, where should i put the pem files ? Thank a lot.

**Comment by leocavalcante** [comment]
Are you using Flutter?

**Comment by leocavalcante** [comment]
Closed due inactivity.

**Comment by renantheodoro** [comment]
@leocavalcante Im having the same issue above. And Im using Flutter! 

My code is like this:

```
final String publicKeyFile =
        await rootBundle.loadString(AssetReference.publicKey);

    final RSAPublicKey publicKey =
        await parseKeyFromFile<RSAPublicKey>(publicKeyFile);
```

And the return is:

`Unhandled Exception: FileSystemException: Cannot open file, path = ' [content key]' (OS Error: No such file or directory, errno = 2)`
