### ISSUE TITLE
not able to decrypt from encrypted contents of a file

### ISSUE THREAD

**Issue by rajeshzmoke** [leocavalcante/encrypt#107]
I am able to encrypt contents of .db file and store it, but when I am trying to decrypt the contents of the same file, i am not able to.

Encryption
`
Uint8List listData = await File(path).readAsBytes();
final encrypted = encrypter.encryptBytes(listData, iv: iv);
await File(path).writeAsBytes(encrypted.bytes);
`

while Decrypting i am not able to directly decrypt from the encrypted contents of the file, ive to again create `Encrypted` object and then decrypt, which is not giving me the original not encrypted content of the file

`
Uint8List listData = await newDB.readAsBytes();
final encrypted = encrypter.encryptBytes(listData, iv: iv);
final decrypted = encrypter.decryptBytes(enclist, iv: iv);
`

how can i directly pass the encrypted contents of the file and decrypt it

**Comment by leocavalcante** [comment]
Did you tried to just pass the `listData` to `decryptBytes` method?
```dart
final encryptedBytes = await db.readAsBytes();
final decrypted = encrypter.decryptBytes(encryptedBytes);
```

**Comment by rajeshzmoke** [comment]
@leocavalcante yea i did but `db.readAsBytes() `gives me a `Uint8List` and the `decryptBytes()` takes `Encrypted` type, hence it doesnt work

**Comment by leocavalcante** [comment]
OH, now I see. Just wrap/decorate your bytes into a `Encrypted`:
```dart
final encryptedBytes = await db.readAsBytes();
final decrypted = encrypter.decryptBytes(Encrypted(encryptedBytes));
```

**Comment by rajeshzmoke** [comment]
@leocavalcante 

> OH, now I see. Just wrap/decorate your bytes into a `Encrypted`:
> 
> ```dart
> final bytes = await db.readAsBytes();
> final decrypted = encrypter.decryptBytes(Encrypted(bytes));
> ```
i get `ArgumentError (Invalid argument(s): Invalid or corrupted pad block)
`

**Comment by leocavalcante** [comment]
I did a small example here, encrypting and decrypting a file, it works great:
```dart
import 'dart:io';

import 'package:encrypt/encrypt.dart';

void main() async {
  final key = Key.fromBase64('ExAaFAYKCAMdAAsIHCADByAbIREBDQ4CDAcSDQAPHSE=');
  final iv = IV.fromBase64('EQsBDQcMBQEWBAsaFBkUEQ==');
  final encrypter = Encrypter(AES(key, mode: AESMode.cbc));
  final filename = 'foo.txt';

  await File(filename).writeAsString('Hello world');
  print(await File(filename).readAsString());

  final bytes = await File(filename).readAsBytes();
  print(bytes.length);

  final encrypted = encrypter.encryptBytes(bytes, iv: iv);
  print(encrypted.base64);

  await File('$filename.encrypted').writeAsBytes(encrypted.bytes);
  print((await File('$filename.encrypted').readAsBytes()).length);

  final encryptedBytes = await File('$filename.encrypted').readAsBytes();
  final decrypted = encrypter.decrypt(Encrypted(encryptedBytes), iv: iv);

  print(decrypted);
}
```
```pwsh
issue_107 [master]~ dart .\main.dart
Hello world
11
gxkljVyioVHMAjAzHC1uSQ==
16
Hello world
```

Your error means that the maybe the key or the iv aren't the same for encryption/decryption.

**Comment by rajeshzmoke** [comment]
> I did a small example here, encrypting and decrypting a file, it works great:
> 
> ```dart
> import 'dart:io';
> 
> import 'package:encrypt/encrypt.dart';
> 
> void main() async {
>   final key = Key.fromBase64('ExAaFAYKCAMdAAsIHCADByAbIREBDQ4CDAcSDQAPHSE=');
>   final iv = IV.fromBase64('EQsBDQcMBQEWBAsaFBkUEQ==');
>   final encrypter = Encrypter(AES(key, mode: AESMode.cbc));
>   final filename = 'foo.txt';
> 
>   await File(filename).writeAsString('Hello world');
>   print(await File(filename).readAsString());
> 
>   final bytes = await File(filename).readAsBytes();
>   print(bytes.length);
> 
>   final encrypted = encrypter.encryptBytes(bytes, iv: iv);
>   print(encrypted.base64);
> 
>   await File('$filename.encrypted').writeAsBytes(encrypted.bytes);
>   print((await File('$filename.encrypted').readAsBytes()).length);
> 
>   final encryptedBytes = await File('$filename.encrypted').readAsBytes();
>   final decrypted = encrypter.decrypt(Encrypted(encryptedBytes), iv: iv);
> 
>   print(decrypted);
> }
> ```
> 
> ```powershell
> issue_107 [master]~ dart .\main.dart
> Hello world
> 11
> gxkljVyioVHMAjAzHC1uSQ==
> 16
> Hello world
> ```
> 
> Your error means that the maybe the key or the iv aren't the same for encryption/decryption.

I'm using `Key.fromSecureRandom(16);
`
  static final key = Key.fromSecureRandom(16);
  static final iv = IV.fromLength(16);

ill try to with same Key and get back

**Comment by leocavalcante** [comment]
You must use the same key and iv pair for encryption and decryption, not a random pair each time. That's the goal of symmetric encryption, a single key securely generated and stored for the encryption and decryption process.
https://en.wikipedia.org/wiki/Symmetric-key_algorithm
