### ISSUE TITLE
Retrieve encrypted string from database

### ISSUE THREAD

**Issue by ptv1p3r** [leocavalcante/encrypt#108]
I'm using your lib, but a question for the implementation
Following the example all works ok, but in my cenario, i'm encrypting a string, that has to go to a database encrypted as base64..

When i need to retrieve this, how sould i do that for it to work ?
Do i need to concatenate iv as base4 and the encrypted also as base64, then split the string when retrieve from the database and decrypt converting the iv from base64 and the string message part ?

This is just a test to make it work 
`             
final key = encrypt.Key.fromUtf8(appSettings.getString('MASTER_ENCRYPT_KEY'));
              final iv = encrypt.IV.fromLength(16);
              final encrypter = encrypt.Encrypter(encrypt.AES(key, mode: encrypt.AESMode.cbc));

              final encrypted = encrypter.encrypt(_password, iv: iv);
              print(encrypted.bytes);
              print(encrypted.base64);

              final b64data = encrypted.base64;
              final b64iv = iv.base64;

              final token = '$b64iv$b64data';

              final token_iv = token.substring(1,24);
              final token_data = token.substring(24);

              final teste_iv = encrypt.IV.fromUtf8(token_iv);
              final teste_data =  encrypt.Encrypted.fromUtf8(token_data);

              final decrypted = encrypter.decrypt(encrypted, iv: iv); -> ok
              final decrypted2 = encrypter.decrypt(teste_data, iv: teste_iv); -> not ok
              
              print(decrypted); -> ok
              print(decrypted2);` -> not ok

**Comment by leocavalcante** [comment]
Try restoring the IV from base 64:
```dart
final teste_iv = encrypt.IV.fromBase64(token_iv);
```

But I'd recommend you to do a bytes merge instead of their base 64 representations:
```dart
import 'dart:convert';

import 'package:encrypt/encrypt.dart';

const KEY = 'CgwNHAkbGhAEGwEfIAEKGgwPGQwGBRAeCwcUFxgeFh8=';
const IV_LENGTH = 16;

final encrypter = Encrypter(AES(Key.fromBase64(KEY), mode: AESMode.cbc));

String encrypt(String data) {
  final iv = IV.fromSecureRandom(IV_LENGTH);
  final encrypted = encrypter.encrypt(data, iv: iv);
  return base64.encode(List.from(iv.bytes)..addAll(encrypted.bytes));
}

void main() {
  final base64Token = encrypt("Hello world");
  print(base64Token);

  final bytesToken = base64.decode(base64Token);

  // First 16 (IV_LENGTH) bytes are the IV
  final iv = IV(bytesToken.sublist(0, IV_LENGTH));

  // From the 16 is the encrypted input
  final encrypted = Encrypted(bytesToken.sublist(16));

  final decrypted = encrypter.decrypt(encrypted, iv: iv);
  print(decrypted);
}
```
```pwsh
issue_108 [master]~ dart .\main.dart
bnORmJBOiz2JXNob5up1Y2ZtV8bjCHO/NrPbIM1Lhco=
Hello world
issue_108 [master]~ dart .\main.dart
yqMwbxGh1alErQhKcTrQPyUmlawFKKKY9uQamwu8WDs=
Hello world
```

**Comment by ptv1p3r** [comment]
Thank you, just used your example and this seems to be working as expected! 👍
