### ISSUE TITLE
Decrypt encrypted string

### ISSUE THREAD

**Issue by ptv1p3r** [leocavalcante/encrypt#109]
I've used your lib to encrypt/decrypt in dart with success.
Now the encrypted string is stored in the database, and it needs to be decrypted in python 3 using this lib : https://nitratine.net/blog/post/python-encryption-and-decryption-with-pycryptodome/

But using the same method cbc, it gives me a error on the unpad.. does this make sence to you ? do you do a pad on the encrypt using cbc on your side ?

**Comment by leocavalcante** [comment]
Can you share the Dart snippet that does the encryption and the Python snippet that does the decryption, please?

**Comment by ptv1p3r** [comment]
I have changed to mode cfb64 on dart side so that on python side no padding should be required.
On dart all is good.
`// get application settings
  static GlobalConfiguration _appSettings = new GlobalConfiguration();

  // encrypt key
  static final _KEY = Key.fromBase64(_appSettings.getString('MASTER_ENCRYPT_KEY'));

  // encrypt iv byte length
  static const _IV_LENGTH = 16;

  // encrypt mode
  static final _encrypter = Encrypter(AES(_KEY, mode: AESMode.cfb64));

  // encrypt data function
  static String encryptData(String data) {
    var base64Token;

    try{

      final iv = IV.fromSecureRandom(_IV_LENGTH);
      final encrypted = _encrypter.encrypt(data, iv: iv);
      base64Token = base64.encode(List.from(iv.bytes)..addAll(encrypted.bytes));

    } catch (error) {
      base64Token = error.toString();
    }

    return base64Token;
  }


  // decrypt data function
  static String decryptData(String data) {
    var decrypted;

    try{
      final bytesToken = base64.decode(data);

      // First 16 (IV_LENGTH) bytes are the IV
      final iv = IV(bytesToken.sublist(0, _IV_LENGTH));

      // From the 16 is the encrypted input
      final encrypted = Encrypted(bytesToken.sublist(_IV_LENGTH));

      decrypted = _encrypter.decrypt(encrypted, iv: iv);

    } catch(error) {
      decrypted = error.toString();
    }

    return decrypted;
  }`

On python 3.7 using the above lib, on mode cfb it's all working ok, the problem arises when on python trying to decrypt the encrypted string from dart.

`def decryptUserPassword(token):
    try:
        key = AES_KEY_CITYGUIDE.encode()  # defaults to utf8 creates byte array
        # split link into iv and data
        bytesToken = b64decode(token)

        bytesData = io.BytesIO(bytesToken)
        iv = bytesData.read(16)
        data = bytesData.read()

        decrypter = AES.new(key, AES.MODE_CFB, iv)  # setup decrypter with key cfb mode and data iv
        decrypter_data = decrypter.decrypt(data)  # decrypted data
        decoded_data = decrypter_data.decode()  # defaults to utf8 creates byte array

    except Exception as ex:
        decoded_data = None

    return decoded_data`

**Comment by leocavalcante** [comment]
This part `data = bytesData.read()`, the data should be read from the 16 byte forward, this is maybe reading all the bytes.

**Comment by ptv1p3r** [comment]
I thought that also, but on debug it looks ok, reading all the bytes from 16 to the end..

**Comment by ptv1p3r** [comment]
It trows an error  here decoded_data = decrypter_data.decode()  that it cant read the first byte.. on cbc it trows a error on unpadding

**Comment by leocavalcante** [comment]
I'm sorry. I'm afraid I don't know Python enough to help you is this quest...
