### ISSUE TITLE
Padding required when decrypting using AES CTR mode

### ISSUE THREAD

**Issue by ydotmalik** [leocavalcante/encrypt#110]
I get this exception when I try to decrypt something in AES CTR mode:

```
E/flutter (19095): Invalid argument(s): Input data length must be a multiple of cipher's block size
E/flutter (19095): #0      PaddedBlockCipherImpl.process (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:55:9)
E/flutter (19095): #1      AES.decrypt (package:encrypt/src/algorithms/aes.dart:38:20)

```

Here is my code:

    final encrypter = encrypt.Encrypter(encrypt.AES(key, mode: encrypt.AESMode.ctr));
    final decrypted = encrypter.decrypt(encrypt.Encrypted.fromBase16(cipher), iv: iv);

```cipher``` is a hexadecimal string of length 10.  I thought AES CTR mode did not require any padding.  It seems like the code shouldn't be going to padded_block_cipher_impl.dart.

**Comment by ydotmalik** [comment]
For reference, I worked around this by using Pointy Castle directly:

```
import 'package:encrypt/encrypt.dart' as encrypt;
import 'package:pointycastle/export.dart' as pc;

String decrypt(String cipher, Uint8List key, Uint8List iv) {
  final encryptedText = encrypt.Encrypted.fromBase16(cipher);
  final ctr = pc.CTRStreamCipher(pc.AESFastEngine())
    ..init(false, pc.ParametersWithIV(pc.KeyParameter(key.bytes), iv.bytes));
  Uint8List decrypted = ctr.process(encryptedText.bytes);

  print(String.fromCharCodes(decrypted));

  return String.fromCharCodes(decrypted);
}
```

encrypt's utilities for coverting to a Uint8List came in handy.

**Comment by leocavalcante** [comment]
You can padding `null` to padding, to avoid it to be used:
```dart
final encrypter = encrypt.Encrypter(encrypt.AES(key, mode: encrypt.AESMode.ctr, padding: null));
```
