### ISSUE TITLE
I need PKCS5 Padding so where is that?

### ISSUE THREAD

**Issue by mhbdev** [leocavalcante/encrypt#111]
`Unhandled Exception: RegistryFactoryException: No algorithm registered of type Padding with name: PKCS5`

I'm always getting the exception above when I am creating Encrypter object!

**Comment by leocavalcante** [comment]
I'm sorry, but there is no PKCS5 padding.
Dup: #99 #48

**Comment by mhbdev** [comment]
I know but is there any way to make it on my own?

**Comment by leocavalcante** [comment]
Maybe https://pub.dev/packages?q=pkcs5 🤷

**Comment by nateshmbhat** [comment]
Pkcs7 should work for a server with PKCS5 padding.

I just tested it for my server which uses PKCS5 while using Pkcs7 padding at encryption.

Pointy castle guys say they both should work the same.
