### ISSUE TITLE
Invalid argument(s): Initialization vector must be the same length as block size

### ISSUE THREAD

**Issue by nirvan-odb** [leocavalcante/encrypt#112]
```
     final key = encrypyt.Key.fromUtf8('a 32character long string');
     final iv = encrypyt.IV.fromLength(32);
     final encrypter = encrypyt.Encrypter(encrypyt.AES(key, mode: encrypyt.AESMode.cbc, padding: 'PKCS7'));
     final encrypted = encrypter.encrypt(plainText, iv: iv);
     final decrypted = encrypter.decrypt(encrypted, iv: iv);
```
Hi, I have the code above and I am getting the error in the title when trying to execute the code.

I know that for AES with CBC mode, the IV and key length must be 256bits or 32 bytes long. Am I wrong in thinking in this way?

Why would I be getting this error? 

Any advice or hints would be appreciated.

**Comment by leocavalcante** [comment]
AES-256 still needs a 128-bit length IV.
https://security.stackexchange.com/questions/90848/encrypting-using-aes-256-can-i-use-256-bits-iv

**Comment by nirvan-odb** [comment]
Thank you for your reply. However, when using a 128-bit length IV, I am getting an exception.

"Unhandled Exception: RangeError (start): Invalid value: Only valid value is 0: -16"

Do you think this may be related to this package or is it something related locally to my project?

**Comment by leocavalcante** [comment]
Can you share the updated snippet, please?

**Comment by nirvan-odb** [comment]
Sure,

```
 final key = encrypyt.Key.fromUtf8('a 32character long string');
     final iv = encrypyt.IV.fromLength(16);
     final encrypter = encrypyt.Encrypter(encrypyt.AES(key, mode: encrypyt.AESMode.cbc, padding: 'PKCS7'));
     final encrypted = encrypter.encrypt(plainText, iv: iv);
     final decrypted = encrypter.decrypt(encrypted, iv: iv);
```

This is being run on tap of a login button.

**Comment by leocavalcante** [comment]
@nirvan-odb 
I just copied and pasted your snippet, even with the typo on `encrypyt`, hehe, and I got:
```
Invalid argument(s): Key length must be 128/192/256 bits
```
And, in fact, `a 32character long string` is 25 UTF-8 bytes, not 32.

Try, this one:
```dart
import 'package:encrypt/encrypt.dart' as encrypyt;

void main() {
  final plainText = 'hello world';
  final key = encrypyt.Key.fromUtf8('a real 32 character long string!');
  final iv = encrypyt.IV.fromLength(16);
  final encrypter = encrypyt.Encrypter(encrypyt.AES(key, mode: encrypyt.AESMode.cbc, padding: 'PKCS7'));
  final encrypted = encrypter.encrypt(plainText, iv: iv);
  final decrypted = encrypter.decrypt(encrypted, iv: iv);

  print(decrypted);
}
```

**Comment by nirvan-odb** [comment]
Hahah I'll go ahead and change that typo right now 

Thank you very much for your help, it was an error on my end, the value for the plain text being passed in was null at some points and therefore gave that error. 

It worked using your main function.

**Comment by leocavalcante** [comment]
Awesome, feel free to open or reopen on any issues. Cheers.
