### ISSUE TITLE
aes how to set zeropadding?

### ISSUE THREAD

**Issue by lumia1999** [leocavalcante/encrypt#114]
aes how to set zeropadding?

**Comment by lumia1999** [comment]
only support  PKCS7?

**Comment by leocavalcante** [comment]
Pass `null` to the  `padding` named parameter on the constructor:
```dart
AES(key, padding: null);
```

**Comment by lumia1999** [comment]
do as it,but not work

    final key = Key.fromUtf8(keyStr);
    final iv = IV.fromUtf8(ivStr);
    final encrypter = Encrypter(AES(key, mode: AESMode.cbc, padding: null));
    final encrypted = encrypter.encrypt(content, iv: iv);
    return encrypted.base64;


I/flutter (17612): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (17612): The following ArgumentError was thrown while handling a gesture:
I/flutter (17612): Invalid argument(s): Input buffer too short
I/flutter (17612): When the exception was thrown, this was the stack:
I/flutter (17612): #0      CBCBlockCipher._encryptBlock (package:pointycastle/block/modes/cbc.dart:68:7)
I/flutter (17612): #1      CBCBlockCipher.processBlock (package:pointycastle/block/modes/cbc.dart:63:13)
I/flutter (17612): #2      AES._processBlocks (package:encrypt/src/algorithms/aes.dart:45:25)
I/flutter (17612): #3      AES.encrypt (package:encrypt/src/algorithms/aes.dart:22:24)
I/flutter (17612): #4      Encrypter.encryptBytes (package:encrypt/src/encrypter.dart:12:19)
I/flutter (17612): #5      Encrypter.encrypt (package:encrypt/src/encrypter.dart:20:12)
I/flutter (17612): #6      AesUtil.encodeAesStr (package:ruyi/utils/aes_util.dart:11:33)
I/flutter (17612): #7      post (package:ruyi/api/netUtils.dart:49:21)
I/flutter (17612): #8      UserService.login (package:ruyi/model/user_repository.dart:17:20)
I/flutter (17612): #9      UserRepository.login (package:ruyi/model/user_repository.dart:26:20)
I/flutter (17612): #10     UserProvider.login (package:ruyi/viewmodel/user_provider.dart:49:10)
I/flutter (17612): #11     _LoginPageState._login (package:ruyi/view/login_page.dart:290:23)
I/flutter (17612): #12     _LoginPageState.loginButton.<anonymous closure>.<anonymous closure> (package:ruyi/view/login_page.dart:234:15)
I/flutter (17612): #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (17612): #14     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
I/flutter (17612): #15     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
I/flutter (17612): #16     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
I/flutter (17612): #17     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (17612): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter (17612): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (17612): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (17612): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (17612): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (17612): #26     _invoke1 (dart:ui/hooks.dart:274:10)
I/flutter (17612): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)

**Comment by leocavalcante** [comment]
Can you share what `keyStr`, `ivStr` and specially `content` are?
Since you aren't using auto-padding, you should make sure that the content is multiple of the key size.

**Comment by lumia1999** [comment]
here is it,
 
 static String keyStr = "e23d8ef964cb1b2f496344140a96f21d";
  static String ivStr = "65afbd767f84c480";

**Comment by lumia1999** [comment]
content:{"account":"aaaa","password":"bbb","loginType":"1"}

**Comment by leocavalcante** [comment]
Your key is a Hexdecimal string, not UTF-8. It has 16 bytes (128 bits).
![image](https://user-images.githubusercontent.com/183722/75770169-3eaeb980-5d26-11ea-9555-ead4d7779149.png)

Your content `{"account":"aaaa","password":"bbb","loginType":"1"}` is 51 one-byte utf-8 characters:
![image](https://user-images.githubusercontent.com/183722/75770039-f55e6a00-5d25-11ea-8732-511d27407ba6.png)
(408 bits)

408 is not a multiple of 128.
408/128 = 3.1875

**Comment by mhbdev** [comment]
what if a user wants to encrypt something like that?
I mean a content which its length is not a multiple of 128?
What's the solution?

**Comment by leocavalcante** [comment]
@mhbdev that's why we use padding, which is already the default behavior.
