### ISSUE TITLE
Encrypting bytes with RSA throwing Input data too large error.

### ISSUE THREAD

**Issue by brisey006** [leocavalcante/encrypt#117]
How do I use RSA to encrypt bytes?

I am getting the error below.

`E/flutter (25395): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Input data too large
E/flutter (25395): #0      OAEPEncoding._encodeBlock (package:pointycastle/asymmetric/oaep.dart:106:7)
E/flutter (25395): #1      OAEPEncoding.processBlock (package:pointycastle/asymmetric/oaep.dart:97:14)
E/flutter (25395): #2      BaseAsymmetricBlockCipher.process (package:pointycastle/src/impl/base_asymmetric_block_cipher.dart:15:15)
E/flutter (25395): #3      RSA.encrypt (package:encrypt/src/algorithms/rsa.dart:40:30)
E/flutter (25395): #4      MainScaffold.build.<anonymous closure>.<anonymous closure> (package:michaels/main.dart:90:35)
E/flutter (25395): #5      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (25395): #6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (25395): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (25395): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
E/flutter (25395): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
E/flutter (25395): #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
E/flutter (25395): #11     _StreamController._add (dart:async/stream_controller.dart:642:7)
E/flutter (25395): #12     _StreamController.add (dart:async/stream_controller.dart:588:5)
E/flutter (25395): #13     _FileStream._readBlock.<anonymous closure> (dart:io/file_impl.dart:105:19)
E/flutter (25395): #14     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (25395): #15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (25395): #16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (25395): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (25395): #18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (25395): #19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter (25395): #20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter (25395): #21     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (25395): #22     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (25395): #23     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (25395): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (25395): #25     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (25395): #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
`

**Comment by leocavalcante** [comment]
Can you share a snippet of code that reproduces the error?

**Comment by brisey006** [comment]
`Stream<List<int>> inputStream = file.openRead();
          inputStream.listen((chunk) {
            final encrypted = encrypter.encryptBytes(chunk);
            print(encrypted.bytes);
            sink.add(encrypted.bytes);
          }).onDone(() {
            sink.close();
            print('done');
          });`

**Comment by brisey006** [comment]
```
          Stream<List<int>> inputStream = file.openRead();

          inputStream.listen((chunk) {
            final encrypted = encrypter.encryptBytes(chunk);
            print(encrypted.bytes);
            sink.add(encrypted.bytes);
          }).onDone(() {
            sink.close();
            print('done');
          });

**Comment by leocavalcante** [comment]
What is the size of the file?

**Comment by brisey006** [comment]
The file is 25mb. Here I was trying to encrypt it in chunks from a stream which are 65537 bit large per chunk

**Comment by leocavalcante** [comment]
65537 bits is still pretty [big for RSA/PKCS1](https://security.stackexchange.com/questions/33434/rsa-maximum-bytes-to-encrypt-comparison-to-aes-in-terms-of-security). The max is 256 bytes/1960 bits.
