### ISSUE TITLE
2 positional argument(s) expected ,but 1 found

### ISSUE THREAD

**Issue by deusquodmortis** [leocavalcante/encrypt#119]
I am really new to dart and encryption stuff.So I am getting this error 
![image](https://user-images.githubusercontent.com/53172609/76387324-b361a380-6377-11ea-8d30-fe3387b9eb84.png)
I just wanted to encrypt some text w/ hardcoded key & iv. Why am I getting this error can anyone help me please ?

**Comment by leocavalcante** [comment]
Did you modified the `encrypter.dart` file?

**Comment by deusquodmortis** [comment]
I did not modified the encrypter.dart file i look what arguments it wants nothing else.I created 2-3 new applications added the library and it still gives this error.

**Comment by leocavalcante** [comment]
I'm sorry, I'm afraid I can not reproduce this error to help you. Also, it seams something related to your Dart development environment, not the lib itself.
I just ran the tests again on Dart 2.7.1. 

What is your Dart version?

**Comment by deusquodmortis** [comment]
I am using Dart 2.7.0 maybe thats related somehow. I do not have any problems w/ other libs. But I like this one and want to use it.
