### ISSUE TITLE
Input buffer too short

### ISSUE THREAD

**Issue by mhbdev** [leocavalcante/encrypt#121]
I have seen other issues with this title but my situation is a lil bit odd!
everything is fine in my code but aes encrypting does not work with some contents!!!
Can anybody explain why is that?

**Comment by mhbdev** [comment]
And The length of my data of course is not fixed so what can I do for encrypting?

**Comment by leocavalcante** [comment]
Can you share a snippet of code that reproduces the error?

**Comment by mhbdev** [comment]
content: {"username":"2423423423","password":"33333","cc":"98","action":3,"fingerprint":"1a55364f3147a41d4d1dad934d894474838feb1e4671c0d4351f639b07ffb71d","version":1}


```
var aes = Encrypter(
      AES(
          Key.fromBase64(
            "KkctSmFOZFJnVWtYcDJzNXY4eS9CP0UoSCtNYlBlU2g=",
          ),
          mode: AESMode.cbc,
          padding: null),
    );
String encrypted = aes.encrypt(base64Encode(
                utf8.encode(
                  content,
                ),
              ), iv: IV.fromSecureRandom(16)).base64;
```

and the exception is thrown here
`
if ((inpOff + blockSize) > inp.length) {
      throw new ArgumentError("Input buffer too short");
    }
`

**Comment by mhbdev** [comment]
The thing that is so so much funny is this ⬇️ 
{"username":"2423423423","password":**33333**,"cc":"98","action":3,"fingerprint":"1a55364f3147a41d4d1dad934d894474838feb1e4671c0d4351f639b07ffb71d","version":1}

this content is exactly the first content above but with a difference -> 33333 is not in the middle of 2 " double quotations :)

**Comment by leocavalcante** [comment]
So, when not using padding your input should be a multiple of the block size.
AES always use 128 bits (16 bytes) as block size.

When you base64 encode the content:
```json
{"username":"2423423423","password":"33333","cc":"98","action":3,"fingerprint":"1a55364f3147a41d4d1dad934d894474838feb1e4671c0d4351f639b07ffb71d","version":1}
```

You get:
```text
eyJ1c2VybmFtZSI6IjI0MjM0MjM0MjMiLCJwYXNzd29yZCI6IjMzMzMzIiwiY2MiOiI5OCIsImFjdGlvbiI6MywiZmluZ2VycHJpbnQiOiIxYTU1MzY0ZjMxNDdhNDFkNGQxZGFkOTM0ZDg5NDQ3NDgzOGZlYjFlNDY3MWMwZDQzNTFmNjM5YjA3ZmZiNzFkIiwidmVyc2lvbiI6MX0=
```

Which have **212 bytes**, then 212 / 16 = **13,25**.
❌ 212 is not a multiple of 16.

**But**, when you base64 encode the content:
```json
{"username":"2423423423","cc":"98","password":11111,"action":2,"fingerprint":"1a55364f3147a41d4d1dad934d894474838feb1e4671c0d4351f639b07ffb71d","version":1}
```

You get the following String:
```text
eyJ1c2VybmFtZSI6IjI0MjM0MjM0MjMiLCJjYyI6Ijk4IiwicGFzc3dvcmQiOjExMTExLCJhY3Rpb24iOjIsImZpbmdlcnByaW50IjoiMWE1NTM2NGYzMTQ3YTQxZDRkMWRhZDkzNGQ4OTQ0NzQ4MzhmZWIxZTQ2NzFjMGQ0MzUxZjYzOWIwN2ZmYjcxZCIsInZlcnNpb24iOjF9
```

Which has **208 bytes** and 208 / 16 is a perfect **13**, you get 13 blocks.
✔️ **208 is a multiple of 16, just pure coincidence**

---

Why don't you just use padding? Why are you `padding: null`?

**Comment by mhbdev** [comment]
how to have zero padding! CMS pkcs7 is not supported in php openssl library :(

**Comment by mhbdev** [comment]
I am using the same encrypter for both encryption and decryption but I cannot decrypt the message with the same padding in php.

$data = openssl_encrypt($in, 'AES-256-CBC', base64_decode("secretKey"), OPENSSL_ZERO_PADDING, $iv);

**Comment by mhbdev** [comment]
I just found a solution!!!
I have to use 2 different padding for encrypting and decrypting my data :|
Don't know why but encrypt and decrypt paddings are different in php openssl.
Thanks Man
It would be awesome if you make padding variable not final in Algorithm class in my case that will help so much

**Comment by leocavalcante** [comment]
You can use it with PHP's openssl regularly, there is no special things to deal with, there is no need to switch padding, check this out: https://github.com/leocavalcante/encrypt/issues/87#issuecomment-549619391
PHP's default padding behavior is already PKCS7!! https://www.php.net/manual/en/function.openssl-encrypt.php#117208

**Comment by Javed1191** [comment]
> I just found a solution!!!
> I have to use 2 different padding for encrypting and decrypting my data :|
> Don't know why but encrypt and decrypt paddings are different in php openssl.
> Thanks Man
> It would be awesome if you make padding variable not final in Algorithm class in my case that will help so much

Thanks @mhbdev dude your suggession worked for me.

**Comment by swar-101** [comment]
In my case, I had named my maven project folder including an emoji, as soon as I took it out, the error went away! 😄
I guess it must be because maven doesn't accept or parse through emojis i.e. UTF-8 encoding as the directory name.
