### ISSUE TITLE
Invalid or corrupted pad block

### ISSUE THREAD

**Issue by YDJSZY** [leocavalcante/encrypt#122]
I encrypt data then send it to server, the server return success and other encrypt data,but I decrypt fail.
final encrypted = encrypter.encrypt(json.encode(data), iv: iv);
String secretData = encrypted.base64;
Map postData = {
      "params": secretData,
       xxx,
       xxx
    };
var res = await request.login(postData);
final myResData = encrypter.decrypt64(res, iv: iv);
throw error Invalid or corrupted pad block.
I don‘t know what's wrong

**Comment by leocavalcante** [comment]
This error means that the decryption failed. Make sure you are using the same set of algorithm, key and iv for both encryption and decryption processes.
Also, you don't need to encrypt/decrypt things by yourself to send data over network, just use TLS (https).

**Comment by YDJSZY** [comment]
I have set same key and iv. I can decrypt the data of server return with crypto-js, but if i decrypt server data with your encrypt ,it throw error "Invalid or corrupted pad block".

**Comment by YDJSZY** [comment]
Have other reason can cause the error ?

**Comment by leocavalcante** [comment]
1. Can you share the snippet that you use on the server-side to make the encryption and the response?

**Comment by YDJSZY** [comment]
sorry, I have no the server code. but i think that the server use the same key and iv. because i can decrypt it use crypto-js

**Comment by leocavalcante** [comment]
Can you share what `res` from `var res = await request.login(postData);` looks like? Are you sure it is a base64 encoded value?

**Comment by YDJSZY** [comment]
just like +RSebDQQk358GWqMgYkq0ZJx8aO5ng8YJm/Lfy183KmWPWixHBie4Kb1Utjw/pTp+rD5497rhAT+ivqmTw1p5t+LiiJqShnROnOLChAhpMrwIF6RAhE3Ur7MZYwfXWGznElJgNqhFRQ4QBHzBDbiWZQaldUUJOy5TsUM67Ni/EPqwbMBYuTDUXB0XR8mAcDV6RCV/cYBziDAdhfc3P6qqBoUj2jq8oPFs79bLpVFiBBuzwLeFa5vWVCHWob4aYFwBPqES9OpMOqvAqViXzsFj4z28Ei+1fbSTpRo4A3muWjxL3ERMRXrngUrqWYz4JW5PFrEOgmRhvLqnWi7n8jx2bJNgun5ma4HyJGF0FZP5rgbR7b+q392YRr9AjmdsGgct29+ee0vQmrFY8dD2e6uaDHdF4nN6atjk0K04m7389Wau8BEJZdCiJKvpc+mtvwC9km/uGFDjYQigGOgg2lxLPm2M0B9CzaEQEgUxMtNYZY496ODHkI/M4c6bRAOjkJKl1ANum4dyFpbZtm7sefqUwfnfIhao6H/sO5qTZTIy0KxFpNdiYXGINUzfQeV0i8dG46qJ+h/s4L8QE4Z1UFNp+SOyiIHsoV+UWBQB2RDxrbnpBq8Papadcl01oveV1x4LMY8KNuMFdbHwj3B4R8srttcy4cYKcqYMEjsSVtjpsE=

**Comment by leocavalcante** [comment]
Also, the intent of an IV (initialization vector) is to be unique for each encryption process, not the same like the key. Usually the IV is concatenated to the encrypted binary then base64-encoded; you need to make sure what the server is doing.

Can I make some attempts to that? Can you share the key and IV you are using?

**Comment by YDJSZY** [comment]
iv: VVuucs_sec201906
key: VVuucs_sec201906

**Comment by leocavalcante** [comment]
I forgot to ask: what is the algorithm and mode (if AES) server is using? Is it padded with PKCS7?

**Comment by YDJSZY** [comment]
I use PKCS7 in client side, i think the server side is same

**Comment by YDJSZY** [comment]
The server use AES and CBC

**Comment by leocavalcante** [comment]
Your server isn't using padding.
```dart
import 'package:encrypt/encrypt.dart';

void main() {
  final key = Key.fromUtf8('VVuucs_sec201906');
  final iv = IV.fromUtf8('VVuucs_sec201906');

  final encoded =
      '+RSebDQQk358GWqMgYkq0ZJx8aO5ng8YJm/Lfy183KmWPWixHBie4Kb1Utjw/pTp+rD5497rhAT+ivqmTw1p5t+LiiJqShnROnOLChAhpMrwIF6RAhE3Ur7MZYwfXWGznElJgNqhFRQ4QBHzBDbiWZQaldUUJOy5TsUM67Ni/EPqwbMBYuTDUXB0XR8mAcDV6RCV/cYBziDAdhfc3P6qqBoUj2jq8oPFs79bLpVFiBBuzwLeFa5vWVCHWob4aYFwBPqES9OpMOqvAqViXzsFj4z28Ei+1fbSTpRo4A3muWjxL3ERMRXrngUrqWYz4JW5PFrEOgmRhvLqnWi7n8jx2bJNgun5ma4HyJGF0FZP5rgbR7b+q392YRr9AjmdsGgct29+ee0vQmrFY8dD2e6uaDHdF4nN6atjk0K04m7389Wau8BEJZdCiJKvpc+mtvwC9km/uGFDjYQigGOgg2lxLPm2M0B9CzaEQEgUxMtNYZY496ODHkI/M4c6bRAOjkJKl1ANum4dyFpbZtm7sefqUwfnfIhao6H/sO5qTZTIy0KxFpNdiYXGINUzfQeV0i8dG46qJ+h/s4L8QE4Z1UFNp+SOyiIHsoV+UWBQB2RDxrbnpBq8Papadcl01oveV1x4LMY8KNuMFdbHwj3B4R8srttcy4cYKcqYMEjsSVtjpsE=';

  final encrypted = Encrypted.fromBase64(encoded);
  final encrypter = Encrypter(AES(key, mode: AESMode.cbc, padding: null));
  final decrypted = encrypter.decrypt(encrypted, iv: iv);

  print(decrypted);
}
```
```json
{"loginName":"luwenwei@vv.cn","userCode":"oa1242621735752884226","organizeType":1,"thirdOpenId":"","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50SWQiOiIyNzMyNzAiLCJhdWQiOiIiLCJzdWIiOiIiLCJvcmdhbml6ZVR5cGUiOiIxIiwibG9naW5OYW1lIjoibHV3ZW53ZWlAdnYuY24iLCJpc3MiOiJ2dlVVQ1MiLCJleHAiOjE1ODgwODAzMDMsImlhdCI6MTU4NTQ4ODMwMywidXNlckNvZGUiOiJvYTEyNDI2MjE3MzU3NTI4ODQyMjYifQ.7S6PFFz2q9aZc2CXWbWt58USu7iIXpEILugN-xNMdno","thirdOpenType":null,"pwdUpdateTime":"2020-03-27 15:14:00"}
```
Also it is probably using the same IV for all encryption process, this is a security risk, is like using the same salt for every password.

**Comment by YDJSZY** [comment]
Thank you so mush!!!
In fact, i just join the new company three day. so i don‘t know  why the server side developer did that.
Thank you again! I have spent two day in this problem.

**Comment by leocavalcante** [comment]
No problem and congratulations+good luck on your new position.
Feel free to share this issue with your coworkers if you like.

**Comment by preetideswal** [comment]
[https://stackoverflow.com/questions/68742275/decrypt-sting-in-flutter](url)

here is my problem 
 @leocavalcante please help   , if you know any solution    
Thankyou @leocavalcante

**Comment by theDeveloper574** [comment]
hey when decrypt success this show me that message "�}�;{`���fV&" not the actual string message that is writen "hi"
anyone help me with that.
