### ISSUE TITLE
Read XML RSA key

### ISSUE THREAD

**Issue by aBuder** [leocavalcante/encrypt#123]
Hi, 

I'm looking for a solution to read RSA key from XML file. Is there a solution to read RSA key like this format?

```xml
<RSAKeyValue>
    <Modulus></Modulus>
    <Exponent></Exponent>
    <P></P>
    <Q></Q>
    <DP></DP>
    <DQ></DQ>
    <InverseQ></InverseQ>
    <D></D>
</RSAKeyValue>
```

**Comment by leocavalcante** [comment]
Hi,

Please, take a look [here](https://github.com/bcgit/pc-dart/blob/master/test/asymmetric/rsa_test.dart#L9) to see how you can create `RSAPublicKey` and `RSAPrivateKey` directly from modulus, exponent, p and q.

**Comment by aBuder** [comment]
@leocavalcante Thanks for fast help, but I have one question. How I should handle this with this kind of data, It looks like base64

<RSAKeyValue> 
    <Modulus>1znidPBIcMcO7K/53tkTSyKqxlG5Mcws8kVtijS4tyEU4W/FEVWYpOtv+Stnb4Vt</Modulus>
    <Exponent>AQAB</Exponent>
</RSAKeyValue>

**Comment by leocavalcante** [comment]
This base64 string is probably representing a binary, you can use use PointyCastle utils to [decode bytes into `BigInt`](https://github.com/PointyCastle/pointycastle/blob/master/lib/src/utils.dart#L10) (don't forget to `base64.decode` first).
