### ISSUE TITLE
Do the RSA method support the type "use private key to encrypt,and use public key to decrypt"?

### ISSUE THREAD

**Issue by Cqucyf** [leocavalcante/encrypt#127]
I use the 4.0.0 version,but maybe not support.
Expect support soon,thanks.

**Comment by leocavalcante** [comment]
Hi @Cqucyf 
This technique of encrypting with a private key and decrypting with a public key is called signing and is supported: https://github.com/leocavalcante/encrypt/blob/master/test/signer_test.dart
