### ISSUE TITLE
Encrypt PDF file in Python and Decrypt in flutter app

### ISSUE THREAD

**Issue by hereabdulla** [leocavalcante/encrypt#128]
First of all thanks for the great package,

i am developing a medical web application with a flutter mobile client,as per HIPAA compliance,all the files has to be encrypted while in rest as well as in transit,is it possible to encrypt a pdf file in python and decrypt it in Flutter

Thanks in Advance

**Comment by leocavalcante** [comment]
It, is possible, but people have warned about encrypting/decrypting large files.
