### ISSUE TITLE
Decryption at API deployed on Tomcat Server

### ISSUE THREAD

**Issue by rp014947** [leocavalcante/encrypt#129]
I am encrypting login credentials at app level, but i am not able to decrypt the encrypted string at API written in Java for validating the password. I used some codes that i got from searching the githib/stackoverflow etc. But its not working. I wanted to start fresh, so please help - what is it that i do to decrypt the text, are there any standard methods/jar that i need to use.

Basically what is it that i need to do to encrypt text at flutter app level and decrypt the string at java API in tomcat server. Please help thank you.

**Comment by rp014947** [comment]
If any body knows about this please help me.

**Comment by panchalAlpit** [comment]
final str2 = utf8.decode(base64.decode(value));// value in your API encrypting string
      final ekey = Key.Key.fromBase64(Constants.ENCRYPTED_KEY);
      final iv = IV.fromBase64(Constants.ENCRYPTED_IV);
      final encrypter = Encrypter(enc.AES(ekey, mode: enc.AESMode.cbc));
      final decrypted = encrypter.decrypt(Encrypted.fromBase64(str2), iv: iv);

**Comment by rp014947** [comment]
> final str2 = utf8.decode(base64.decode(value));// value in your API encrypting string
> final ekey = Key.Key.fromBase64(Constants.ENCRYPTED_KEY);
> final iv = IV.fromBase64(Constants.ENCRYPTED_IV);
> final encrypter = Encrypter(enc.AES(ekey, mode: enc.AESMode.cbc));
> final decrypted = encrypter.decrypt(Encrypted.fromBase64(str2), iv: iv);

Thank you for your help.
