### ISSUE TITLE
Decrypt data from database

### ISSUE THREAD

**Issue by Conrado916645** [leocavalcante/encrypt#131]
my data are save from my sqflite when retrieve the data how can i decrypt it. iam using AES

**Comment by Conrado916645** [comment]
class PassEncryptDecrypt{ 

static final key = Key.fromUtf8('samplecode'); 
  static final iv = IV.fromLength(16);

  static final encrypter = Encrypter(AES(key));


  encryptPassword(String password){
    return  encrypter.encrypt(password, iv: iv);
  }

   decryptPassword(String password){
    return encrypter.decrypt(password, iv: iv);
  }
}

this is my class I am trying to decrypt the data from the database.

**Comment by Conrado916645** [comment]
I just figured it out thanks.

**Comment by HitendraRathod10** [comment]
Can you give solution here ? I am trying to decrypt data from firebase. But I didn't get expected result.
