### ISSUE TITLE
Running flutter pub get causes dependency issues

### ISSUE THREAD

**Issue by futurelucas4502** [leocavalcante/encrypt#132]
Running "flutter pub get" in management_console_mobile...       
Because every version of flutter_test from sdk depends on crypto 2.1.3 and encrypt 4.0.1 depends on crypto ^2.1.4, flutter_test from sdk is incompatible with encrypt 4.0.1.

**Comment by leocavalcante** [comment]
What's is the version of your Dart SDK?

**Comment by futurelucas4502** [comment]
Ah after updating it fixed the problem thank you
