### ISSUE TITLE
Error when decrypting using unpadded AES-ctr

### ISSUE THREAD

**Issue by Sorunome** [leocavalcante/encrypt#136]
When trying to decrypt AES-ctr without padding, it'll give an error provided the encrypted data is not fully block-sized:

```dart
import 'dart:typed_data';
import 'package:encrypt/encrypt.dart';

void main() {
  // these are all zero only to demonstrate the issue
  final key = Uint8List(32);
  final cipher = Uint8List(44); // just make sure that this isn't block-sized  
  final iv = Uint8List(16);
  final res = AES(Key(key), mode: AESMode.ctr, padding: null).decrypt(Encrypted(cipher), iv: IV(iv));
  print(res.toString());
}
```

Will throw

```
RangeError (index): Index out of range: index should be less than 44: 44
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2209:7)
#1      SICStreamCipher.processBytes (package:pointycastle/stream/sic.dart:61:39)
#2      StreamCipherAsBlockCipher.processBlock (package:pointycastle/adapters/stream_cipher_as_block_cipher.dart:31:18)
#3      AES._processBlocks (package:encrypt/src/algorithms/aes.dart:45:25)
#4      AES.decrypt (package:encrypt/src/algorithms/aes.dart:35:14)
#5      main (file:///home/sorunome/repos/famedly/famedlysdk/test.dart:9:63)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by Sorunome** [comment]
It appears that encrypt is having the same issues.

**Comment by Sorunome** [comment]
As work-around you can, for now, pad your input with 0's until it is full block lengths, and afterwards chop off those extra bytes again.

**Comment by leocavalcante** [comment]
That is why padding exists, to make sure the input block has the desired length. If you set the padding as null you are striping off this functionality, then you have to ensure the block size by yourself (if leading zero, for example like you mentioned), is not a bug or error, is the expected behavior.

**Comment by uhoreg** [comment]
CTR (as well as CFB and OFB) don't require the input to be padded to a specific block size, as the input is XORed with the output of the cipher, rather than being processed by the cipher itself..  See the second paragraph of https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Padding

**Comment by leocavalcante** [comment]
@uhoreg you should open an issue at the PointyCastle project then, is where the implementations live.

**Comment by Sorunome** [comment]
Done....their repos seem to be a bit messy due to moving around a bit, so hoping to have opened on the right repo! https://github.com/bcgit/pc-dart/issues/13

**Comment by AKushWarrior** [comment]
@leocavalcante It's not a pointycastle issue.

https://github.com/leocavalcante/encrypt/blob/7098001c61b4ce1e215cec7d805531efac2268e6/lib/src/algorithms/aes.dart#L13 Look at this line. You use the BlockCipher registry to instantiate AES/CTR. If you use the BlockCipher registry to do this (instead of the StreamCipher) it returns a version of CTR which processes in 64-bit blocks.

```dart
var ctrBlock = BlockCipher('AES/CTR'); //This has 64-bit blocks and needs padding
var ctrStream = StreamCipher('AES/CTR'); //This is a stream cipher and needs no padding
```

**Comment by leocavalcante** [comment]
@AKushWarrior oh, thanks for bringing this up.

**Comment by leocavalcante** [comment]
@Sorunome, please, check if https://pub.dev/packages/encrypt/versions/4.0.2 solves for you. Thanks.

**Comment by Sorunome** [comment]
It seems to fix the issue, thank you!
