### ISSUE TITLE
How do I store data of encrypted type on firebase?

### ISSUE THREAD

**Issue by TheCoolNerd27** [leocavalcante/encrypt#138]
I'm trying to implement RSA encryption and decryption using this package. My question is when I have successfully encrypted the data how do I go about storing it on a database and then retrieving it back to decrypt it. If I just store the base64 string would that be enough data to reconstruct the data to successfully decrypt the string? 
I see this is a similar issue to #108 but that's for AES encryption.

**Comment by leocavalcante** [comment]
You need the key and the iv used in the encryption process too.

**Comment by TheCoolNerd27** [comment]
> You need the key and the iv used in the encryption process too.

But there is no iv used in RSA encryption, we just pass the string to encrypt as per the docs?
`final encrypted = encrypter.encrypt(plainText);`
 `final decrypted = encrypter.decrypt(encrypted);`

**Comment by leocavalcante** [comment]
For RSA you need the private key of the public key pair used in the encryption for the decryption process. Having a key pair, you encrypt with the public key and decrypt with the private key.

**Comment by TheCoolNerd27** [comment]
I'm sorry for not asking the question clearly,
What I'm asking is when I encrypt the string the resultant data-type in Encrypted if I store the base64 of the encrypted data how do I decrypt it as the decrypt function takes data type of encrypted as a parameter.
P.S I have both the private and public keys it's just that I don't know how do I get encrypted type data back from it's base64 which would be stored in a database.

**Comment by leocavalcante** [comment]
Oh, got it, sorry. Yes, the base64 or base16 (hexdecimal) are safe string representations of the actual encrypted bytes for data transfer, serialization and persistence.
You can store the base64 string and use it for the decryption process.

**Comment by TheCoolNerd27** [comment]
`  final decrypted = encrypter.decrypt(Encrypted(b64string));`
Okay,So is this the correct way?

**Comment by leocavalcante** [comment]
No, `Encrypted` receives only bytes on its constructor. But you can use the `decrypt64` sugar:
```dart
final decrypted = encrypter.decrypt64(b64string);
```

**Comment by TheCoolNerd27** [comment]
Okay,
Thanks a lot.
