### ISSUE TITLE
Default mode

### ISSUE THREAD

**Issue by asavchuk** [leocavalcante/encrypt#140]
According to this [Block cipher mode of operation](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation)

> CTR mode (CM) is also known as integer counter mode (ICM) and segmented integer counter (SIC) mode.

Then why are they both available in supported modes: SIC(socaled default) and CTR? 
Aren't they the same mode? What is the difference?

**Comment by leocavalcante** [comment]
Just aliases
