### ISSUE TITLE
Unhandled Exception: type 'String' is not a subtype of type 'Encrypted'

### ISSUE THREAD

**Issue by Zrufy** [leocavalcante/encrypt#146]
I already have an encrypted text that I receive in aes. If I pass this String in the decrypt it gives me this error. Do you have other solutions?

**Comment by shubham100ev** [comment]
Please tell the solution

**Comment by leocavalcante** [comment]
@shubham100ev you just wrap your `String` primitive as bytes in a `Encrypted` value:

```dart
final encrypted = Encrypted(yourEncryptedBytes);
```

There are also helpers to make it easy to use when you have base16 (hexdecimal), base64 or utf-8 representations:

```dart
final encrypted = Encrypted.fromBase16(yourString);
final encrypted = Encrypted.fromBase64(yourString);
final encrypted = Encrypted.fromUtf8(yourString);
```

You need to know what bytes representation you used to store the scripted value.
