### ISSUE TITLE
how to solved this error?

### ISSUE THREAD

**Issue by vipul8815** [leocavalcante/encrypt#148]
Resolving dependencies... (33.8s)
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
Got socket error trying to find package encrypt at https://pub.dartlang.org.

**Comment by leocavalcante** [comment]
Sorry, it seams related to Pub, not the library.
It was analyzed just yesterday: https://pub.dev/packages/encrypt#-analysis-tab-
