### ISSUE TITLE
Large plain text Unable to decrypt using java aes decription 

### ISSUE THREAD

**Issue by ranasng** [leocavalcante/encrypt#151]
If plain text is large json string then it throws exception "Input length must be multiple of 16 when decrypting with padded cipher" in java.

**Comment by leocavalcante** [comment]
Sorry, I don't know where Java fits in here. Have you asked to Java library authors or to Java community? Do you have a small snippet that reproduces the error?

**Comment by ranasng** [comment]
Actually encrypted string that I'm trying to decrypt  is generated using dart encryption library. The function encrypter.encrypt(plainText, iv: iv);  generates byte array, I think this generated byte array is incomplete because there is no closing square bracket after the last element. I am using a large json string as plaintext.  Here is the generated byte array [189, 118, 164, 215, 78, 249, 237, 189, 104, 80, 120, 151, 131, 191, 17, 0, 5, 34, 78, 204, 219, 165, 115, 5, 247, 224, 126, 211, 37, 204, 63, 49, 96, 73, 151, 147, 225, 154, 219, 41, 75, 251, 52, 149, 189, 58, 179, 255, 39, 117, 212, 77, 102, 203, 57, 154, 221, 142, 65, 157, 214, 225, 189, 52, 18, 224, 5, 34, 199, 74, 191, 67, 62, 97, 80, 218, 162, 14, 179, 129, 165, 103, 241, 131, 49, 147, 195, 128, 148, 214, 182, 249, 229, 33, 138, 122, 199, 92, 0, 91, 7, 222, 86, 45, 30, 61, 62, 84, 139, 188, 90, 180, 215, 151, 55, 186, 33, 65, 9, 123, 0, 40, 44, 59, 74, 79, 250, 140, 252, 184, 74, 114, 60, 63, 122, 69, 237, 124, 23, 175, 29, 26, 57, 45, 216, 93, 214, 186, 64, 173, 111, 91, 92, 32, 3, 194, 44, 180, 34, 102, 190, 255, 199, 209, 199, 219, 81, 26, 213, 230, 189, 31, 98, 89, 232, 26, 155, 33, 136, 187, 50, 67, 200, 9, 98, 255, 81, 147, 209, 153, 240, 131, 156, 226, 188, 243, 49, 10, 186, 82, 198, 243, 2, 177, 125, 5, 129, 254, 54, 74, 46, 2, 82, 234, 118, 138, 84, 121, 156, 132, 101, 244, 36, 211, 60, 147, 1

I tried with a small json string that works fine. any suggestion?

**Comment by leocavalcante** [comment]
It is just the console that didn't printed out the entire array because of the long output...
