### ISSUE TITLE
How the server send encrypted text in dart

### ISSUE THREAD

**Issue by AmirGhased** [leocavalcante/encrypt#155]
Send an encrypted string to the server and then reopen the server and encrypt a string with the same Rsa algorithm to be sent to the client.

**Comment by AmirGhased** [comment]
`C# Server :

public static string RsaEncrypt(string data, string pubkey)
        {
            RSAParameters ApublicKey; 
     var pub = GetPublicKeyFromPemFile(pubkey);
            ApublicKey = pub.ExportParameters(false);
            RSAParameters result = new RSAParameters();
            result.Modulus = ApublicKey.Modulus;
            result.Exponent = ApublicKey.Exponent;
            System.Text.UTF8Encoding encoding = new System.Text.UTF8Encoding();
            byte[] DataToEncrypt = encoding.GetBytes(data);
            byte[] encryptedData;

            using (RSACryptoServiceProvider RSA = new RSACryptoServiceProvider(2048))
            {
                RSA.ImportParameters(result);
                encryptedData = RSA.Encrypt(DataToEncrypt, true);
            }
            return Convert.ToBase64String(encryptedData);
        }



Dart Client :


AsymmetricKeyPair rsaGenerateKeyPair({int bitStrength = 2048}) {
  var keyParams =
  new RSAKeyGeneratorParameters(BigInt.parse('65537'), bitStrength, 12);
  var secureRandom = new FortunaRandom();
  var random = new Random.secure();
  List<int> seeds = [];
  for (int i = 0; i < 32; i++) {
    seeds.add(random.nextInt(255));
  }
  secureRandom.seed(new KeyParameter(new Uint8List.fromList(seeds)));
  var rngParams = new ParametersWithRandom(keyParams, secureRandom);
  var k = new RSAKeyGenerator();
  k.init(rngParams);

  return k.generateKeyPair();
}


String decrypt(String cipherBase64, PublicKey pubkey,PrivateKey prvkry ) {
  final encrypter = Encrypter(RSA(publicKey: pubkey, privateKey: prvkry));
  return encrypter.decrypt64(cipherBase64);
}

encodePublicKeyToPem(RSAPublicKey publicKey) {
  var algorithmSeq = new ASN1Sequence();
  var algorithmAsn1Obj = new ASN1Object.fromBytes(Uint8List.fromList([0x6, 0x9, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0xd, 0x1, 0x1, 0x1]));
  var paramsAsn1Obj = new ASN1Object.fromBytes(Uint8List.fromList([0x5, 0x0]));
  algorithmSeq.add(algorithmAsn1Obj);
  algorithmSeq.add(paramsAsn1Obj);

  var publicKeySeq = new ASN1Sequence();
  publicKeySeq.add(ASN1Integer(publicKey.modulus)); 
  publicKeySeq.add(ASN1Integer(publicKey.exponent)); 
  var publicKeySeqBitString = new ASN1BitString(Uint8List.fromList(publicKeySeq.encodedBytes));
  var dataBase641 = base64.encode(publicKeySeq.encodedBytes);
  var dataBase642 = base64.encode(publicKeySeq.elements[1].encodedBytes);
  var topLevelSeq = new ASN1Sequence();
  topLevelSeq.add(algorithmSeq);
  topLevelSeq.add(publicKeySeqBitString);

  var dataBase64 = base64.encode(topLevelSeq.encodedBytes);
  return """-----BEGIN PUBLIC KEY-----\r\n$dataBase64\r\n-----END PUBLIC KEY-----""";
}






`

**Comment by leocavalcante** [comment]
Are you having any errors? Send the error you are getting, please, and a small snippet in Dart code, using this library, that reproduces it.

**Comment by AmirGhased** [comment]
When I send the module and exponet to the server.
The server encrypts, but the client cannot open and decrypt.
And it gives a long character error.

You can send a sample of this connection between the server and the client.
 Did you secure the information between the server and the client?

**Comment by leocavalcante** [comment]
You don't need this library to encrypt http client-server communication, just use regular tls (https).

**Comment by AmirGhased** [comment]
![Code](https://user-images.githubusercontent.com/65483562/85972879-5ea96d80-b9e6-11ea-8a63-4858a21fcc08.jpg)
please check code connect to server.
![Error](https://user-images.githubusercontent.com/65483562/85972923-77198800-b9e6-11ea-862a-de5c07c7d5b7.jpg)
And Error code when Decrypt data in server

**Comment by AmirGhased** [comment]
How to make https (ssl/tls) ?????
Are you have Code Example
