### ISSUE TITLE
Unsupported block type for private key

### ISSUE THREAD

**Issue by alidhkh** [leocavalcante/encrypt#156]
Hi. I'm getting this error when trying to decrypt a text encrypted by Golang using public key generated by Dart:
```
Unsupported block type for private key: 65
```

This is my dart code for generating key pairs and exporting public key:
```dart
AsymmetricKeyPair<RSAPublicKey, RSAPrivateKey> generateKeyPair({int bitLength = 2048}) {
    // Create an RSA key generator and initialize it

    final keyGen = RSAKeyGenerator()
      ..init(ParametersWithRandom(
          RSAKeyGeneratorParameters(BigInt.parse('65537'), bitLength, 2),
          secureRandom()));

    // Use the generator

    final pair = keyGen.generateKeyPair();
    // Cast the generated key pair into the RSA key types

    final myPublic = pair.publicKey as RSAPublicKey;
    final myPrivate = pair.privateKey as RSAPrivateKey;

    return AsymmetricKeyPair<RSAPublicKey, RSAPrivateKey>(myPublic, myPrivate);
  }

  SecureRandom secureRandom() {
    final secureRandom = FortunaRandom();

    final seedSource = Random.secure();
    final seeds = <int>[];
    for (int i = 0; i < 32; i++) {
      seeds.add(seedSource.nextInt(255));
    }
    secureRandom.seed(KeyParameter(Uint8List.fromList(seeds)));

    return secureRandom;
  }

String encodePublicKeyToPem(RSAPublicKey publicKey) {
    var algorithmSeq = new ASN1Sequence();
    var algorithmAsn1Obj = new ASN1Object.fromBytes(Uint8List.fromList([0x6, 0x9, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0xd, 0x1, 0x1, 0x1]));
    var paramsAsn1Obj = new ASN1Object.fromBytes(Uint8List.fromList([0x5, 0x0]));
    algorithmSeq.add(algorithmAsn1Obj);
    algorithmSeq.add(paramsAsn1Obj);

    var publicKeySeq = new ASN1Sequence();
    publicKeySeq.add(ASN1Integer(publicKey.modulus));
    publicKeySeq.add(ASN1Integer(publicKey.exponent));
    var publicKeySeqBitString = new ASN1BitString(Uint8List.fromList(publicKeySeq.encodedBytes));

    var topLevelSeq = new ASN1Sequence();
    topLevelSeq.add(algorithmSeq);
    topLevelSeq.add(publicKeySeqBitString);
    var dataBase64 = base64.encode(topLevelSeq.encodedBytes);

    return """-----BEGIN PUBLIC KEY-----\r\n$dataBase64\r\n-----END PUBLIC KEY-----""";
  }
```

This is my golang code for importing public key and encrypting data:
```go
pk, err := ParseRsaPublicKeyFromPemStr(d.PK)
if err != nil {
    fmt.Println(err)
    return
}
encryptedBytes, err := rsa.EncryptOAEP(sha256.New(),rand.Reader,pk,[]byte("super secret message"),nil)
if err != nil {
    fmt.Println(err)
    return
}
func ParseRsaPublicKeyFromPemStr(pubPEM string) (*rsa.PublicKey, error) {
	block, _ := pem.Decode([]byte(pubPEM))
	if block == nil {
		return nil, errors.New("failed to parse PEM block containing the key")
	}

	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, err
	}

	switch pub := pub.(type) {
	case *rsa.PublicKey:
		return pub, nil
	default:
		break // fall through
	}
	return nil, errors.New("Key type is not RSA")
}
```

And finally decrypting with Dart that throws the exception:
```dart
    final encrypter = Encrypter(RSA(publicKey: this.keyPair.publicKey, privateKey: this.keyPair.privateKey));
    List<int> result = encrypter.decryptBytes(Encrypted(event));
```

**Comment by leocavalcante** [comment]
Where did `this.keyPair.privateKey` comes from?

**Comment by alidhkh** [comment]
> Where did `this.keyPair.privateKey` comes from?

Forgot to place in the code. generateKeyPair() is called from a class and it's value is then assigned to keyPair.

```
keyPair = RsaKeyHelper().generateKeyPair();
```

**Comment by leocavalcante** [comment]
Can you make a small snippet that reproduces the error?

**Comment by alidhkh** [comment]
> Can you make a small snippet that reproduces the error?

Actually I found the cause. If I use `EncryptPKCS1v15` method to encrypt data in golang, decrypting in dart goes successful.

But when I use `EncryptOAEP` the error comes up. I guess PointyCastle does not support OAEP.

**Comment by tahaali54** [comment]
In my case when I got this error the issue was that the data I was trying to decrypt was encrypted using another key pair.

**Comment by susarlanikhilesh** [comment]
@alidhkh  
I create my keys on golang and I want to decode and use the public key in dart. But failing too. 

I'm using same golang to decode from bytestoPublicKey. 
But now I need an equivalent bytestoPublicKey in dart. Any help ? 


All the dart functions throw this error. 
Unhandled exception:
      type 'ASN1Sequence' is not a subtype of type 'ASN1Integer' in type cast

**Comment by aliforever** [comment]
> @alidhkh I create my keys on golang and I want to decode and use the public key in dart. But failing too.
> 
> I'm using same golang to decode from bytestoPublicKey. But now I need an equivalent bytestoPublicKey in dart. Any help ?
> 
> All the dart functions throw this error. Unhandled exception: type 'ASN1Sequence' is not a subtype of type 'ASN1Integer' in type cast

Check these repositories out:
https://github.com/aliforever/go-nodejs-rsa-gcm
https://github.com/aliforever/encryptionbox/blob/master/rsa.go

The first one shows the difference between how encryption is done in Go vs. NodeJS
The second one is a wrapper for encryption functions in Go. 

You can use the second one to convert PEM bytes to PublicKey.

**Comment by susarlanikhilesh** [comment]
I want to convert PEM to PublicKey in my dart program. 

//func (r rsaMethods) PublicKeyFromPKIXPEMBytes(pemBytes []byte) (publicKey *rsa.PublicKey, err error) 
I need equivalent of the above function which converts in dart programming

**Comment by aliforever** [comment]
> I want to convert PEM to PublicKey in my dart program.
> 
> //func (r rsaMethods) PublicKeyFromPKIXPEMBytes(pemBytes []byte) (publicKey *rsa.PublicKey, err error) I need equivalent of the above function which converts in dart programming

This is what I've used on a Dart project with [ninja](https://pub.dev/packages/ninja)
```dart
RSAPublicKey.fromPEM(utf8.decode(base64Decode(pemBase64BytesFromGoServer)));
```

To generate a public key:
```dart
RSAPrivateKey _rsaPrivateKey = RSAPrivateKey.generate(1024);
writeToServer(base64Encode(utf8.encode(_rsaPrivateKey.toPublicKey.toPem(toPkcs1: true))))
```
Hope it helps you

**Comment by susarlanikhilesh** [comment]
It is actually giving error:

Unhandled exception:
Exception: Invalid structure
#0      new RSAPublicKey.fromASN1
package:ninja/…/rsa/rsa.dart:76

**Comment by susarlanikhilesh** [comment]
It is not toPkcs1. 
In go, it is 
`func PublicKeyToBytes(pub *rsa.PublicKey) ([]byte, error) {
	pubASN1, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return nil, err
	}

	pubBytes := pem.EncodeToMemory(&pem.Block{
		Type:  "RSA PUBLIC KEY",
		Bytes: pubASN1,
	})

	return pubBytes, nil
}`

for decoding 
`func BytesToPublicKey(pub []byte) (*rsa.PublicKey, error) {
	block, _ := pem.Decode(pub)
	b := block.Bytes
	ifc, err := x509.ParsePKIXPublicKey(b)
	if err != nil {
		return nil, err
	}
	key, ok := ifc.(*rsa.PublicKey)
	if !ok {
		return nil, err
	}
	return key, nil
}`

So I need PKIX, not pkcs1

**Comment by aliforever** [comment]
> 

Try to see if you could convert pkixx (DER) to PKCS1 pem and use that (because that was the only way I could get it to work), honestly I think Dart has a poor amount of resource regarding encryption/decryption. You need to research about it to be able to get it work. 

I'll let you know if I be able to find a way to parse a Go generated PKIX Der in Dart

**Comment by susarlanikhilesh** [comment]
Sure. Thanks a lot :)
