### ISSUE TITLE
Support SSH private/public key files

### ISSUE THREAD

**Issue by bsutton** [leocavalcante/encrypt#161]
It would be really handy if you could add support for using ssh keys for encrypting/decrypting.

Most people that use ssh will have a pub/private key pair and it would be really convenient if these could be used rather than having to generate a new key pair.

This document (might) help:

https://blog.oddbit.com/post/2011-05-08-converting-openssh-public-keys/#:~:text=Privacy%20Enhanced%20Mail%20(PEM)%20is,in%20big%2Dendian%20order).

**Comment by leocavalcante** [comment]
But you can already use it, it isn't required to generate new ones.

**Comment by bsutton** [comment]
No it throws an error as it doesn't recognise the headers.

**Comment by leocavalcante** [comment]
Which type of key do you use? I think the parser works with RSA only.

**Comment by bsutton** [comment]
I'm on linux and this is the standard ssh key:

-----BEGIN OPENSSH PRIVATE KEY-----
XXXXXX

I've tried changing the header to one of the supported headers but this still fails as then ans1 parser doesn't like it.

Reading the above noted link discusses that ssh uses an odd format for storage of the key.
The keys is most often encrypted as well.

**Comment by bsutton** [comment]
Any chance that you would implement support for ssh keys?

**Comment by leocavalcante** [comment]
It already works with SSH keys, the pair at the `tests/` folder was generated using `ssh-keygen` for example.
I need to know what type of keys do you use, is it RSA? DSA? ECDSA? ED25519? Do you know what is the type of your key?
