### ISSUE TITLE
How create "AESCTR256NoPadding" 

### ISSUE THREAD

**Issue by heinzan** [leocavalcante/encrypt#162]
How create "AESCTR256NoPadding".I cann't find in readme.Thanks.

**Comment by leocavalcante** [comment]
Pass null to padding and use a 256-bit key https://github.com/leocavalcante/encrypt#nozero-padding

**Comment by heinzan** [comment]
I added null but encrypted string is not compatible with java class from server side see https://github.com/leocavalcante/encrypt/issues/164.What difference. @leocavalcante
