### ISSUE TITLE
Invalid argument(s): Input data too large

### ISSUE THREAD

**Issue by WL2012** [leocavalcante/encrypt#168]
when encrypt a long string, catch error 'Input data too large'
such as 'eyJraWQiOiJlWGF1bm1MIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmJtdy5jb25uZWN0ZWQubW9iaWxlMjAuY24uZGx5eHgiLCJleHAiOjE2MDAyMjYwMzYsImlhdCI6MTYwMDEzOTYzNiwic3ViIjoiMDAwNDcxLjhhNDllYTFlNTMyYzQxNzhhYzU1NGQ5OGFmN2UxNmM2LjAzMTIiLCJjX2hhc2giOiJ4aWo5R1ptcFpSTnJyakZNT2FycmNnIiwiZW1haWwiOiIyODMxNzUxNjFAcXEuY29tIiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwiYXV0aF90aW1lIjoxNjAwMTM5NjM2LCJub25jZV9zdXBwb3J0ZWQiOnRydWV9.N0lFAaJq8NXczIu9Ol9PxhbL7Ld1-LLvLsZeEa3ktDp7mJPbuDpfi_RRxOAcyJH_sSKHgWWUZFBtVqBO1X7uQf0GCZ5Sq6U8Rjc4J3H9kK4hN5nwVXI15NFEDXJqLFgQeBnIOS1F2J8zWCD7VCxoMHuDbNSx5EEiu45UL2vOj087hbjntqj3V7rY5Ma0-M0LMkS6lTp54_FFcq1BbbSBG_n3V3I7NoNIGeB8yMN5dC52q4hyxdLLgmIKPL0fVjqriWP4wd05mon40Ali5ZFhUeuAqENergTOJrgG91_c4G8WEU6ON2-R_m00JV9sxdfGxptHYoRLxO0vybFBKg_mvw'

Can you help resolve this issue?

**Comment by leocavalcante** [comment]
What algorithm are you using?

**Comment by giandifra** [comment]
I have same problem with RSA algorithm.

**Comment by leocavalcante** [comment]
Is part of the RSA specification a maximum of 245 bytes: https://security.stackexchange.com/questions/33434/rsa-maximum-bytes-to-encrypt-comparison-to-aes-in-terms-of-security#:~:text=RSA%2C%20as%20defined%20by%20PKCS%231%2C%20encrypts%20%22messages%22%20of,can%20be%20encrypted%20with%20RSA%20is%20245%20bytes.

**Comment by Myzel394** [comment]
@liang-notes how did you resolve this issue?

**Comment by liyajie920112** [comment]
when encrypt a long string, catch error 'Input data too large'

You can use the following code

> Note if the PKCS1Encoding is being used

```dart
import 'package:encrypt/encrypt.dart';
import 'package:pointycastle/export.dart';

static Uint8List concatenateBytes(List<Uint8List> byteList) {
    int totalLength = byteList.fold(0, (sum, bytes) => sum + bytes.length);
    Uint8List result = Uint8List(totalLength);
    int offset = 0;

    for (var bytes in byteList) {
      result.setRange(offset, offset + bytes.length, bytes);
      offset += bytes.length;
    }

    return result;
  }

  static String decryptRSA(String encryptedData) {
    try {
      final cipher = PKCS1Encoding(RSAEngine());
      cipher.init(false, PrivateKeyParameter<RSAPrivateKey>(parsePrivateKey()));

      final encryptedBytes = base64Decode(encryptedData);
      final inputLen = encryptedBytes.length;
      int offLen = 0;
      int i = 0;

      List<Uint8List> byteList = [];

      while (inputLen - offLen > 0) {
        final int chunkSize = (inputLen - offLen > 128) ? 128 : inputLen - offLen;
        final cache = cipher.process(Uint8List.sublistView(encryptedBytes, offLen, offLen + chunkSize));
        byteList.add(cache);
        i++;
        offLen = 128 * i;
      }

      final byteArray = concatenateBytes(byteList);
      return utf8.decode(byteArray);
    } catch (e) {
      print(e);
      return '';
    }
  }

  static String encryptRSA(String plaintext) {
    try {
      final cipher = PKCS1Encoding(pointycastle.RSAEngine())
        ..init(true, PublicKeyParameter<RSAPublicKey>(parsePublicKey()));

      final utf8Bytes = Uint8List.fromList(utf8.encode(plaintext));
      final inputLen = utf8Bytes.length;
      int offLen = 0;
      int i = 0;
      List<Uint8List> bops = [];

      while (inputLen - offLen > 0) {
        final chunkSize = (inputLen - offLen > 117) ? 117 : inputLen - offLen;
        final cache = cipher.process(Uint8List.sublistView(utf8Bytes, offLen, offLen + chunkSize));
        bops.add(cache);
        i++;
        offLen = 117 * i;
      }

      final encryptedData = concatenateBytes(bops);
      final base64Encoded = base64Encode(encryptedData);

      return base64Encoded;
    } catch (e) {
      print(e);
      return "";
    }
  }
```
