### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by praveenb** [leocavalcante/encrypt#172]
Hi 

When i run secure-random command, its giving following error

`Can't load Kernel binary: Invalid kernel binary format version.`

Im using windows 10, below are flutter details

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[!] VS Code (version 1.46.0)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)
```

Please let me know, if any fix for it.

Thank you.

**Comment by leocavalcante** [comment]
This library is not meant to be used with the Dart SDK bundled with Flutter.

Try installing it using `pub global activate webdev` only, WITHOUT prefixing it with `flutter packages`.

**Comment by praveenb** [comment]
It worked fine, When run command in PowerShell. When run in cmd prompt its just closing.

Thank you.
