### ISSUE TITLE
Can the AES libraries support key and initial vector (key, IV)?

### ISSUE THREAD

**Issue by kmusham** [leocavalcante/encrypt#18]
We are planning to use AES encryption on the mobile application and server side.
Server side using Microsoft AES libraries (https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes?view=netframework-4.7.2) but required to pass key and IV to encrypt text. 
but, IV is not supported in your libraries. Do you have any plans to enhance the libraries to include IV and match with standard encryption libraries?

Thanks

**Comment by leocavalcante** [comment]
@kmusham actually, I was in doubt about creating an IV internally or leaving it to the user-space. Now you gave me and good example on how this would be better handled, Thanks. Marking this as bug, since is a breaking problem and handling it as soon as possible. Probably right tomorrow.

**Comment by kmusham** [comment]
Wow! Thanks for a prompt reply. Adding 'IV' support would be a life saver for our project. I was looking for other algorithms that work both on C# and flutter.

**Comment by leocavalcante** [comment]
There we go.

IV moved to user-land:
#### AES
```dart
import 'package:encrypt/encrypt.dart';

void main() {
  final plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
  final key = 'my 32 length key................';
  final iv = IV.fromLength(16);

  final encrypter = Encrypter(AES(key, iv));

  final encrypted = encrypter.encrypt(plainText);
  final decrypted = encrypter.decrypt(encrypted);

  print(decrypted); // Lorem ipsum dolor sit amet, consectetur adipiscing elit
  print(encrypted.base64); // R4PxiU3h8YoIRqVowBXm36ZcCeNeZ4s1OvVBTfFlZRdmohQqOpPQqD1YecJeZMAop/hZ4OxqgC1WtwvX/hP9mw==
}
```

You can create IVs from a given length or from hexdecimal and Base64 strings using:
```dart
IV.fromBase16(hexdecimal)
```
and
```dart
IV.fromBase64(base64EncodedString)
```

This was addressed on v2.0. You can use it right now by referencing it on pub:

```yaml
dependencies:
  kittens:
    git:
      url: git://github.com/leocavalcante/encrypt.git
      ref: v2.0
```

Please, note that v2.0 returns an `Encrypted` object now on `encrypt()` method.
You can get the hexdecimal representation using the `base16` getter:
```dart
print(encrypted.base16);
```
And there is also a getter for a base64 representation:
```dart
print(encrypted.base64);
```
Or you can do whatever you want with the raw bytes:
```dart
print(encrypted.bytes);
```

**Comment by kmusham** [comment]
Thank you so much. Let me work with our server team and make sure that both (mobile and server side C# ) implementations match.

**Comment by leocavalcante** [comment]
Awesome, let me know about any other issues. I'm make some tests on encrypting/decrypting from and to different languages as well.

**Comment by leocavalcante** [comment]
Hi Kiran,
You can use [Pub's Git packages](https://www.dartlang.org/tools/pub/dependencies#git-packages)

For **encrypt**'s branch **v2.0** it would look like:
```yaml
dependencies:
  encrypt:
    git:
      url: git://github.com/leocavalcante/encrypt.git
      ref: v2.0
```

Best,

**Comment by kmusham** [comment]
Hi Leo,

I’m having bit  difficulty in using the APIs.

Our server side team created the follow hash using C# AES libraries,

Just testing if I can decrypt the using the same keys, and IV used. But, I’m getting errors 'I/flutter ( 1260): Invalid argument(s): Input data length must be a multiple of cipher's block size'

Here is test code with sample keys and test data:

testAES() {
  final key = 'my32lengthsupersecretnooneknows1';
  final iv = IV.fromBase64('AAAAAAAAAAAAAAAA');
  final encrypter = Encrypter(AES(key, iv));

  final encrypted =
      'WFdaN3pjT2FMYUk3YklidUFocGJwaEcvejNEL3o1R1RTaWRnd2NmSFB6ST0=';
  final decrypted = encrypter.decrypt(Encrypted.fromBase64(encrypted));

  print('decrypted = $decrypted');
}

Please let me know what I’m missing.

**Comment by leocavalcante** [comment]
Hi Kiran,

Good news and bad news.

**Good news**
I was able to encrypt using C#'s AES:
![image](https://user-images.githubusercontent.com/183722/51865717-497e6a00-232e-11e9-823e-14d0a19525e0.png)

And decrypt using Dart's encrypt:
![image](https://user-images.githubusercontent.com/183722/51865787-7e8abc80-232e-11e9-95d5-fecd4f985777.png)

**Bad news**
This is about AES operation Mode: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

C# uses by default: CBC https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Block_Chaining_(CBC)

encrypt is hard-coded to use SIC mode

Also there is this little gap on key that is accepting only Strings, I'll wrap it on a Key thing instead of forcing to be a String.

---

**Please, give me just a couple hours**. Working on it right now.

**Comment by leocavalcante** [comment]
**There we go!**
The latest commits should be enough to get it working.

You should be able create keys like you do for IVs:
```dart
final key = Key.fromBase64('<base64 encoded key>');
```
You can still create keys from plain UTF-8 strings:
```dart
final key = Key.fromUtf8('mysupersecret32lengthkey');
// IVs as well
final iv = IV.fromUtf8('8bytesiv');
```
And now you can override the default AES mode of operation to match .NET default CBC mode:
```dart
Encrypter(AES(key, iv, mode: AESMode.cbc));
```

# Full example:

## Encrypting on C#
```csharp
using System;
using System.IO;
using System.Security.Cryptography;

namespace csharp
{
  class Program
  {
    static void Main(string[] args)
    {
      using (var aes = Aes.Create())
      {
        var encryptor = aes.CreateEncryptor(aes.Key, aes.IV);

        using (var ms = new MemoryStream())
        {
          using (var cs = new CryptoStream(ms, encryptor, CryptoStreamMode.Write))
          {
            using (var sw = new StreamWriter(cs))
            {
              sw.Write("Hello World");
            }

            Console.WriteLine(Convert.ToBase64String(aes.Key));
            Console.WriteLine(Convert.ToBase64String(aes.IV));
            Console.WriteLine(Convert.ToBase64String(ms.ToArray()));
          }
        }
      }
    }
  }
}
```
### Output
```
5wK5cuDz3oyEV04TVaodjnUR0i8RT9FQmOQk2M3fDD8=
bj/QPy0lAktJZNJrQUVq+Q==
e+7n6mf4G+1MLMcREjRNWg==
```


## Decrypting on Dart
```dart
import 'package:encrypt/encrypt.dart';

void main() {
  final key = Key.fromBase64('5wK5cuDz3oyEV04TVaodjnUR0i8RT9FQmOQk2M3fDD8=');
  final iv = IV.fromBase64('bj/QPy0lAktJZNJrQUVq+Q==');
  final encrypted = Encrypted.fromBase64('e+7n6mf4G+1MLMcREjRNWg==');

  final encrypter = Encrypter(AES(key, iv, mode: AESMode.cbc));
  print(encrypter.decrypt(encrypted));
}
```

**Comment by kmusham** [comment]
Hi Leo,
Thanks for prompt reply.
I’m still getting the same error.

I/flutter ( 3931): Invalid argument(s): Input data length must be a multiple of cipher's block size
I/flutter ( 3931): 
I/flutter ( 3931): When the exception was thrown, this was the stack:
I/flutter ( 3931): #0      PaddedBlockCipherImpl.process (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:55:9)
I/flutter ( 3931): #1      AES.decrypt (package:encrypt/src/aes.dart:36:20)
I/flutter ( 3931): #2      Encrypter.decrypt (package:encrypt/encrypt.dart:32:37)


Here is the updated code:

testAES() {
  final key = Key.fromUtf8('my32lengthsupersecretnooneknows1');
  final iv = IV.fromUtf8('AAAAAAAAAAAAAAAA');

  final encrypted =
      'WFdaN3pjT2FMYUk3YklidUFocGJwaEcvejNEL3o1R1RTaWRnd2NmSFB6ST0=';

  final encrypter = Encrypter(AES(key, iv, mode: AESMode.cbc));

  final decrypted = encrypter.decrypt(Encrypted.fromBase64(encrypted));

  print('decrypted = $decrypted');
}

**Comment by leocavalcante** [comment]
Do you mind to share the C# snippet?
Does it uses **my32lengthsupersecretnooneknows1** as Key?
And does it uses **AAAAAAAAAAAAAAAA** as IV?

And your base64 string seams to a base64 encoding of a already previous base64 string:
![image](https://user-images.githubusercontent.com/183722/51870296-48ebd080-233a-11e9-829d-d1e659594b96.png)

**Comment by leocavalcante** [comment]
**Look!** Changed my C# snippet here to use this *Key* and *IV*.

| Key | IV |
| --- | --- |
| my32lengthsupersecretnooneknows1 | AAAAAAAAAAAAAAAA |

C# Code
```csharp
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace csharp
{
  class Program
  {
    static void Main(string[] args)
    {
      using (var aes = Aes.Create())
      {
        var key = Encoding.UTF8.GetBytes("my32lengthsupersecretnooneknows1");
        var iv = Encoding.UTF8.GetBytes("AAAAAAAAAAAAAAAA");
        var encryptor = aes.CreateEncryptor(key, iv);

        using (var ms = new MemoryStream())
        {
          using (var cs = new CryptoStream(ms, encryptor, CryptoStreamMode.Write))
          {
            using (var sw = new StreamWriter(cs))
            {
              sw.Write("Hello World");
            }

            Console.WriteLine(Convert.ToBase64String(ms.ToArray()));
          }
        }
      }
    }
  }
}
```

Then Dart Code:
```dart
import 'package:encrypt/encrypt.dart';

void main(List<String> args) {
  final key = Key.fromUtf8('my32lengthsupersecretnooneknows1');
  final iv = IV.fromUtf8('AAAAAAAAAAAAAAAA');

  final encrypted = Encrypted.fromBase64(args[0]);
  final encrypter = Encrypter(AES(key, iv, mode: AESMode.cbc));

  print(encrypter.decrypt(encrypted));
}
```

Key and IV are hard-coded now, don't forget they should be the same on both sides.
The notice that I made the Dart code decrypt the Base64 given on the CLI args.
It works perfectly:

```pwsh
> dotnet run -p .\csharp\
< u7oAy2rHPHB1oua+hwl8PA==
> dart .\dart\bin\main.dart u7oAy2rHPHB1oua+hwl8PA==
< Hello World
```

**Comment by kmusham** [comment]
Or, send me your personal email id, I can share you the complete C# class file. 
I do not want to get published on GitHub.

**Comment by leocavalcante** [comment]
Hm, right. Is `SymmetricCrypt` something made by then?
Have you folks already tried using `Encoding.UTF8.GetBytes` instead of `Encoding.ASCII.GetBytes`, I mean: `UTF8` instead of `ASCII`, this should be the case, since they share the same byte, but...

You can e-mail me the full C# and this `SymmetricCrypt` at lc@leocavalcante.com

**Comment by leocavalcante** [comment]
Well, as I suspected, using ASCII did work as well.

The thing here must be on `SymmetricCrypt`, didn't found it on .NET APIs:
https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.2&term=SymmetricCrypt

Is it a class created by your back-end team? Can you share it?

**Comment by kmusham** [comment]
We used UTF8 encoding to encrypt but this time, I see a different issue


I/flutter ( 6996): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6996): The following FormatException was thrown building Builder:
I/flutter ( 6996): Invalid radix-16 number
I/flutter ( 6996): M1
I/flutter ( 6996): 
I/flutter ( 6996): When the exception was thrown, this was the stack:
I/flutter ( 6996): #0      int._throwFormatException (dart:core/runtime/libintegers_patch.dart:130:5)
I/flutter ( 6996): #1      int._parse (dart:core/runtime/libintegers_patch.dart:104:14)
I/flutter ( 6996): #2      int.parse (dart:core/runtime/libintegers_patch.dart:61:12)
I/flutter ( 6996): #3      _createUint8ListFromHexString (package:encrypt/encrypt.dart:122:20)
I/flutter ( 6996): #4      new Encrypted.fromBase16 (package:encrypt/encrypt.dart:54:17)



Code: (with new encrypted text)

testAES() {
  final key = Key.fromUtf8('my32lengthsupersecretnooneknows1');
  final iv = IV.fromUtf8('AAAAAAAAAAAAAAAA');

  final encrypted =
      'M1QvRXhGZVFkVjlLbTN4L1ZGSkhzOXNyQ0NpVERHR3Q3dkRiMXZkT3BTaz0';

  final encrypter = Encrypter(AES(key, iv, mode: AESMode.cbc));

  final decrypted = encrypter.decrypt(Encrypted.fromBase16(encrypted));

  print('decrypted = $decrypted');
}

**Comment by leocavalcante** [comment]
Hm, but this: M1QvRXhGZVFkVjlLbTN4L1ZGSkhzOXNyQ0NpVERHR3Q3dkRiMXZkT3BTaz0
Isn't hex. Hexdecimal use all upper or all lower case letters.
I saw or email, I'll trying some others things here.

**Comment by kmusham** [comment]
Please let me know your recommendations that works on both on C# and flutter. Not sure on what we’re missing here to make it work..

Thank you.

**Comment by leocavalcante** [comment]
Hi @kmusham 
Sorry the delay.

The method `public string Encrypt(string text, byte[] key, byte[] iv)` on the class `SymmetricCrypt` is already return a Base64 String.  So the method `public string EncryptToBase64String(string text)` is Base64 encoding a String that is already Base64 encoded...

If you just call `Encrypt` you will be able to already get a Base64 encoded string and give it to Dart.

## Full code

### C# (using the class you emailed me without any modifications)
```chasrp
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using TokenGenerator;

namespace csharp
{
  class Program
  {
    static void Main(string[] args)
    {
      using (var aes = Aes.Create())
      {
        var key = Encoding.ASCII.GetBytes("my32lengthsupersecretnooneknows1");
        var iv = Encoding.ASCII.GetBytes("AAAAAAAAAAAAAAAA");
        var encryptor = new SymmetricCrypt<AesCryptoServiceProvider>(key, iv);

        Console.WriteLine(encryptor.Encrypt("Hello World"));
      }
    }
  }
}
```

### Dart
```dart
import 'package:encrypt/encrypt.dart';

void main(List<String> args) {
  final key = Key.fromUtf8('my32lengthsupersecretnooneknows1');
  final iv = IV.fromUtf8('AAAAAAAAAAAAAAAA');

  final encrypted = Encrypted.fromBase64(args[0]);
  final encrypter = Encrypter(AES(key, iv, mode: AESMode.cbc));

  print(encrypter.decrypt(encrypted));
}
```
### Output on VSCode terminal
![image](https://user-images.githubusercontent.com/183722/51946364-5ff8f400-2408-11e9-9f1a-2a521abb49b1.png)

**Comment by kmusham** [comment]
Thank you so much Loe. Everything worked well on both ends. We appreciate your time and prompt reply. Let me know when you're going to release the official code to public. As of now, I'm going to use your v2.0 branch.
Thanks.

**Comment by leocavalcante** [comment]
Awesome, glad to help. Feel free to reach me out any support for my libraries.
Best,

**Comment by kmusham** [comment]
When are you releasing 2.0 to public?

**Comment by leocavalcante** [comment]
I'm waiting for some time to review the API and add some more tests.

**Comment by leocavalcante** [comment]
There we go!

**Comment by kmusham** [comment]
Thank you.

**Comment by charulbudania** [comment]
crmLZqrBlV3xdlEvw0JfBw==:Dw9WuCE51rouRUarlZ4Z8Q==
I want to decrypt this type of value 
Can anyone help me?

**Comment by charulbudania** [comment]
import 'package:encrypt/encrypt.dart';

void main() {
  final plainText = 'raaj';
  final data = 'crmLZqrBlV3xdlEvw0JfBw==:Dw9WuCE51rouRUarlZ4Z8Q==';
  final key = Key.fromUtf8('0123456789asdfgh');
  final iv = IV.fromUtf8('1231231231231231');
  final encrypter = Encrypter(AES(key));
  List<String> parts = data.split(":");
  final encrypted = encrypter.encrypt(plainText, iv: iv);
  print(encrypted.base64+":"+iv.base64);
  final decrypted = encrypter.decrypt(encrypted, iv: iv);
  print(decrypted);
}
@leocavalcante please help me to find the solution

**Comment by shivyogkrupa** [comment]
@leocavalcante

i need decrypter for C#.
