### ISSUE TITLE
Can the IV be detected/extracted automatically?

### ISSUE THREAD

**Issue by magnuswikhog** [leocavalcante/encrypt#185]
I'm trying to decrypt something that was encrypted using a Pascal encryption library, with AES-CBC 256-bit encryption. That library stores the IV in the first 16 bytes of the resulting "crypto string". Reading a bit about this, it seems that this is more or less "standard practice".

But so far, the only way I found to decrypt it using this package is to manually extract the first 16 bytes from the crypto, use those to create the IV and then decrypt the rest of the crypto. If this is indeed the standard way of storing IV and crypto together, then I would expect that there would be a decryption method that automatically does all this.

Perhaps there is, and I just didn't find it?

**Comment by leocavalcante** [comment]
There is not. Today this should be done manually indeed.
