### ISSUE TITLE
What is the implementation option for the Salsa20 algorithm (8,12 or 20 rounds of encryption) 

### ISSUE THREAD

**Issue by kostasoft** [leocavalcante/encrypt#186]
Thank you so much for the library! Everything is super, it works on mobile devices and on the Web.
I would like to know if you use classic Salsa20 or Salsa20/8 (Salsa20/12) algorithm?

And have you found a library for Node.js that can encode/decode data from your library (only interested in Salsa20 as the fastest algorithm)?

**Comment by leocavalcante** [comment]
Hi, thanks!
Well I guess it is the classic but you can check at the https://github.com/bcgit/pc-dart project, is where the algorithms are actually implemented.
For Node.js, from previous issue I saw that `crypto` was working ok.
