### ISSUE TITLE
how to create a public.pem and private.pem

### ISSUE THREAD

**Issue by NTMS2017** [leocavalcante/encrypt#190]
Hi,

I need to create my own public.pem and private.pem to use in my app instead of the example in test folder.
How to create my own  public.pem and private.pem?

Thanks

**Comment by leocavalcante** [comment]
Have you tried `openssl`? `ssh-keygen`?

**Comment by NTMS2017** [comment]
No, I didnt. Any example for that?

**Comment by leocavalcante** [comment]
Check at least the first 10 results https://www.google.com/search?q=generate+rsa+key+pair

**Comment by NTMS2017** [comment]
Thank you, I will. 👍🙏
