### ISSUE TITLE
Invalid argument(s): Error Input buffer too short

### ISSUE THREAD

**Issue by kttary** [leocavalcante/encrypt#192]
I'm translating AES encryption from java to flutter using encrypt. Here is my flutter code:

```
final String initVectorClient = "1234567811111111";
final String keyClient = "4456445699999999";
final key = Key.fromUtf8(keyClient);
final iv = IV.fromUtf8(initVectorClient);
final encrypter = Encrypter(AES(key, mode: AESMode.cbc, padding: null));

String result = encrypter.encrypt("8EQEKSOQ", iv: iv).base64;
```

unfortunately the last line give me an error Invalid argument(s): Error Input buffer too short. I couldn't find my mistake. Pls help

**Comment by leocavalcante** [comment]
Please, see https://github.com/leocavalcante/encrypt/issues/10

**Comment by kttary** [comment]
i tried to 8 character long as string input '8EQEKSOQ8EQEKSOQ' and it encrypted succesfully. However, given the same iv and key both in java and flutter gave me different result. 

> // Java Result::::: TS/xuuBrzKeqVrFLBb/dzqcNLLozx1uzEep6VS5C2Kw= 
> // Flutter Result:: TS/xuuBrzKeqVrFLBb/dzg==

any clue?

**Comment by kcibdev** [comment]
> i tried to 8 character long as string input '8EQEKSOQ8EQEKSOQ' and it encrypted succesfully. However, given the same iv and key both in java and flutter gave me different result.
> 
> > // Java Result::::: TS/xuuBrzKeqVrFLBb/dzqcNLLozx1uzEep6VS5C2Kw=
> > // Flutter Result:: TS/xuuBrzKeqVrFLBb/dzg==
> 
> any clue?

Any update on your problem? did you finally solve it

**Comment by kttary** [comment]
luckily i have flexibility to use PKCS7 instead of zero padding

**Comment by kcibdev** [comment]
> luckily i have flexibility to use PKCS7 instead of zero padding

Please can you show how you did. Thank you

**Comment by kttary** [comment]
what have you done?

**Comment by kcibdev** [comment]
> what have you done?

Oh don't worry i finally found the solution
I used the same unique generated key for both IV and Key
