### ISSUE TITLE
AES encryption not working with Persian & Arabic chars

### ISSUE THREAD

**Issue by bkhezry** [leocavalcante/encrypt#196]
I want to encrypt Persian word like سلام
and get this exception:
`Unhandled Exception: Invalid argument(s): Input buffer too short`

How can I use this encryption with Unicode string?

**Comment by leocavalcante** [comment]
Block-cyphers only works with a fixed-size length for both input and output
https://en.wikipedia.org/wiki/Block_size_(cryptography)

AES block-size is 128 bits
https://en.wikipedia.org/wiki/Advanced_Encryption_Standard

128 bits = 16 bytes and `سلام` is half of it.
![image](https://user-images.githubusercontent.com/183722/108847047-fbe09400-75bd-11eb-97e0-dae1319cdc01.png)

Just like #8 and #10
