### ISSUE TITLE
Native android Java

### ISSUE THREAD

**Issue by PrincEddy** [leocavalcante/encrypt#197]
is there any equivalent of this plugin in Java for native android development? some of my client's phones are not compatible with flutter so I need to develop a client app using native

**Comment by praveenb** [comment]
Hi,
I tried in Native Android, 
https://github.com/leocavalcante/encrypt/issues/164#issuecomment-795330857

you may try it
Thanks

**Comment by PrincEddy** [comment]
@praveenb thank you. Sure I will try it
