### ISSUE TITLE
Create md5 from a custom string

### ISSUE THREAD

**Issue by marcellocamara** [leocavalcante/encrypt#199]
With Encrypt is possible to generate a MD5 string from a custom String ? 

I need that user choose his own key, instead of providing my own!

I'm using something like this:
```
final _myKey = "my32lengthsupersecretnooneknows1";

String encrypt(String value) {
  var key = Key.fromUtf8(_myKey);
  var iv = IV.fromLength(16);
  return Encrypter(AES(key)).encrypt(value, iv: iv).base64;
}
```

There's an way with Crypto package:
```
var bytes = utf8.encode("customString");
var md5Result = md5.convert(bytes).toString();
```
But, I don't want to use another package. Or should I ?

I didn't found a way to do it on readme and the code.

**Comment by leocavalcante** [comment]
Encrypt focuses on two-way cryptography (the ones you can encrypt and decrypt), this excludes hashing/digest algorithms like MD5. But you can use PointyCastle directly.

**Comment by marcellocamara** [comment]
@leocavalcante Entendi, Leo.

Há uma forma de criar uma `Key` utilizando minha string customizada de tamanho variável ou é uma regra utilizar uma string de 32 chars ?

Eu citei na dúvida a md5 pois ao gerar uma md5 ela já contém os 32 chars.

**Comment by leocavalcante** [comment]
Opa, então, o tamanho da chave pro AES pode ser 128, 192 ou 256 bits (https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) que seria 12, 24 ou 32 bytes.

Quanto maior o tamanho da chave, mais seguro, você aumenta a complexidade pra casos de brute-force (https://en.wikipedia.org/wiki/Key_size) então 32 bytes que é o máximo seria o recomendado.

**32 bytes não é necessariamente o mesmo que 32 chars**, isso só acontece na ASCII, mas na Unicode alguns caracteres podem ter até 4 bytes (https://en.wikipedia.org/wiki/Variable-width_encoding)

Gerar chaves maiores a partir de chaves menores, tipo fazer `meu-segredo` virar uma chave de 32 bytes se chama Key Derivation (https://en.wikipedia.org/wiki/Key_derivation_function) Acabei não documentando na README, mas tem nos exemplos: https://github.com/leocavalcante/encrypt/blob/4.x/example/stretch.dart#L7 você só vai precisar de um Salt (https://en.wikipedia.org/wiki/Salt_(cryptography)) pra deixar mais seguro, recomendo um salt pra cada derivation/stretch que for fazer, assim você evita rainbow-table.
