### ISSUE TITLE
Help Learning and Coding.

### ISSUE THREAD

**Issue by NTMS2017** [leocavalcante/encrypt#2]
Good morrning Leo Cavalcante, this is awesome news for us. I will try it today and donate. Thank you very much. At last we can make 2 way encrypted communication between Flutter and aqueduct... 5 am in my country now. I will test this when I go to work. Kind Regards...

**Comment by leocavalcante** [comment]
Hi @NTMS2017 
Thank you for your support!
This motivates doing more open-source code!
Best,
