### ISSUE TITLE
Promote the 5.x release as the latest stable version as of the Dart 2.12 release

### ISSUE THREAD

**Issue by dokinkon** [leocavalcante/encrypt#200]
Thanks your awesome package. Recently Flutter 2 was just announced and Dart null-safety is stable.

How about migrate this package into null-safety? Thanks

**Comment by leocavalcante** [comment]
https://pub.dev/packages/encrypt/versions/5.0.0-beta.1
https://github.com/leocavalcante/encrypt/tree/5.x
https://github.com/leocavalcante/encrypt/pull/195

**Comment by pushpendraKh** [comment]
@leocavalcante What about bumping the version to 5.0.0 (stable release)?

**Comment by leocavalcante** [comment]
@pushpendraKh that is the purpose of this issue

**Comment by leocavalcante** [comment]
[`5.0.0`](https://pub.dev/packages/encrypt/versions/5.0.0) is now stable, thank you folks for the patience.

**Comment by Droidlover** [comment]
> [`5.0.0`](https://pub.dev/packages/encrypt/versions/5.0.0) is now stable, thank you folks for the patience.

Thank you very much :)

**Comment by NTMS2017** [comment]
Thanks @leocavalcante. 👍 🥇
