### ISSUE TITLE
crypto dependency issue

### ISSUE THREAD

**Issue by cultivatebuddy** [leocavalcante/encrypt#201]
Getting this error:
Because encrypt 4.1.0 depends on crypto ^2.1.5 and no versions of encrypt match >4.1.0 <5.0.0, encrypt ^4.1.0 requires crypto ^2.1.5.

Because of the above, I am unable to upgrade the crypto lib to latest 3.0.0 version. Kindly help with how to resolve this.

**Comment by NickNevzorov** [comment]
Have a same issue
Fix please

Tnx!

**Comment by nikhilbadyal** [comment]
Same issue 
```Because encrypt >=4.1.0 <5.0.0-beta.1 depends on crypto ^2.1.5 and notes depends on crypto ^3.0.0, encrypt >=4.1.0 <5.0.0-beta.1 is forbidden.```

Can you fix please. I'm not able to use other packages like json_store. Because they depends on encrypt. Can you please update the crypto dependency to 3.0.0

**Comment by leocavalcante** [comment]
[`5.0.0`](https://pub.dev/packages/encrypt/versions/5.0.0) is now stable and running with `crypto 3.0.0`, thank you folks for the patience.

**Comment by AhmedAlsamet** [comment]
**Hi i faced the same problem now in version 5.0.3**

Because no versions of encrypt match 5.0.3 and no versions of encrypt match >5.0.3 <6.0.0, encrypt ^5.0.3 is forbidden.
So, because prject depends on encrypt ^5.0.3, version solving failed.

**Any Help?**
