### ISSUE TITLE
Incompatible dependency with flutter_driver for 5.0.0-beta.1

### ISSUE THREAD

**Issue by robsonmeemo** [leocavalcante/encrypt#202]
```
Because every version of flutter_driver from sdk depends on crypto 2.1.5 and encrypt >=5.0.0-beta.1 depends on crypto ^3.0.0, flutter_driver from sdk is incompatible with encrypt >=5.0.0-beta.1.
```

**Comment by leocavalcante** [comment]
Maybe related #201

**Comment by leocavalcante** [comment]
Try to upgrade your `flutter_driver` [it seems to be already using `crypto 3.0.0`](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/pubspec.yaml#L29).

If you can't, then fallback to [`encrypt 4.x`](https://pub.dev/packages/encrypt/versions/4.1.0) which uses `crypto ^2.1.5`.
