### ISSUE TITLE
AES/CFB/NoPadding

### ISSUE THREAD

**Issue by OLibraQ** [leocavalcante/encrypt#203]
Encrypter(AES(key, mode: AESMode.cfb64, padding: null));

------------------------------------------------
 Unhandled Exception: Invalid argument(s): Input buffer too short

**Comment by leocavalcante** [comment]
Duplicated:
#8 #10 #196

**Comment by OLibraQ** [comment]
How do I use CFB encryption?
Encryption mode is used cfb64 ?

**Comment by ParmarPravin** [comment]
#   Error Encrypter
