### ISSUE TITLE
_streamable  not contain AESMode.cbc

### ISSUE THREAD

**Issue by memtopia** [leocavalcante/encrypt#206]
```
enum AESMode {
  cbc,
  cfb64,
  ctr,
  ecb,
  ofb64Gctr,
  ofb64,
  sic,
}

const Map<AESMode, String> _modes = {
  AESMode.cbc: 'CBC',
  AESMode.cfb64: 'CFB-64',
  AESMode.ctr: 'CTR',
  AESMode.ecb: 'ECB',
  AESMode.ofb64Gctr: 'OFB-64/GCTR',
  AESMode.ofb64: 'OFB-64',
  AESMode.sic: 'SIC',
};

const List<AESMode> _streamable = [
  AESMode.sic,
  AESMode.ctr,
];
```

As source code , why _streamable not contain AESMode.cbc, I have an issue that needs to use AESMode.cbc with zero padding, any solution? Thanks.

**Comment by leocavalcante** [comment]
CBC is not streamable, is a block cipher mode: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_block_chaining_(CBC)

And to remove padding, just pass `null` to it:
https://github.com/leocavalcante/encrypt#nozero-padding

**Comment by memtopia** [comment]
> CBC is not streamable, is a block cipher mode: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_block_chaining_(CBC)
> 
> And to remove padding, just pass `null` to it:
> https://github.com/leocavalcante/encrypt#nozero-padding

but   refer to this page   [](https://the-x.cn/en-us/cryptography/Aes.aspx)   select cbc and  zero padding , and  input any length text, no need to length == 16 , I got  correct result, 

example: input 123456     key : ABC1234567890abc    iv:ABC1234567890abc   correct  output  "O7d7/wniQQiEzhmtkqnq0Q==" 


and  in java there is `Cipher cipher = Cipher.getInstance("AES/CBC/NoPadding");`  indeed, how?
