### ISSUE TITLE
Unhandled Exception: Invalid argument: Instance of 'Encrypted'

### ISSUE THREAD

**Issue by ScottishRoss** [leocavalcante/encrypt#208]
Error: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument: Instance of 'Encrypted'

This is the code I'm running:
`final key = Key.fromLength(32);
  final iv = IV.fromLength(8);
  final encrypter = Encrypter(Salsa20(key));

  final encryptedString = encrypter.encrypt(victory, iv: iv);
  print (encryptedString);`

```
I/flutter (31208): Instance of 'Encrypted'
E/flutter (31208): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument: Instance of 'Encrypted'
E/flutter (31208): #0      convertPlatformException (package:cloud_firestore_platform_interface/src/method_channel/utils/exception.dart:13:5)
E/flutter (31208): #1      MethodChannelDocumentReference.set (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:43:13)
E/flutter (31208): <asynchronous suspension>
E/flutter (31208): #2      CollectionReference.add (package:cloud_firestore/src/collection_reference.dart:47:5)
E/flutter (31208): <asynchronous suspension>
E/flutter (31208): #3      saveLittleVictory.<anonymous closure> (package:social_sign_on/data/firestore_operations.dart)
E/flutter (31208): <asynchronous suspension>
E/flutter (31208): 
```

I'm doing simple string encryption here, nearly exactly the same as the example provided. "victory" is a string that's passed into the function. 

I cannot find any other exception information and I don't know where else to look. I tried AES encryption too and had the same issue.

**Comment by leocavalcante** [comment]
Not sure if this issue is related to this package. Are you able to create a small snippet that reproduces the error?
Are you trying to store an `Encrypted` instance into Firestore?

At this part:
```dart
final encryptedString = encrypter.encrypt(victory, iv: iv);
print (encryptedString);
```
It is not a `String`, it is an `Encrypted` instance.
Try:
```dart
final encryptedString = encrypter.encrypt(victory, iv: iv);
print(encryptedString.base64);
print(encryptedString.base16);
```

**Comment by ScottishRoss** [comment]
Ah, that explains that. Thank you.

I do need some additional help if that's okay though:

When storing to Firebase, I would like to encrypt a string using the Users UID as a Key, and then pass the IV along with it for decryption when I need to. I can't seem to figure out a way of doing this, especially now I now I need to convert the encrypted string into a String somehow, and I just can't seem to figure this problem out.

**Comment by leocavalcante** [comment]
All the encryption process is based on binaries, when you need a string of it, you need a encoder for these binary data. Base64 and base16/hexdecimal are two most used encoders for it.
