### ISSUE TITLE
Use ECB mode to prompt errors，Other modes have incorrect encryption results

### ISSUE THREAD

**Issue by jlcool** [leocavalcante/encrypt#21]
mode: AESMode.ecb
type 'ParametersWithIV<KeyParameter>' is not a subtype of type 'KeyParameter' of 'params'

Other results are different from this website http://tool.chacuo.net/cryptaes . My background data is consistent with this website.

**Comment by jlcool** [comment]
The second problem may be that my IV settings are incorrect.

**Comment by leocavalcante** [comment]
Thanks for reporting. ECB fixed!

About the second problem: can you share the Dart snippet your are using and the settings you choose on the website, please?
