### ISSUE TITLE
RSA ERROR

### ISSUE THREAD

**Issue by EunyoungY** [leocavalcante/encrypt#217]
Hello, I'm running RSA Example, and I'm going through some errors.

Unhandled Exception: FileSystemException: Cannot open file, path = 'test/public.pem' (OS Error: No such file or directory, errno = 2)

I have downloaded private.pem, public.pem from repository, and put this on test folder. however, It says can not open test/public.pem.

[code]
import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:encrypt/encrypt.dart';
import 'package:encrypt/encrypt.dart' as encrypt;
import 'package:encrypt/encrypt_io.dart';
import 'package:pointycastle/asymmetric/api.dart';

void main() => runApp(MyApp());
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  void encryptToRSA() async{ 
    final publicKey = await parseKeyFromFile<RSAPublicKey>('test/public.pem'); 
    final privKey = await parseKeyFromFile<RSAPrivateKey>('test/private.pem');

    final plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
    final encrypter = Encrypter(RSA(publicKey: publicKey, privateKey: privKey));

    final encrypted = encrypter.encrypt(plainText);
    final decrypted = encrypter.decrypt(encrypted);

    print(decrypted);
    print(encrypted.bytes);
    print(encrypted.base16);
    print(encrypted.base64);  print(encrypted.base64);  
  }

[log]
Syncing files to device sdk gphone x86 arm...
I/flutter (19748): HELL
E/flutter (19748): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Cannot open file, path = 'test/public.pem' (OS Error: No such file or directory, errno = 2)
E/flutter (19748): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter (19748): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (19748): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (19748): <asynchronous suspension>
E/flutter (19748): #3      parseKeyFromFile (package:encrypt/encrypt_io.dart:8:15)
E/flutter (19748): <asynchronous suspension>
E/flutter (19748): #4      _MyAppState.encryptToRSA (package:tilko/main.dart:108:23)
E/flutter (19748): <asynchronous suspension>
E/flutter (19748): 

[flutter doctor -v]
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale ko-KR)
    • Flutter version 2.2.2 at /Users/eunyoung/developer/sdk/new/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eunyoung/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

**Comment by leocavalcante** [comment]
Flutter isn't finding the PEM files, I don't work with Flutter, I think you have to do extra steps to read files:
https://flutter.dev/docs/development/ui/assets-and-images

**Comment by developmentkws** [comment]
Solved Checkout : [Solution](https://github.com/leocavalcante/encrypt/issues/86#issuecomment-903473711)
