### ISSUE TITLE
RSA example, path issue

### ISSUE THREAD

**Issue by EunyoungY** [leocavalcante/encrypt#218]
Hello, I'm running through RSA example, and it doesn't work well.
It says [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Cannot open file, path = 'assets/public.pem' (OS Error: No such file or directory, errno = 2)

![image](https://user-images.githubusercontent.com/43934072/124403803-0fbdb300-dd73-11eb-86b5-48a4eacd741c.png)

[pubspec.yaml]
![image](https://user-images.githubusercontent.com/43934072/124403809-19471b00-dd73-11eb-9662-75da14f9e114.png)

[Code]
  void encryptToRSA() async{ 
    final publicKey = await parseKeyFromFile<RSAPublicKey>('assets/public.pem');
    // final publicKey = await rootBundle.loadString('assets/public.pem');

    final privKey = await parseKeyFromFile<RSAPrivateKey>('assets/private.pem');

    final plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
    final encrypter = Encrypter(RSA(publicKey: publicKey, privateKey: privKey));

    final encrypted = encrypter.encrypt(plainText);
    final decrypted = encrypter.decrypt(encrypted);

    print(decrypted);
    print(encrypted.bytes);
    print(encrypted.base16);
    print(encrypted.base64);  print(encrypted.base64);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data Example'),
        ),
        body: Center( 
          child: ElevatedButton(
            child: Text("GET"),
            onPressed: (){ 
              // getData();
              // getAES();
              encryptToRSA();
            },
          ),

        ),
      ),
    );
  }

[flutter run]
Performing hot restart...
Syncing files to device sdk gphone x86 arm...
Restarted application in 2,597ms. 
E/flutter ( 7584): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: Cannot open file, path = 'assets/public.pem' (OS Error: No such file or directory, errno = 2)
E/flutter ( 7584): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 7584): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 7584): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 7584): <asynchronous suspension>
E/flutter ( 7584): #3      parseKeyFromFile (package:encrypt/encrypt_io.dart:8:15)
E/flutter ( 7584): <asynchronous suspension>
E/flutter ( 7584): #4      _MyAppState.encryptToRSA (package:tilko/main.dart:98:23)
E/flutter ( 7584): <asynchronous suspension>
E/flutter ( 7584): 

[flutter doctor -v]
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale ko-KR)
    • Flutter version 2.2.2 at /Users/eunyoung/developer/sdk/new/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eunyoung/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

**Comment by amed901107** [comment]
I ran into the same error, did you solve it?

**Comment by amed901107** [comment]
@EunyoungY here you have a solution!!!
 var fileAssets=await loadAsset('assets/rsa_key/public.pem');
    final parser = RSAKeyParser();
    final RSAPublicKey publicKey = parser
        .parse(fileAssets) as RSAPublicKey;

**Comment by developmentkws** [comment]
Solved Checkout : [Solution](https://github.com/leocavalcante/encrypt/issues/86#issuecomment-903473711)
