### ISSUE TITLE
using RSA without pem file

### ISSUE THREAD

**Issue by EunyoungY** [leocavalcante/encrypt#219]
"If I only have a publickey string, how do I get the RSAPublicKey object？ #97"
 final publicKey = RSAKeyParser().parse("keyString");

I followed this, and it gave me an error
![image](https://user-images.githubusercontent.com/43934072/124404441-e2becf80-dd75-11eb-91ed-7ac4a503813c.png)

[Code]
  void encryptToRSA() async{ 
    final publicKey = RSAKeyParser().parse("I put down my string");
    final privKey = RSAKeyParser().parse("I put down my string");
    final plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';

    final encrypter = Encrypter(RSA(publicKey: publicKey, privateKey: privKey));
![image](https://user-images.githubusercontent.com/43934072/124404508-32050000-dd76-11eb-934c-333fe79b8a14.png)

    final encrypted = encrypter.encrypt(plainText);
    final decrypted = encrypter.decrypt(encrypted);

    print(decrypted);
    print(encrypted.bytes);
    print(encrypted.base16);
    print(encrypted.base64);  print(encrypted.base64); 
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data Example'),
        ),
        body: Center( 
          child: ElevatedButton(
            child: Text("GET"),
            onPressed: (){ 
              // getData();
              // getAES();
              encryptToRSA();
            },
          ),

        ),
      ),
    );
  }

  

[flutter doctor -v]
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale ko-KR)
    • Flutter version 2.2.2 at /Users/eunyoung/developer/sdk/new/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eunyoung/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

**Comment by ibrahim-mubarak** [comment]
So your keys are perfectly fine, but they have to be modified slightly based on the type of key it is.

For example
```dart
var publicKey =  "-----BEGIN PUBLIC KEY-----\n$rawKey\n-----END PUBLIC KEY-----";
```

This should allow your key to be parsed properly

**Comment by EunyoungY** [comment]
I really appreciate your help!!

It works well. However, I faced another problem.
When I run the example, It gives an error like this.
T**oo large for maximum RSA cipher input block size (128): 256**
 



E/flutter (28790): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument (len): Too large for maximum RSA cipher input block size (128): 256
E/flutter (28790): #0      RSAEngine._convertInput (package:pointycastle/asymmetric/rsa.dart:101:7)
E/flutter (28790): #1      RSAEngine.processBlock (package:pointycastle/asymmetric/rsa.dart:87:17)
E/flutter (28790): #2      PKCS1Encoding._decodeBlock (package:pointycastle/asymmetric/pkcs1.dart:134:23)
E/flutter (28790): #3      PKCS1Encoding.processBlock (package:pointycastle/asymmetric/pkcs1.dart:96:14)
E/flutter (28790): #4      BaseAsymmetricBlockCipher.process (package:pointycastle/src/impl/base_asymmetric_block_cipher.dart:14:15)
E/flutter (28790): #5      RSA.decrypt (package:encrypt/src/algorithms/rsa.dart:53:20)
E/flutter (28790): #6      Encrypter.decryptBytes (package:encrypt/src/encrypter.dart:25:17)
E/flutter (28790): #7      Encrypter.decrypt (package:encrypt/src/encrypter.dart:31:17)
E/flutter (28790): #8      _MyAppState.encryptToRSA (package:tilko/main.dart:142:33)
E/flutter (28790): <asynchronous suspension>
E/flutter (28790):

**Comment by leocavalcante** [comment]
https://github.com/leocavalcante/encrypt/issues/168#issuecomment-692778748
