### ISSUE TITLE
"Key" keyword contradicts with flutter's inbuilt "key"

### ISSUE THREAD

**Issue by Anvesh2013** [leocavalcante/encrypt#22]

**Comment by Basher7** [comment]
same error in my project

lib/pages/password_keepers.dart:58:52: Error: The argument type 'String' can't be assigned to the parameter type 'Key'.
 - 'Key' is from 'package:encrypt/encrypt.dart' ('file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/encrypt-2.0.0/lib/encrypt.dart').

**Comment by leocavalcante** [comment]
`Key` on `encrypt` is just a alias for `Encrypted`.
You can seamlessly replace:
```dart
final key = Key.fromUtf8('mysupersecretkey!!!');
```
By:
```dart
final key = Encrypted.fromUtf8('mysupersecretkey!!!');
```

You can also use an import alias:
```dart
import 'package:encrypt/encrypt.dart' as encrypt;
final key = encrypt.Key.fromUtf8('mysupersecretkey!!!');
```
Or even `hide` the `Key` from the `material` import:
```dart
import 'package:flutter/material.dart' hide Key;
```

**Comment by leocavalcante** [comment]
Hey folks, I'd like to also point out that if you are importing material and encrypt on the same .dart file is a bad smell, it is a high indicative that there is some business logic and UI being mixed.
