### ISSUE TITLE
Bump PointyCastle version to support web builds

### ISSUE THREAD

**Issue by datteroandrea** [leocavalcante/encrypt#220]
When importing the encrypt package this is the error that is given:

```
    flutter pub add encrypt Launching lib\main.dart on Chrome in debug mode...
    flutter/.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/key_derivators/argon2.dart:42:27:
Error: The integer literal 0xFFFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
    Try changing the literal to something that can be represented in Javascript.
    In Javascript 0x10000000000000000 is the nearest value that can be represented exactly. static const int M32L = 0xFFFFFFFFFFFFFFFF; 
    
    flutter/.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/src/utils.dart:313:9:
Error: The integer literal 0xFFFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
    Try changing the literal to something that can be represented in Javascript.
    In Javascript 0x10000000000000000 is the nearest value that can be represented exactly. ((0xFFFFFFFFFFFFFFFF) ^ ((1 << (64 - count)) - 1));
    
    flutter/.pub-cache/hosted/pub.dartlang.org/pointycastle-3.1.3/lib/src/platform_check/platform_check.dart:6:35: Error: Method not found: 'getPlatform'. static Platform get instance => getPlatform(); Failed to compile application.
```

Works completely fine in Android and iOS seems.

**Comment by leocavalcante** [comment]
I guess that  `pointycastle` doesn't works on the web.

**Comment by datteroandrea** [comment]
So I can't use it for web development?

**Comment by leocavalcante** [comment]
Yup, at least until https://github.com/bcgit/pc-dart/issues/112

**Comment by ConstantCNel** [comment]
@leocavalcante Hi! Firstly, thank you so much for this package! It's really nice. 

It seems that above issue has been fixed: https://github.com/bcgit/pc-dart/issues/112 

Any idea when you can implement this in your package? 

Looking forward to it!

**Comment by leocavalcante** [comment]
It is still a release candidate, but I can maybe create a RC for encrypt too.

**Comment by ConstantCNel** [comment]
Ah that would be really great! 
I'd love to use this package in web as well.

**Comment by mast3rmindx** [comment]
> It is still a release candidate, but I can maybe create a RC for encrypt too.

Any update on this? It's no longer a RC.

**Comment by leocavalcante** [comment]
Sorry, didn't get time to see this yet.
Isn't anyone willing to do a PR?

**Comment by leocavalcante** [comment]
New version is on pub https://pub.dev/packages/encrypt/versions/5.0.1
Thanks @mast3rmindx
