### ISSUE TITLE
AES CBC Invalid or corrupted pad block 

### ISSUE THREAD

**Issue by ZacharieAzoulai** [leocavalcante/encrypt#224]
Hi,

I'm facing this issue and I don't know why,

When I try to decrypt with AES CBC 256 and PCKS7 padding, it works but on flutter it throw "Invalid or corrupted pad block"

Here is my piece of code:
```
import 'package:encrypt/encrypt.dart' as encr;

//some stuff

String key = "QK8s9l351p3RrK5-7TTmq9LL66z__kcoAE12dqv5an0=";
String encrypted = "VoHF769Z07ktjacqSLoImblwbE5xuhpnQdLbHHajQC4=";
String iv = "-ulVzHpwuz2_SIlDnjYDhw==";
final encrypter = encr.Encrypter(encr.AES(encr.Key.fromBase64(key), mode: encr.AESMode.cbc));
String result = encrypter.decrypt(encr.Encrypted.fromBase64(encrypted), iv:encr.IV.fromBase64(iv));
print('result = $result');
```

The result to find is "Gaspacho Andalou"

For testing I use this website: https://the-x.cn/en-us/cryptography/Aes.aspx and it works on it 
<img width="1352" alt="Screenshot 2021-07-24 at 00 57 37" src="https://user-images.githubusercontent.com/47105495/126849068-84226e74-f778-4069-8bf7-17060cab5de5.png">

In my project encryption/decryption with this package works really fine but when decrypting this particular key, iv and encrypted message it doesn't work and I really don't know why...

Can you help me ?

Thanks

**Comment by CuriousDev21** [comment]
@ZacharieAzoulai  I would love to know how you solved this issue....
