### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Input data length must be a multiple of cipher's block size

### ISSUE THREAD

**Issue by josh4500** [leocavalcante/encrypt#238]
Unable to decrypt files from Uint8List. I parse the encrypted file ( from Uint8List) to Encrypted(file), the try do decrypt file. But it throws error.

**Comment by leocavalcante** [comment]
Your input must be padded to fit a multiple of the block size.

**Comment by josh4500** [comment]
Yes, I tried looking for resources that link up to the function or class I might use for it in dart but got stuck already.
