### ISSUE TITLE
Invalid argument(s): Input data length must be a multiple of cipher's block size

### ISSUE THREAD

**Issue by abc873693** [leocavalcante/encrypt#24]
My app use aes decrypt64 occur crash.

This is my source code.

> final encrypter =
          Encrypter(AES(Constants.key, Constants.iv, mode: AESMode.cbc));
      var encryptPassword = prefs.getString(Constants.PREF_PASSWORD) ?? "";
      if (encryptPassword != "")
        password = encrypter.decrypt64(encryptPassword);

and crash log

> Non-fatal Exception: package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart 55 in PaddedBlockCipherImpl.process
0   ???                            0x0 PaddedBlockCipherImpl.process (padded_block_cipher_impl.dart:55)
1   ???                            0x0 AES.decrypt (aes.dart:36)
2   ???                            0x0 Encrypter.decrypt (encrypter.dart:16)
3   ???                            0x0 Encrypter.decrypt64 (encrypter.dart:26)
4   ???                            0x0 LoginPageState._getPreference (login_page.dart:292)
5   ???                            0x0 LoginPageState.initState (login_page.dart:41)
6   ???                            0x0 StatefulElement._firstBuild (framework.dart:3846)
7   ???                            0x0 ComponentElement.mount (framework.dart:3711)
8   ???                            0x0 Element.inflateWidget (framework.dart:2956)
9   ???                            0x0 Element.updateChild (framework.dart:2759)
10  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
11  ???                            0x0 Element.inflateWidget (framework.dart:2956)
12  ???                            0x0 Element.updateChild (framework.dart:2759)
13  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
14  ???                            0x0 Element.rebuild (framework.dart:3559)
15  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
16  ???                            0x0 ComponentElement.mount (framework.dart:3711)
17  ???                            0x0 Element.inflateWidget (framework.dart:2956)
18  ???                            0x0 Element.updateChild (framework.dart:2759)
19  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
20  ???                            0x0 Element.inflateWidget (framework.dart:2956)
21  ???                            0x0 Element.updateChild (framework.dart:2759)
22  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
23  ???                            0x0 Element.inflateWidget (framework.dart:2956)
24  ???                            0x0 MultiChildRenderObjectElement.mount (framework.dart:4982)
25  ???                            0x0 Element.inflateWidget (framework.dart:2956)
26  ???                            0x0 Element.updateChild (framework.dart:2759)
27  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
28  ???                            0x0 Element.rebuild (framework.dart:3559)
29  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
30  ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
31  ???                            0x0 ComponentElement.mount (framework.dart:3711)
32  ???                            0x0 Element.inflateWidget (framework.dart:2956)
33  ???                            0x0 Element.updateChild (framework.dart:2759)
34  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
35  ???                            0x0 Element.inflateWidget (framework.dart:2956)
36  ???                            0x0 Element.updateChild (framework.dart:2759)
37  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
38  ???                            0x0 Element.rebuild (framework.dart:3559)
39  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
40  ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
41  ???                            0x0 ComponentElement.mount (framework.dart:3711)
42  ???                            0x0 Element.inflateWidget (framework.dart:2956)
43  ???                            0x0 Element.updateChild (framework.dart:2759)
44  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
45  ???                            0x0 Element.inflateWidget (framework.dart:2956)
46  ???                            0x0 Element.updateChild (framework.dart:2759)
47  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
48  ???                            0x0 Element.rebuild (framework.dart:3559)
49  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
50  ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
51  ???                            0x0 ComponentElement.mount (framework.dart:3711)
52  ???                            0x0 Element.inflateWidget (framework.dart:2956)
53  ???                            0x0 Element.updateChild (framework.dart:2759)
54  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
55  ???                            0x0 Element.inflateWidget (framework.dart:2956)
56  ???                            0x0 Element.updateChild (framework.dart:2759)
57  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
58  ???                            0x0 Element.rebuild (framework.dart:3559)
59  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
60  ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
61  ???                            0x0 ComponentElement.mount (framework.dart:3711)
62  ???                            0x0 Element.inflateWidget (framework.dart:2956)
63  ???                            0x0 Element.updateChild (framework.dart:2759)
64  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
65  ???                            0x0 Element.rebuild (framework.dart:3559)
66  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
67  ???                            0x0 ComponentElement.mount (framework.dart:3711)
68  ???                            0x0 Element.inflateWidget (framework.dart:2956)
69  ???                            0x0 Element.updateChild (framework.dart:2759)
70  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
71  ???                            0x0 Element.rebuild (framework.dart:3559)
72  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
73  ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
74  ???                            0x0 ComponentElement.mount (framework.dart:3711)
75  ???                            0x0 Element.inflateWidget (framework.dart:2956)
76  ???                            0x0 Element.updateChild (framework.dart:2759)
77  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
78  ???                            0x0 Element.inflateWidget (framework.dart:2956)
79  ???                            0x0 Element.updateChild (framework.dart:2759)
80  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
81  ???                            0x0 Element.rebuild (framework.dart:3559)
82  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
83  ???                            0x0 ComponentElement.mount (framework.dart:3711)
84  ???                            0x0 Element.inflateWidget (framework.dart:2956)
85  ???                            0x0 Element.updateChild (framework.dart:2759)
86  ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
87  ???                            0x0 Element.inflateWidget (framework.dart:2956)
88  ???                            0x0 Element.updateChild (framework.dart:2759)
89  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
90  ???                            0x0 Element.rebuild (framework.dart:3559)
91  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
92  ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
93  ???                            0x0 ComponentElement.mount (framework.dart:3711)
94  ???                            0x0 Element.inflateWidget (framework.dart:2956)
95  ???                            0x0 Element.updateChild (framework.dart:2759)
96  ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
97  ???                            0x0 Element.rebuild (framework.dart:3559)
98  ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
99  ???                            0x0 ComponentElement.mount (framework.dart:3711)
100 ???                            0x0 Element.inflateWidget (framework.dart:2956)
101 ???                            0x0 Element.updateChild (framework.dart:2759)
102 ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
103 ???                            0x0 Element.inflateWidget (framework.dart:2956)
104 ???                            0x0 Element.updateChild (framework.dart:2759)
105 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
106 ???                            0x0 Element.rebuild (framework.dart:3559)
107 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
108 ???                            0x0 ComponentElement.mount (framework.dart:3711)
109 ???                            0x0 Element.inflateWidget (framework.dart:2956)
110 ???                            0x0 Element.updateChild (framework.dart:2759)
111 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
112 ???                            0x0 Element.rebuild (framework.dart:3559)
113 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
114 ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
115 ???                            0x0 ComponentElement.mount (framework.dart:3711)
116 ???                            0x0 Element.inflateWidget (framework.dart:2956)
117 ???                            0x0 Element.updateChild (framework.dart:2759)
118 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
119 ???                            0x0 Element.rebuild (framework.dart:3559)
120 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
121 ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
122 ???                            0x0 ComponentElement.mount (framework.dart:3711)
123 ???                            0x0 Element.inflateWidget (framework.dart:2956)
124 ???                            0x0 MultiChildRenderObjectElement.mount (framework.dart:4982)
125 ???                            0x0 Element.inflateWidget (framework.dart:2956)
126 ???                            0x0 Element.updateChild (framework.dart:2759)
127 ???                            0x0 _TheatreElement.mount (overlay.dart:494)
128 ???                            0x0 Element.inflateWidget (framework.dart:2956)
129 ???                            0x0 Element.updateChild (framework.dart:2759)
130 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
131 ???                            0x0 Element.rebuild (framework.dart:3559)
132 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
133 ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
134 ???                            0x0 ComponentElement.mount (framework.dart:3711)
135 ???                            0x0 Element.inflateWidget (framework.dart:2956)
136 ???                            0x0 Element.updateChild (framework.dart:2759)
137 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
138 ???                            0x0 Element.rebuild (framework.dart:3559)
139 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
140 ???                            0x0 ComponentElement.mount (framework.dart:3711)
141 ???                            0x0 Element.inflateWidget (framework.dart:2956)
142 ???                            0x0 Element.updateChild (framework.dart:2759)
143 ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
144 ???                            0x0 Element.inflateWidget (framework.dart:2956)
145 ???                            0x0 Element.updateChild (framework.dart:2759)
146 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
147 ???                            0x0 Element.rebuild (framework.dart:3559)
148 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
149 ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
150 ???                            0x0 ComponentElement.mount (framework.dart:3711)
151 ???                            0x0 Element.inflateWidget (framework.dart:2956)
152 ???                            0x0 Element.updateChild (framework.dart:2759)
153 ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
154 ???                            0x0 Element.inflateWidget (framework.dart:2956)
155 ???                            0x0 Element.updateChild (framework.dart:2759)
156 ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
157 ???                            0x0 Element.inflateWidget (framework.dart:2956)
158 ???                            0x0 Element.updateChild (framework.dart:2759)
159 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
160 ???                            0x0 Element.rebuild (framework.dart:3559)
161 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
162 ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
163 ???                            0x0 ComponentElement.mount (framework.dart:3711)
164 ???                            0x0 Element.inflateWidget (framework.dart:2956)
165 ???                            0x0 Element.updateChild (framework.dart:2759)
166 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
167 ???                            0x0 Element.rebuild (framework.dart:3559)
168 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
169 ???                            0x0 ComponentElement.mount (framework.dart:3711)
170 ???                            0x0 Element.inflateWidget (framework.dart:2956)
171 ???                            0x0 Element.updateChild (framework.dart:2759)
172 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
173 ???                            0x0 Element.rebuild (framework.dart:3559)
174 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
175 ???                            0x0 ComponentElement.mount (framework.dart:3711)
176 ???                            0x0 Element.inflateWidget (framework.dart:2956)
177 ???                            0x0 Element.updateChild (framework.dart:2759)
178 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
179 ???                            0x0 Element.rebuild (framework.dart:3559)
180 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
181 ???                            0x0 ComponentElement.mount (framework.dart:3711)
182 ???                            0x0 Element.inflateWidget (framework.dart:2956)
183 ???                            0x0 Element.updateChild (framework.dart:2759)
184 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
185 ???                            0x0 Element.rebuild (framework.dart:3559)
186 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
187 ???                            0x0 ComponentElement.mount (framework.dart:3711)
188 ???                            0x0 Element.inflateWidget (framework.dart:2956)
189 ???                            0x0 Element.updateChild (framework.dart:2759)
190 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
191 ???                            0x0 Element.rebuild (framework.dart:3559)
192 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
193 ???                            0x0 StatefulElement._firstBuild (framework.dart:3864)
194 ???                            0x0 ComponentElement.mount (framework.dart:3711)
195 ???                            0x0 Element.inflateWidget (framework.dart:2956)
196 ???                            0x0 Element.updateChild (framework.dart:2759)
197 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
198 ???                            0x0 Element.rebuild (framework.dart:3559)
199 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
200 ???                            0x0 ComponentElement.mount (framework.dart:3711)
201 ???                            0x0 Element.inflateWidget (framework.dart:2956)
202 ???                            0x0 Element.updateChild (framework.dart:2759)
203 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
204 ???                            0x0 Element.rebuild (framework.dart:3559)
205 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
206 ???                            0x0 ComponentElement.mount (framework.dart:3711)
207 ???                            0x0 Element.inflateWidget (framework.dart:2956)
208 ???                            0x0 Element.updateChild (framework.dart:2759)
209 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
210 ???                            0x0 Element.rebuild (framework.dart:3559)
211 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
212 ???                            0x0 ComponentElement.mount (framework.dart:3711)
213 ???                            0x0 Element.inflateWidget (framework.dart:2956)
214 ???                            0x0 Element.updateChild (framework.dart:2759)
215 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
216 ???                            0x0 Element.rebuild (framework.dart:3559)
217 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
218 ???                            0x0 ComponentElement.mount (framework.dart:3711)
219 ???                            0x0 Element.inflateWidget (framework.dart:2956)
220 ???                            0x0 Element.updateChild (framework.dart:2759)
221 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
222 ???                            0x0 Element.rebuild (framework.dart:3559)
223 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
224 ???                            0x0 ComponentElement.mount (framework.dart:3711)
225 ???                            0x0 Element.inflateWidget (framework.dart:2956)
226 ???                            0x0 Element.updateChild (framework.dart:2759)
227 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
228 ???                            0x0 Element.rebuild (framework.dart:3559)
229 ???                            0x0 ComponentElement._firstBuild (framework.dart:3716)
230 ???                            0x0 ComponentElement.mount (framework.dart:3711)
231 ???                            0x0 Element.inflateWidget (framework.dart:2956)
232 ???                            0x0 Element.updateChild (framework.dart:2759)
233 ???                            0x0 SingleChildRenderObjectElement.mount (framework.dart:4876)
234 ???                            0x0 Element.inflateWidget (framework.dart:2956)
235 ???                            0x0 Element.updateChild (framework.dart:2759)
236 ???                            0x0 ComponentElement.performRebuild (framework.dart:3747)
237 ???                            0x0 Element.rebuild (framework.dart:3559)
238 ???                            0x0 BuildOwner.buildScope (framework.dart:2273)
239 ???                            0x0 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (binding.dart:700)
240 ???                            0x0 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (binding.dart:268)
241 ???                            0x0 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (binding.dart:988)
242 ???                            0x0 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (binding.dart:928)
243 ???                            0x0 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<fn> (binding.dart:749)
244 ???                            0x0 ._rootRun (zone.dart:1120)
245 ???                            0x0 _CustomZone.run (zone.dart:1021)
246 ???                            0x0 _CustomZone.runGuarded (zone.dart:923)
247 ???                            0x0 _CustomZone.bindCallbackGuarded.<fn> (zone.dart:963)
248 ???                            0x0 ._rootRun (zone.dart:1124)
249 ???                            0x0 _CustomZone.run (zone.dart:1021)
250 ???                            0x0 _CustomZone.bindCallback.<fn> (zone.dart:947)
251 ???                            0x0 Timer._createTimer.<fn> (libtimer_patch.dart:21)
252 ???                            0x0 _Timer._runTimers (libtimer_impl.dart:382)
253 ???                            0x0 _Timer._handleMessage (libtimer_impl.dart:416)
254 ???                            0x0 _RawReceivePortImpl._handleMessage (libisolate_patch.dart:171)

I don't know what happend

**Comment by leocavalcante** [comment]
Can you reproduce this error in a Dart snippet with a different key and IV then share here?
How is encryptPassword value being generated?

**Comment by leocavalcante** [comment]
Closed due inactivity.
