### ISSUE TITLE
AES-GCM 

### ISSUE THREAD

**Issue by Ezhiltechii** [leocavalcante/encrypt#283]
Hello,

I have a problem with the package.(https://pub.dev/packages/encrypt)

I get the following errors:

In this line:
final encrypter = Encrypter(AES(key, mode: AESMode.gcm));
this error:

There's no constant named 'gcm' in 'AESMode'

and in

final decrypted = encrypter.decrypt(
      encrypted,
      iv: iv,
      associatedData: macValue,
    );
The named parameter 'associatedData' isn't defined.

Could you help me understand what I made wrong?

Thank you very much for your support!

**Comment by nerdy-plutonian-ng** [comment]
So apparently, the owner of this package did not publish the latest update to pub, so you can depend on the git instead. You add the below to your dependencies in pubspec.yaml 

`  encrypt:
    git:
      url: https://github.com/leocavalcante/encrypt.git`

**Comment by leocavalcante** [comment]
Latest version added: https://pub.dev/packages/encrypt/versions/5.0.3
