### ISSUE TITLE
[QUESTION] How is encryption implemented on iOS (for export compliance)?

### ISSUE THREAD

**Issue by under3415** [leocavalcante/encrypt#287]
Hi
I am using your package to decrypt some files in my mobile app to protect the ip. 
I have to answer questions in the Apple store about encryption for US and French [export compliance](https://help.apple.com/app-store-connect/#/dev88f5c7bf9) (not sure why is Google not asking for this!?). 

Anyway, the options are (the way I understood them):
1. Proprietary encryption (the worst option)
2. Industry standard encryption (e.g., IEEE, IETF, ISO, ITU, ETSI, 3GPP, TIA, and GSMA)
4. Crypto functionality within Apple’s operating system (this I think is exempt)

When I use your encryption package on iOS, is this using Apple OS crypto functionality? 
How should I answer this question?

This is the methods I call:
```
final encrypter = Encrypter(AES(key, mode: AESMode.cbc, padding: 'PKCS7'));
final Encrypted encrypted = Encrypted(await targetFile.readAsBytes());
return encrypter.decrypt(encrypted, iv: iv);
```

**Comment by abhlabs** [comment]
I'm facing this same issue.  I _think_ the encryption algorithms used by the encrypt package would be considered "industry standard" algorithms, and it would be helpful to get confirmation of that from the package developers or others with relevant expertise.  If that's true, then item #2 on the Apple list would apply, and you'd need to either produce the French encryption declaration, or restrict your app from French distribution.

**Comment by leocavalcante** [comment]
Sorry, folks. This library was never intended for Flutter, despite its in Dart. I have no idea how security/cryptography complies on mobile platforms.

But I'd say it is the option 2. They are implementations of industry-standards.

**Comment by abhlabs** [comment]
> ... They are implementations of industry-standards.

That's perfect, thanks very much!
