### ISSUE TITLE
The method .fromLength hasn't been updated to be cryptographically-secure in the pub package

### ISSUE THREAD

**Issue by as3ng** [leocavalcante/encrypt#295]
Hi!
First of all, this pub package really helps me to use it in a Flutter project especially when dealing for security perspectives. I recently used the latest version of the package (5.0.1 if I'm not mistaken) yet the `.fromLength` method isn't updated yet to be secured, resulting a trailing zeroes again just like in the prior version.

Seems a bug to me, but here I used the Zapp sandbox for building the Flutter project. I updated the pubspec.yaml for using the mentioned version and run a test for printing out the bytearray of the resulting variable which derives a `.fromLength` method.

![image](https://user-images.githubusercontent.com/49669266/225277460-737faba4-53c6-4466-8ecd-6df2d3652ebc.png)
![image](https://user-images.githubusercontent.com/49669266/225282533-f03cc2f9-21ef-4a59-82d4-6bc24dc1e45c.png)
![image](https://user-images.githubusercontent.com/49669266/225277636-9c07aaae-b52a-4ada-99fb-e7c452b019ea.png)

I thought this would may annoy some dev/stakeholders for using the method but it turns out to be still insecure. It'd not take a couple of minutes to break a confidential data when they use it, and it doesn't come up with bruteforcing as well.

Is this because of the pub package server hasn't updated it yet or is it still not implemented correctly? Because as far as I know, it already did and there's a new one.

![image](https://user-images.githubusercontent.com/49669266/225278707-a0052fee-e65f-4518-84f1-ea2a87df12bf.png)

Thanks! ;)

**Comment by leocavalcante** [comment]
Published, please visit: https://github.com/leocavalcante/encrypt/issues/314
