### ISSUE TITLE
Key Length issue

### ISSUE THREAD

**Issue by NTMS2017** [leocavalcante/encrypt#3]
First I use my key (Len:50) and I get below error. Error state that key must be 128/192 or 256bits.
I am confuse here. You have 32 character and its works. 

https://stackoverflow.com/questions/4850241/how-many-bits-in-a-character has a explain that it depends what is the character and what encoding it is in. So do you going to support ISO-8895-1 tp ISO-8895-9 as well as, UTF-8, UTF-16, UTF-32 encoding type?

I will stick to 32 length now. My local language is TR and ISO-8895-5 (Latin-5 (Turkish)). It will be good to cover all other language. Thanks

Unhandled exception:
Invalid argument(s): Key length must be 128/192/256 bits
#0      AESFastEngine.init (package:pointycastle/block/aes_fast.dart:66:7)
#1      AES.encrypt (package:encrypt/src/aes.dart:20:9)
#2      Encrypter.encrypt (package:encrypt/encrypt.dart:17:17)
#3      main (file:///Users/niyazitoros/IdeaProjects/github/untitled/bin/main.dart:11:35)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by leocavalcante** [comment]
Hi @NTMS2017 
This is a constraint of the algorithm: https://en.wikipedia.org/wiki/Advanced_Encryption_Standard
Keys must be 128, 192 or 256 bits, exactly this sizes, it's **not** a range.

As you researched, 1 utf-8 char is 4 bytes, so a 32 char length key is equals to 32 * 4 = **128 bits**.

So keys should have:

| UTF-8 length | Bits |
| --- | --- |
| 32 | 128 |
| 48 | 192 |
| 64 | 256 |

*This can vary on the characters you are using*

**I highly recommend** you to use a 256 bits key generated by a [CSPRNG](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator). PointyCastle [has one](https://en.wikipedia.org/wiki/Fortuna_(PRNG)), it is used for the Salts in [password](https://github.com/leocavalcante/password-dart).

I will stick your issue to remember to add something like that in this project so you can generate cryptographic secure keys right from the terminal.

*Note:* You already able to do that thought [`/dev/urandom`](https://en.wikipedia.org/wiki//dev/random) or [`RtlGenRandom`](https://en.wikipedia.org/wiki/CryptGenRandom).

**Comment by NTMS2017** [comment]
Thanks Leo, check all this tomorrow.
