### ISSUE TITLE
Invalid or corrupted pad block

### ISSUE THREAD

**Issue by chinabrant** [leocavalcante/encrypt#30]
How can i get the data:
```
static Future post(String url, List<int> data) async {
    Response rsp = await dio.post(url, data: data, options: Options(responseType: ResponseType.bytes));
    return rsp.data;
  }
```
How to use this lib:
```
static List<int> aes128Decode(List<int> data) {
    final key = Key.fromUtf8('xxxxxxxxxxxxxxxx');
    final iv = IV.fromLength(16);
    final encrypter = Encrypter(AES(key, iv, mode: AESMode.ecb));

    print(data);
    final encrypted = Encrypted(Uint8List.fromList(data)); 

    return encrypter.decrypt(encrypted).runes.toList();
  }
```

The data like this: (console print)
[90, 94, 169, 122, 182, 145, 29, 101, 77, 245, 27, 223, 120, 103, 10, 194, 46, 197, 31, 0, 105, 197, 5, 94, 153, 24, 105, 142, 147, 46, 51, 224, 86, 113, 199, 20, 84, 61, 171, 72, 132, 189, 253, 90, 228, 134, 201, 232, 244, 150, 190, 63, 226, 81, 12, 75, 140, 55, 73, 162, 142, 171, 248, 36, 199, 241, 183, 236, 109, 145, 37, 172, 63, 219, 53, 197, 255, 165, 204, 167, 110, 4, 55, 187, 189, 202, 219, 100, 66, 48, 91, 231, 248, 46, 121, 66, 85, 21, 188, 33, 168, 254, 129, 253, 42, 129, 230, 85, 19, 14, 11, 118, 225, 30, 169, 178, 86, 251, 139, 177, 63, 85, 92, 195, 223, 45, 70, 148, 245, 88, 228, 247, 62, 46, 187, 161, 171, 102, 192, 101, 76, 116, 23, 91, 58, 238, 119, 108, 15, 135, 49, 8, 203, 126, 188, 181, 27, 184, 77, 119, 62, 167, 89, 176, 73, 226, 227, 195, 8, 220, 164, 73, 50, 253, 9, 120, 56, 143, 50, 2, 169, 198, 113, 136, 232, 64, 83, 87, 19, 164, 235, 179, 196, 163, 40, 98, 186, 179, 10, 94, ......

I got this error:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): Invalid or corrupted pad block
#0      PKCS7Padding.padCount 
package:pointycastle/paddings/pkcs7.dart:40
#1      PaddedBlockCipherImpl.doFinal 
package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:106
#2      PaddedBlockCipherImpl.process 
package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:69
#3      AES.decrypt 
../…/algorithms/aes.dart:36
#4      Encrypter.decrypt 
../…/src/encrypter.dart:16
#5      DataCodec.aes128Decode 
/…/api/data_codec.dart:29
#6      Request.start.<anonymous closure> 
/…/api/request.dart:111
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValu<…>
```

Can you help me? i am not good at encrypt.
I just know the data is encoded by aes128.

Does the data need some additional processed?

**Comment by leocavalcante** [comment]
You need the proper key and iv values to decode...

**Comment by chinabrant** [comment]
```
static List<int> aes128Encode(String params) {
    final key = Key.fromUtf8('15helloTCJTALK20'); 
    final iv = IV.fromLength(16);
    final encrypter = Encrypter(AES(key, iv, mode: AESMode.ecb));

    final encrypted = encrypter.encrypt(params);
    final result = encrypter.decrypt(encrypted);
    print('params: $params');
    print('result: $result');

    return encrypted.bytes;
  }

  static List<int> aes128Decode(List<int> data) {
    final key = Key.fromUtf8('15helloTCJTALK20');
    final iv = IV.fromLength(16);
    final encrypter = Encrypter(AES(key, iv, mode: AESMode.ecb));

    final encrypted = Encrypted(Uint8List.fromList(data)); 

    return encrypter.decrypt(encrypted).runes.toList();
  }
```

Use aes128Encode function, i can get the right answer.

```
AES(this.key, this.iv, {this.mode = AESMode.sic})
      : _cipher = PaddedBlockCipher('AES/${_modes[mode]}/PKCS7'),
        _params = PaddedBlockCipherParameters(
          mode == AESMode.ecb
              ? KeyParameter(key.bytes)
              : ParametersWithIV<KeyParameter>(
                  KeyParameter(key.bytes), iv.bytes),
          null,
        );
```
Look at aes class define, when the model is AESMode.ecb, the iv parameter is no use.

**Comment by leocavalcante** [comment]
Your code looks fine here:
```dart
import 'package:encrypt/encrypt.dart';
import 'dart:typed_data';

class Encoder {
  static List<int> aes128Encode(String params) {
    final key = Key.fromUtf8('15helloTCJTALK20');
    final iv = IV.fromLength(16);
    final encrypter = Encrypter(AES(key, iv, mode: AESMode.ecb));

    final encrypted = encrypter.encrypt(params);
    final result = encrypter.decrypt(encrypted);
    print('params: $params');
    print('result: $result');

    return encrypted.bytes;
  }

  static List<int> aes128Decode(List<int> data) {
    final key = Key.fromUtf8('15helloTCJTALK20');
    final iv = IV.fromLength(16);
    final encrypter = Encrypter(AES(key, iv, mode: AESMode.ecb));

    final encrypted = Encrypted(Uint8List.fromList(data));

    return encrypter.decrypt(encrypted).runes.toList();
  }
}

void main() {
  final text = 'Lorem Ipsum';
  final encoded = Encoder.aes128Encode(text);

  print(encoded);

  final decoded = Encoder.aes128Decode(encoded);

  print(decoded);
}
```

```pwsh
encrypt_issu30~ dart .\bin\main.dart
params: Lorem Ipsum
result: Lorem Ipsum
[193, 56, 172, 130, 112, 33, 0, 154, 30, 140, 46, 16, 54, 73, 41, 239]
[76, 111, 114, 101, 109, 32, 73, 112, 115, 117, 109]
```

I'm missing something?

**Comment by chinabrant** [comment]
I know why, the server data don't need the pkcs7padding to decrypt. So what should i do. 
```
PaddedBlockCipher('AES/${_modes[mode]}/PKCS7'),
```

**Comment by chinabrant** [comment]
This is the encrypt function at client.
```
- (NSData *)AES128EncryptWithKey:(NSString *)key {
	// 'key' should be 128 bytes for AES128, will be null-padded otherwise
	char keyPtr[kCCKeySizeAES128+1]; // room for terminator (unused)
	bzero(keyPtr, sizeof(keyPtr)); // fill with zeroes (for padding)
	
	// fetch key data
	[key getCString:keyPtr maxLength:sizeof(keyPtr) encoding:NSUTF8StringEncoding];
	
	NSUInteger dataLength = [self length];
	
	//See the doc: For block ciphers, the output size will always be less than or 
	//equal to the input size plus the size of one block.
	//That's why we need to add the size of one block here
	size_t bufferSize = dataLength + kCCBlockSizeAES128;
	void *buffer = malloc(bufferSize);
	
	size_t numBytesEncrypted = 0;
	CCCryptorStatus cryptStatus = CCCrypt(kCCEncrypt, kCCAlgorithmAES128, kCCOptionPKCS7Padding + kCCOptionECBMode,
										  keyPtr, kCCKeySizeAES128,
										  NULL /* initialization vector (optional) */,
										  [self bytes], dataLength, /* input */
										  buffer, bufferSize, /* output */
										  &numBytesEncrypted);
    
	if (cryptStatus == kCCSuccess) {
		//the returned NSData takes ownership of the buffer and will free it on deallocation
		return [NSData dataWithBytesNoCopy:buffer length:numBytesEncrypted];
	}
	
	free(buffer); //free the buffer;
	return nil;
}
```

This is the decrypt function.
```
- (NSData *)AES128DecryptHttpWithKey: (NSString *)key {
    // 'key' should be 16 bytes for AES128, will be null-padded otherwise
    char keyPtr[kCCKeySizeAES128+1]; // room for terminator (unused)
    bzero(keyPtr, sizeof(keyPtr)); // fill with zeroes (for padding)
    
    // fetch key data
    [key getCString:keyPtr maxLength:sizeof(keyPtr) encoding:NSUTF8StringEncoding];
    
    NSUInteger dataLength = [self length];
    
    //See the doc: For block ciphers, the output size will always be less than or
    //equal to the input size plus the size of one block.
    //That's why we need to add the size of one block here
    size_t bufferSize = dataLength + kCCBlockSizeAES128;
    void *buffer = malloc(bufferSize);
    
    size_t numBytesDecrypted = 0;
    
    CCCryptorStatus cryptStatus = CCCrypt(kCCDecrypt, kCCAlgorithmAES128, kCCOptionECBMode,
                                          keyPtr, kCCKeySizeAES128,
                                          NULL /* initialization vector (optional) */,
                                          [self bytes], dataLength, /* input */
                                          buffer, bufferSize, /* output */
                                          &numBytesDecrypted);
    
    if (cryptStatus == kCCSuccess) {
        //the returned NSData takes ownership of the buffer and will free it on deallocation
        return [NSData dataWithBytesNoCopy:buffer length:numBytesDecrypted];
    }
    
    free(buffer); //free the buffer;
    return nil;
}
```

In the two function, the third parameter is different at `CCCrypt` invoke.

**Comment by leocavalcante** [comment]
Sorry the delay.
Added the option to use AES without padding, just give a `null` value to it:
```dart
Encrypter(AES(key, iv, mode: AESMode.ecb, padding: null))
```
Does it helps?

**Comment by chinabrant** [comment]
thanks

**Comment by YDJSZY** [comment]
I have the same error, what's the reason ?

**Comment by KonKri** [comment]
It worked, I was working on a message I receive encrypted with AES 128 ECB, and I had the same issue! Please add it to the documentation if you can. Thanks anyways!!

**Comment by leocavalcante** [comment]
It is already there https://github.com/leocavalcante/encrypt#nozero-padding

**Comment by preetshah21699** [comment]
I am facing this issue right now with the version 5.0.3.

However, when I was using version 5.0.1, it didn't have this issue. So, now I have data already encrypted and stored on the server with the defaault padding values.

I believe, the default mode was sic and padding PKCS7. 

```dart
aes1Key = Key.fromUtf8(aes1Text);
aesKey = Key.fromUtf8(aesText);
aes1Encrypter = Encrypter(AES(aes1Key));
aesEncrypter = Encrypter(AES(aesKey));
```

If I use null for padding, it works. But it cannot decrypt my old data properly that was encrypted using the older library.

**Comment by preetshah21699** [comment]
I am facing the same issue. Putting the padding as null works. But I need a workaround as I have pre-existing data that was already encrypted when the library was working. Now that it is not working due to whatever issue, I can't decrypt the data. 

Any suggestions on this?

**Comment by ismaeldmlv** [comment]
> I am facing this issue right now with the version 5.0.3.
> 
> However, when I was using version 5.0.1, it didn't have this issue. So, now I have data already encrypted and stored on the server with the defaault padding values.
> 
> I believe, the default mode was sic and padding PKCS7.
> 
> ```dart
> aes1Key = Key.fromUtf8(aes1Text);
> aesKey = Key.fromUtf8(aesText);
> aes1Encrypter = Encrypter(AES(aes1Key));
> aesEncrypter = Encrypter(AES(aesKey));
> ```
> 
> If I use null for padding, it works. But it cannot decrypt my old data properly that was encrypted using the older library.

same bug on update to 5.0.3...
i fixed changing:
`final iv = IV.fromLength(16);`
to:
`final iv = IV.fromUtf8('KeyWith16CharsHere');`
but of course it not work for decrypt data encrypted by version 5.0.1 because we change the IV.

**Comment by aeternam-13** [comment]
Same issue here, version 5.0.3 just cant decrypt, thankfully the app is not in production yet

**Comment by oliverbytes** [comment]
Same issue here as well

**Comment by alfonsotesone** [comment]
Same problem here with 5.0.3

**Comment by preetshah21699** [comment]
I understand that there is a fix. But the fix isn't backwards compatible. How is someone supposed to use an encryption tool/package if there is no guaratee that they will be able to decrypt the data in the future. I understand that there must have been a bug fix or something that required you to make this change. But the basic functioning of the package should remaing the same and it should be backwards compatible.

**Comment by emadal95** [comment]
I am having the same problem. Data already encrypted is not decrypting anymore. This is a huge issue, is anything being done to fix this?

UPDATE: 
for anyone with this problem still and not able to decrypt old data, the old IV string created with IV.fromLength()  (in base64 below) was `AAAAAAAAAAAAAAAAAAAAAA==`
substitute your IV.fromLength(16) with IV.fromBase64('AAAAAAAAAAAAAAAAAAAAAA=='). this should let you at least decrypt the old password so you can now adjust to the new package encryption

**Comment by ghazalcomputer** [comment]
I have the same problem
Why did you close the issue?
Please check again
There is the same problem again

**Comment by leocavalcante** [comment]
Hi, folks
Please, just replace `IV.fromLength(16)` by `IV.allZerosOfLength(16)`.
As saw in #314 
**Remember that it is not cryptography safe**

**Comment by aeternam-13** [comment]
Hey, i found a solution. I don´t know how good it is but . . .

My use case is that i need new key and IV every login, except for some cases but almost every time is like that. 

I made a function that creates a random String from the characters bellow.


```dart
String _generateRandom(int length) {
    const String allowedChars =
        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
    final random = Random();
    final buffer = StringBuffer();
    for (var i = 0; i < length; i++) {
      final charIndex = random.nextInt(allowedChars.length);
      buffer.write(allowedChars[charIndex]);
    }
    return buffer.toString();
  }
```

And i  just use the generated values

```dart
      final encrypter =
          Encrypter(AES(Key.fromUtf8(secret.key)));
      final encrypted = encrypter.encrypt(original, iv: IV.fromUtf8(secret.iv));
```
