### ISSUE TITLE
publish latest version

### ISSUE THREAD

**Issue by devoncarew** [leocavalcante/encrypt#310]
Hi! Can you publish a new version of this package w/ the latest bits from master (`dart pub publish`)? It'll address a type issue people are seeing at runtime (`Warning: Operand of null-aware operation '!' has type 'BigInt' which excludes null.`). Thanks!

**Comment by JimWuerch** [comment]
Looks like there's a PR waiting to merge first that fixes it.

**Comment by Ri-car-do-1989** [comment]
I'm also waiting for this. Is this package still being maintained? It seems last pub.dev version is from 2 years ago...

**Comment by leocavalcante** [comment]
Sorry, folks. It is an one man job and I don't even work with Dart/Flutter anymore. I need to setup Dart and Pub on my new computer again.

You guys know a way to make an automation for that ? So I can add it to GitHub Actions maybe.

**Comment by JimWuerch** [comment]
I fixed the test failures the previous PR had also.  I haven't setup a GitHub actions for dart publish before, but I'll see if I can copy something from somewhere.  https://dart.dev/tools/pub/automated-publishing

**Comment by leocavalcante** [comment]
Thank you very much for the fixes and the link. It is published and now automated via GH releases.
https://pub.dev/packages/encrypt
