### ISSUE TITLE
type 'KeyParameter' is not a subtype of type 'PaddedBlockCipherParameters in AESMode.ecb

### ISSUE THREAD

**Issue by stoneLee81** [leocavalcante/encrypt#313]
When upgrading from 5.0.1 to 5.0.2, the AES ecb mode will report an PaddedBlockCipherParameters error。

flutter 3.13.4
encrypt 5.0.2

> unhandled exception:
> type 'KeyParameter' is not a subtype of type 'PaddedBlockCipherParameters<CipherParameters?, CipherParameters?>' of 'params'
> #0      PaddedBlockCipherImpl.init (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:45:71)
> #1      AES.encrypt (package:encrypt/src/algorithms/aes.dart:40:9)
> #2      Encrypter.encryptBytes (package:encrypt/src/encrypter.dart:12:19)
> #3      Encrypter.encrypt (package:encrypt/src/encrypter.dart:28:12)

**Comment by Yorkzero** [comment]
Same issue.

**Comment by leocavalcante** [comment]
Closed by https://github.com/leocavalcante/encrypt/pull/312 Shipped at v5.0.3
