### ISSUE TITLE
5.0.1, 5.0.2 and 5.03 cannot decrypt data 

### ISSUE THREAD

**Issue by mehdiwaysi** [leocavalcante/encrypt#316]
I get this error when decrypt data:

Invalid argument(s): Invalid or corrupted pad block

I didn't have this problem before in version 5.0.1. And recently this problem has arisen.

I updated the package to 5.0.2 , 5.0.3 and have the same error

**Comment by leocavalcante** [comment]
Duplicated: https://github.com/leocavalcante/encrypt/issues/314
