### ISSUE TITLE
Invalid argument(s): Invalid or corrupted pad block

### ISSUE THREAD

**Issue by milind169** [leocavalcante/encrypt#324]
Getting below error with latest version encrypt 5.0.3

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Invalid or corrupted pad block
                                                                                                    #0      PKCS7Padding.padCount (package:pointycastle/paddings/pkcs7.dart:47:9)
                                                                                                    #1      PaddedBlockCipherImpl.doFinal (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:112:30)
                                                                                                    #2      PaddedBlockCipherImpl.process (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:74:25)
                                                                                                    #3      AES.decrypt (package:encrypt/src/algorithms/aes.dart:68:22)
                                                                                                    #4      Encrypter.decryptBytes (package:encrypt/src/encrypter.dart:39:10)
                                                                                                    #5      Encrypter.decrypt (package:encrypt/src/encrypter.dart:50:7)
                                                                                                    #6      Encrypter.decrypt64 (package:encrypt/src/encrypter.dart:66:12)

**Comment by appu-sm** [comment]
Facing same issue while decrypting AES

**Comment by milind169** [comment]
Replaced 
IV.fromLength(16);
with 
IV.allZerosOfLength(16);

This worked for me.

**Comment by MattEllison95** [comment]
I don't get how changing the IV to allZerosOfLength makes the encryption secure.

**Comment by chandresh204** [comment]
IV.allZerosOfLength(16);
Works, Thanks @milind169

**Comment by Ahtsham0715** [comment]
I am also facing this issue and tried many solutions but no one worked.

**Comment by leocavalcante** [comment]
Replace `IV.fromLength(16)` to `IV.allZerosOfLength(16)`.

Remember: using an "all-zeros" IVs is not secure.

More info here: https://github.com/leocavalcante/encrypt/issues/314#issuecomment-1729810937

**Comment by Shivsaranyadav** [comment]
I am also facing this issue and tried many solutions but no one worked. 

My code is 

final cipherKey = Key.fromUtf8(passkey);

final encryptService = Encrypter(AES(cipherKey, mode: AESMode.cbc));

final initVector = IV.fromUtf8(passkey.substring(0, 16));

**Comment by pratikpwr** [comment]
Cause: IV value is not constant, new value is generated in each runtime.
We need to use the same IV to decrypt the data.

Solution:
1. generate IV
2. Store the base64 of IV to secure storage just like key

**Comment by shinayser** [comment]
> Replaced IV.fromLength(16); with IV.allZerosOfLength(16);
> 
> This worked for me.

Excuse me, but where can I find this method 'allZerosOfLength'? I am using encrypt 5.0.1 and my `IV` class doesn't have this constructor.

PS: Just found out, it exists only in `5.0.3`.
