### ISSUE TITLE
The name 'Key' is defined in the libraries 'package:encrypt/encrypt.dart' and 'package:flutter/src/foundation/key.dart'. 

### ISSUE THREAD

**Issue by allstar456** [leocavalcante/encrypt#33]
Hello leocavalcante,
    I'm build a flutter APP，add dependencies encrypt: ^2.2.0， then 'flutter packages get' success, input code like:
  final plainText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit';
  final key = Key.fromUtf8('my 32 length key................');
  final iv = IV.fromLength(16);

  final encrypter = Encrypter(AES(key, iv));

  final encrypted = encrypter.encrypt(plainText);
  final decrypted = encrypter.decrypt(encrypted);

  print(decrypted); // Lorem ipsum dolor sit amet, consectetur adipiscing elit
  print(encrypted.base64); // R4PxiU3h8YoIRqVowBXm36ZcCeNeZ4s1OvVBTfFlZRdmohQqOpPQqD1YecJeZMAop/hZ4OxqgC1WtwvX/hP9mw==

but the Android Studio the error: 'The name 'Key' is defined in the libraries 'package:encrypt/encrypt.dart' and 'pack'. What's wrong?

**Comment by leocavalcante** [comment]
You have a naming conflict, to libraries are exporting a symbol named `Key`.
You can solve this by adding an alias like:
```dart
import 'package:encrypt/encrypt.dart' as encrypt;
```
Then using the aliased version for every symbol:
```dart
final key = encrypt.Key.fromUtf8()
final iv = encrypt.IV.fromUtf8()
final encrypted = encrypt.Encrypter()
```

You can also alternatively hide the `Key`, if it isn't in use, exported by Flutter, like:
```dart
import 'package:flutter/material.dart' hide Key;
```

---
Duplicated
- #22 
- #26

**Comment by allstar456** [comment]
thank you!

**Comment by blackbeltandre** [comment]
thanks!

**Comment by cookie-blood** [comment]
Thanks!

**Comment by kea137** [comment]
Thanks

**Comment by schhunheng** [comment]
thank you!

**Comment by goc20** [comment]
can someone solve this issue also:
error: The name 'User' is defined in the libraries 'package:firebase_auth/firebase_auth.dart' and 'package:tunein/models/user.dart'. (ambiguous_import at [tunein] lib/resources/firebase_methods.dart:45)
//this is my firebase_methods .dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:tunein/models/user.dart';
import 'package:tunein/utils/utilities.dart';
class FirebaseMethods {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  GoogleSignIn _googleSignIn = GoogleSignIn();
  static final Firestore firestore = Firestore.instance;

  //user class
  User user = User();

  Future<User> getCurrentUser() async {
    FirebaseUser currentUser;
    currentUser =  FirebaseAuth.instance.currentUser;
    return currentUser;
  }

  Future<User> signIn() async {
    GoogleSignInAccount _signInAccount = await _googleSignIn.signIn();
    GoogleSignInAuthentication _signInAuthentication =
        await _signInAccount.authentication;

    final AuthCredential credential = GoogleAuthProvider.getCredential(
        accessToken: _signInAuthentication.accessToken,
        idToken: _signInAuthentication.idToken);

    User user = (await _auth.signInWithCredential(credential)).user;
    return user;
  }

  Future<bool> authenticateUser(User user) async {
    QuerySnapshot result = await firestore
        .collection("users")
        .where("email", isEqualTo: user.email)
        .getDocuments();

    final List<DocumentSnapshot> docs = result.documents;

    //if user is registered then length of list > 0 or else less than 0
    return docs.length == 0 ? true : false;
  }

  Future<void> addDataToDb(User currentUser) async {
    String username = Utils.getUsername(currentUser.email);

    user = User(
        uid: currentUser.uid,
        email: currentUser.email,
        name: currentUser.displayName,
        profilePhoto: currentUser.photoUrl,
        username: username);

    firestore
        .collection("users")
        .document(currentUser.uid)
        .setData(user.toMap(user));
  }

}



//this is my user.dart file
class User {
  String uid;
  String name;
  String email;
  String username;
  String status;
  int state;
  String profilePhoto;

  User({
    this.uid,
    this.name,
    this.email,
    this.username,
    this.status,
    this.state,
    this.profilePhoto,
  });

  Map toMap(User user) {
    var data = Map<String, dynamic>();
    data['uid'] = user.uid;
    data['name'] = user.name;
    data['email'] = user.email;
    data['username'] = user.username;
    data["status"] = user.status;
    data["state"] = user.state;
    data["profile_photo"] = user.profilePhoto;
    return data;
  }

  User.fromMap(Map<String, dynamic> mapData) {
    this.uid = mapData['uid'];
    this.name = mapData['name'];
    this.email = mapData['email'];
    this.username = mapData['username'];
    this.status = mapData['status'];
    this.state = mapData['state'];
    this.profilePhoto = mapData['profile_photo'];
  }
}

**Comment by adityarsingh** [comment]
Thank You!

**Comment by kuldep-cloud** [comment]
thankyou

**Comment by v1ncere** [comment]
Thank you!

**Comment by lyfer-bob** [comment]
Thank bro

**Comment by ged-flod** [comment]
Thank you !

**Comment by bluegene37** [comment]
Same error after I upgraded to ^5.0.3.
Works fine with 5.0.1 without the ^
When I debug it. I found out, it is giving random results.
It started doing random from this part.
final iv = IV.fromLength(16);
they have the same result as this one.
final iv = IV.fromSecureRandom(16);
Hope it can help.
