### ISSUE TITLE
Encrypter API encourages IV reuse

### ISSUE THREAD

**Issue by peter-fingo** [leocavalcante/encrypt#34]
To my understanding, it is insecure to use the same key, iv combination for encrypting multiple messages, at least in many contexts. The current Encrypter API seems to me like it encourages creating a single encrypter object (which has a static key,iv pair) and reusing it for encrypting multiple messages, which would then be insecure. 

Am I misunderstanding how this works? If not, it might be good to warn about this pitfall, or change the API.

**Comment by leocavalcante** [comment]
Thank you very much.
You are absolutely right, [v3 ](https://pub.dartlang.org/packages/encrypt/versions/3.0.0)will enforce a new IVs on the API.
