### ISSUE TITLE
How can i decrypt large file?

### ISSUE THREAD

**Issue by hasimyerlikaya** [leocavalcante/encrypt#40]
Thank you for this package.

I want to use in our project. When I decrypt small string, there is no problem.
But we encrypt large pdf file with aes. When we try decrypt file from base64 string, there is no action. No error or else. 

How can i decrypt large file (30mb, 90mb, ...) with aes?

  ```
String decrypt(Encrypted encrypted) {
    final key =
        encyrpt.Key.fromBase64("JTSBh84u1w2HScX3B7ndj3RwzDNbF.....");
    final iv = IV.fromBase64("h0nF9we53Y95op.....");
    final encrypter = Encrypter(AES(key, mode: AESMode.cbc));
    try {
      final decrypted = encrypter.decrypt(encrypted, iv: iv);

      return decrypted;
    } catch (e) {
      print(e);
    }
  }
```

**Comment by leocavalcante** [comment]
I have to check where the limitation is. Are you able to make this work using only PointyCastle?

**Comment by gsifni** [comment]
I have the exact same issue. Large files encrypted and when i decrypt the application freezes without error messages. I have to force close to restore the app.

**Comment by leocavalcante** [comment]
@gsifni are you able to use the PointyCastle alone without this encrypt package? This doesn't sounds to be an issue with encrypt it self.

**Comment by hasimyerlikaya** [comment]
I'm sorry for the late reply.

Then I saw that the test is actually working properly. For example, I waited 1 hour for a pdf file and opened successfully. The process takes a long time when opening high-size files.

**Comment by radvansky-tomas** [comment]
> I have the exact same issue. Large files encrypted and when i decrypt the application freezes without error messages. I have to force close to restore the app.

Same here, no error message and there is no limitation in place.
So its hard to tell why you cannot pass big file, or whats the recommended 
approach. I though there will be some sort of "chunked" reading of file
and partial encryption.

**Comment by wujek-srujek** [comment]
I also notice this issue. It takes about 40 seconds on the iOS simulator with a 1.3 mb image. I tried to investigate, and here are my findings:
- It must be the encryption/decryption logic. Reading the file in memory, and writing again, is fast < 300ms.
- Executing encryption in a separate isolate (as described here: https://flutter.dev/docs/cookbook/networking/background-parsing) is about 3-4 seconds faster, but still very slow. But at least it doesn't cause the application to hang.

**Comment by wujek-srujek** [comment]
Actually, I've just found something, take a look here: https://github.com/leocavalcante/encrypt/issues/126#issuecomment-626381918.
