### ISSUE TITLE
Problem encrypting List<int> 

### ISSUE THREAD

**Issue by diso73** [leocavalcante/encrypt#43]
Hi,
I'm trying to encode some binary data I receive as a List<int>. 
As the encrypt methods only receives String I need to create one using String.fromCharCodes (or UTF8Decoder), but with some specific sequences, this String constructor fails with "Bad UTF-8 encoding 0xf9".
I know you plan to release versions of 'encrypt' and 'decrypt' methods for binary data (issue #14); I would really need it for a project I'm working on; I have a (little) budget for this feature if you can deliver it fast (really fast...).

The data sequence I cannot encrypt is:
[17, 97, 97, 97, 0, 0, 0, 0, 0, 0, 0, 49, 50, 51, 52, 53, 0, 0, 0, 249, 24, 25, 5, 19, 12, 9, 0, 0, 0, 0, 0]

Thank you 

Francesco

**Comment by diso73** [comment]
I' pasted the wrong sequence, the real one doesn't have the negative number (-19) on the 24th byte.
the right sequence that can't be encrypted is:
[17, 97, 97, 97, 0, 0, 0, 0, 0, 0, 0, 49, 50, 51, 52, 53, 0, 0, 0, 252, 204, 25, 5, 19, 12, 9, 0, 0, 0, 0, 0]

**Comment by leocavalcante** [comment]
Please, tell me if [`encryptBytes`](https://github.com/leocavalcante/encrypt/pull/44) fulfills your needs. 

```dart
import 'package:encrypt/encrypt.dart';

void main() {
  final key = Key.fromLength(32);
  final iv = IV.fromLength(8);
  final encrypter = Encrypter(Salsa20(key));
  final input = [17, 97, 97, 97, 0, 0, 0, 0, 0, 0, 0, 49, 50, 51, 52, 53, 0, 0, 0, 249, 24, 25, 5, 19, 12, 9, 0, 0, 0, 0, 0];
  final encrypted = encrypter.encryptBytes(input, iv: iv);

  print(encrypted.base64);
}
```

##### output
```
i/aXOptMchuWCmcQd8+c4eMuZwAJB6xqwpVIJoBq7g==
```
