### ISSUE TITLE
RSA type cast exception

### ISSUE THREAD

**Issue by LesterSixNet** [leocavalcante/encrypt#47]
![image](https://user-images.githubusercontent.com/47265717/58770715-2f59de80-85e3-11e9-966a-7833f7721742.png)

use doc demo:
![image](https://user-images.githubusercontent.com/47265717/58770724-38e34680-85e3-11e9-9e79-7a3f655f9510.png)

throw error:
![image](https://user-images.githubusercontent.com/47265717/58770741-50baca80-85e3-11e9-9846-b05428f3b1fc.png)

**Comment by HeiSiBaby** [comment]
这个问题解决了么？
