### ISSUE TITLE
How could I Use AES/CBC/PKCS5Padding

### ISSUE THREAD

**Issue by lonely4flow** [leocavalcante/encrypt#48]
My server workmate decide use RSA and AES to encode and decode data,The AES rule is  AES/CBC/PKCS5Padding,but the defualt padding is PKCS7,there is no choice for PKCS5,how could I use for PKCS5Padding?

**Comment by lonely4flow** [comment]
And how to use public RSA key to decode data?

**Comment by leocavalcante** [comment]
Sorry, there is no support for PKCS5 on PointyCastle, so I can wrap it in Encrypt.

Public keys on asymmetric cryptography, like RSA, are intended to be used only for encryption, that is why it can be public, because it won't be decrypting nothing, only encrypting.

**Comment by lonely4flow** [comment]
that‘s ok,I have use flutter plugin package solve this problem.
using public key to decryp data  maybe not good,but it is decided by our architect，I can do nothing but follow😁

**Comment by nateshmbhat** [comment]
Pkcs7 should work for a server with PKCS5 padding.

I just tested it for my server which uses PKCS5 while using Pkcs7 padding at encryption.

Pointy castle guys say they both should work the same.
