### ISSUE TITLE
Can encrypt be decrypted only with a public encryption private key? 

### ISSUE THREAD

**Issue by igufei** [leocavalcante/encrypt#49]
Can encrypt be decrypted only with a public encryption private key? I now want to implement such a function, put a private key on the server, the client puts a public key, the client uses the public key to encrypt the data, the server uses the private key to decrypt the data, and then the server encrypts the response data using the private key and sends it to the client. End, the client uses the public key to decrypt, this function I have implemented in C#, nodejs, golang, no method found on dart

**Comment by leocavalcante** [comment]
Hi @igufei 
Please, check if [setting `isSignature: true` on the RSA constructor](https://github.com/leocavalcante/encrypt/blob/master/test/encrypt_test.dart#L128) fulfills your needs.

**Comment by igufei** [comment]
@leocavalcante thank you

**Comment by YourksChan** [comment]
4.1.0 How should we deal with this problem?

**Comment by leocavalcante** [comment]
@YourksChan https://github.com/leocavalcante/encrypt#signature-and-verification

**Comment by YourksChan** [comment]
> @YourksChan https://github.com/leocavalcante/encrypt#signature-and-verification

It is not possible to perform separate encryption and decryption of public and private keys. Only private key encryption and public key decryption can be performed.

Expanle:
https://blog.csdn.net/rznice/article/details/104486712/
