### ISSUE TITLE
What is the maximum RSA public and private key size?

### ISSUE THREAD

**Issue by NTMS2017** [leocavalcante/encrypt#51]
I want to use RSA and use "pub global active encrypt" create a keys, but I don't know what is maximum length to select.

In your RSA example you have public_key.pem and private_key.pem. What is maximum length I can get? Also I have a 2 mb reshape string. Can I encrypt that big string?

Thank you very much

**Comment by leocavalcante** [comment]
There is no specific maximum limit for the key, you can try as much as your machine+DartVM can handle.

For encrypting and decrypting is the same. People are having problems with large files #40 but nothing I can do from a wrapper perspective.

**Comment by NTMS2017** [comment]
I converted a RSA string and send to socket. In return I get some text from socket and gain encode 2048 RSA. some times I get very big file such as 500KB or 1 MB text that is convereted to rsa string. My question was can I encrypt string (500kb or 1mb text) using RSA 2048 string. but the link talks about pdf with 30 or 90 mb size. I guess mine is less so it can encrypt that much. Thanks again.
