### ISSUE TITLE
can't open public or private key

### ISSUE THREAD

**Issue by NTMS2017** [leocavalcante/encrypt#52]
Hi Leo,

I create a 2048 key. I crate dart console app. I keep getting this error. Any idea?

**Error:**
```
Unhandled exception:
FileSystemException: Cannot open file, path = 'public_key.pem' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:547:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:592:18)
```

**My Code**
```
class NtmsRsa {
  getPrivateKey() {
    final privateKeyFile = File('private_key.pem');
    final parser = RSAKeyParser();
    final privateKey = parser.parse(privateKeyFile.readAsStringSync()) as RSAPrivateKey;
    return privateKey;
  }

  getPublicKey() {
    final publicKeyFile = File('public_key.pem');
    final parser = RSAKeyParser();
    final publicKey = parser.parse(publicKeyFile.readAsStringSync()) as RSAPublicKey;
    return publicKey;
  }
}
```

**I call as:**

setPrivate.dart
```
Future<String> setPrivate(String capitalPrivateValue) async {
  NtmsRsa _ntmsRsa = new NtmsRsa();
  final encrypter = Encrypter(RSA(publicKey: _ntmsRsa.getPublicKey(), privateKey: _ntmsRsa.getPrivateKey()));
  final encrypted = encrypter.encrypt(capitalPrivateValue);
  return encrypted.base64;
}
```

**main.dart**
```
String _encryptedData = await setPrivate("$myString");
  print(_encryptedData);
```

**Comment by leocavalcante** [comment]
The error is saying that it could not find the `public_key.pem` file. There is a file with that name in the same directory you are running `dart`?

**Comment by NTMS2017** [comment]
Yes it is. And it is in the bin folder.

I craeted 2048 bit key file using online tools.

unttiled (project)
 - ... some other files till bin
 - bin
   - main.dart
   - ntms_rsa.dart
   - ntmsSetPrivate.dart
   - private_key.pem
   - public_key.pem

**Comment by NTMS2017** [comment]
I am using intellij and created demo dart console app for testing.

**Comment by NTMS2017** [comment]
ok I put them in lib directory and its working. This time I got "pointycastle" error. How can I solve this.

Unhandled exception:
Invalid argument(s): Input data too large
#0      PKCS1Encoding._encodeBlock (package:pointycastle/asymmetric/pkcs1.dart:101:7)
#1      PKCS1Encoding.processBlock (package:pointycastle/asymmetric/pkcs1.dart:92:14)
#2      BaseAsymmetricBlockCipher.process (package:pointycastle/src/impl/base_asymmetric_block_cipher.dart:15:15)
#3      RSA.encrypt (package:encrypt/src/algorithms/rsa.dart:27:30)
#4      Encrypter.encryptBytes (package:encrypt/src/encrypter.dart:11:17)
#5      Encrypter.encrypt (package:encrypt/src/encrypter.dart:16:12)
#6      setPrivate (file:///Users/niyazitoros/niyazitoros/IdeaProjects/untitled/bin/ntmsSetPrivate.dart:10:31)

**Comment by NTMS2017** [comment]
I keep getting too large error. I am using 2048 bir rsa public and private key. The text is below.
how can I return version 2.1.0?  It seems version 3.1.0 cannot handle below text size.

```
Unhandled exception:
Invalid argument(s): Input data too large
#0      PKCS1Encoding._encodeBlock (package:pointycastle/asymmetric/pkcs1.dart:101:7)
```



Text:
 String myString = "1967-Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elementum pharetra tellus a consequat. Aenean risus diam, vehicula sed suscipit vitae, ornare in lectus. Sed maximus eu justo ac rutrum. Donec maximus nunc a elementum hendrerit. Quisque vulputate mattis ligula nec pulvinar. Vestibulum vitae mauris eget ligula eleifend tempus. Curabitur id ultrices sapien, ut gravida risus. Sed auctor nisi ac suscipit maximus. Proin volutpat eros ut ex tincidunt, non commodo mauris cursus. Vestibulum finibus porttitor lobortis. Fusce quis suscipit mi. Vivamus nec finibus quam, et tristique sapien. Nunc id consectetur turpis. Praesent eget egestas ligula. Nulla ut accumsan orci. In sed eros a ex imperdiet fringilla ut sit amet orci. Fusce nec fermentum odio, imperdiet accumsan velit. Mauris quis neque iaculis turpis ornare commodo. Phasellus dignissim ipsum a elit congue ornare. Phasellus in imperdiet lorem. Sed et lacus laoreet, eleifend mauris vel, aliquet elit. Etiam sed ligula posuere nunc vulputate mattis id sed diam. Vivamus maximus tristique neque. Aenean suscipit, orci ut feugiat molestie, turpis tellus viverra ex, vitae tincidunt enim tortor in felis. Sed sed commodo justo, vitae porttitor libero. Cras est enim, ultrices vel placerat sit amet, scelerisque quis ex. Nullam vel consectetur libero. Proin commodo metus in lectus efficitur malesuada. Pellentesque erat magna, convallis sit amet rhoncus nec, congue a odio. Phasellus lorem risus, convallis in iaculis nec, interdum id dolor. Nullam congue ut leo id pulvinar. Nullam maximus quam ac arcu maximus molestie. Maecenas molestie ullamcorper orci, ut convallis orci posuere at. Nullam nec dolor non nisl semper dapibus. Fusce cursus lacus sit amet auctor sodales. Nulla nibh arcu, iaculis vitae mollis at, consectetur ultrices sapien. Pellentesque imperdiet justo at vulputate tempor. Quisque a est ipsum. Sed varius ac est id sodales. Nam porta lectus augue, at aliquet augue tristique non. Suspendisse potenti. Curabitur eu sem et risus efficitur elementum in sed sapien. Quisque laoreet lobortis massa sed molestie. Vestibulum luctus aliquet lacus eu pretium. Suspendisse nec sodales orci. Donec fermentum ligula nec arcu hendrerit, quis tristique sem consectetur. Etiam pulvinar turpis eget metus iaculis imperdiet. Proin ut odio dignissim massa rhoncus ornare. Cras quam nibh, cursus at porttitor nec, rutrum vel est. Duis lorem mauris, vestibulum non nunc ac, tincidunt convallis dui. Suspendisse rhoncus turpis non sem consectetur, in vehicula purus condimentum. Maecenas accumsan mi sapien, in tristique nisi imperdiet et. Sed et nulla non nunc laoreet mattis. Ut a quam eget quam lacinia pellentesque eleifend vitae purus. Nulla tempus nec quam quis posuere. Nam at cursus felis. Vestibulum a ante non neque mattis fermentum. Sed ut aliquet tortor, non pharetra est. Nam non varius diam. Sed est nisi, laoreet sed eros ac, posuere vehicula lacus. Nullam metus risus, vehicula sit amet lorem laoreet, vehicula congue tellus. Nulla enim dolor, faucibus at nisl quis, mattis consequat est. Praesent interdum fermentum ultricies.-2019.";

**Comment by NTMS2017** [comment]
When I use version 2.1.0 AES same text works perfectly. Before closing the issue I need ask a question. Which is more secure in my example the RAS or AES?

I use below code and above my post the text worked as I expected. Sorry my last question. Can I increase key and iv length? say 128 to 32?

 final key = Key.fromUtf8(_ntmsRsa.PRIVATE_KEY); //Key.fromLength(32);
 final iv = IV.fromUtf8(_ntmsRsa.IV_KEY); //IV.fromLength(8);

**Comment by leocavalcante** [comment]
[RSA+PKCS1 can handle only 245 bytes](https://security.stackexchange.com/questions/33434/rsa-maximum-bytes-to-encrypt-comparison-to-aes-in-terms-of-security).

Can't tell which is more secure, they play very different roles, even being symmetric and asymmetric, you must find out what fits best for your needs.

**Comment by leocavalcante** [comment]
Closed due inactivity.

**Comment by developmentkws** [comment]
Solved , Check :  [Solution](https://github.com/leocavalcante/encrypt/issues/86#issuecomment-903473711)
