### ISSUE TITLE
Problem decrypting data with 0xFF 

### ISSUE THREAD

**Issue by diso73** [leocavalcante/encrypt#54]
Hi, 
we're using AES with ECB to encrypt/decrypt binary data (chunks of 16 bytes) sourcing from a BLE device. This is the decrypt part:

    String buf = hex.encode(chunk);
    String decodedDataStr = _aesDecrypter.decrypt16(buf);
    Uint8List decodedData = Uint8List.fromList(decodedDataStr.codeUnits);

With the current implementation, using “decrypt16” and then the “String.codeUnits” property to get Uint8List, it seems that some sequences like:

[0xFF, 0xFF, 0xFF, 0xFF, ...up to 16 bytes.... ] (values before encryption)

decodes the “0xFF” values as “0xFD”, obviously causing big problems. 

Could you please implements decryptBytes(List<int>) -> List<int> as you did for encryptBytes?

Thanks a lot

Francesco

**Comment by leocavalcante** [comment]
Hi @diso73 
Can you check if `decryptBytes` of `3.2.0` fulfills your needs?
Cheers!
