### ISSUE TITLE
How could I use AES/ECB/NoPadding

### ISSUE THREAD

**Issue by bookjan** [leocavalcante/encrypt#60]
Hi, I want to know how to use AES/ECB/NoPadding in Dart. Does encrypt support it? Thank you.

**Comment by leocavalcante** [comment]
Hi, yes, it does, you can:
```dart
Encrypter(AES(key, mode: AESMode.ecb, padding: null));
```

**Comment by bookjan** [comment]
Wonderful! Thank you very much.
