### ISSUE TITLE
Encrypt in php and decrypt in Dart(flutter)

### ISSUE THREAD

**Issue by mmojbo** [leocavalcante/encrypt#61]
Hi, 
I'm new in flutter and using PHP OpenSSL encrypt with AES-256-CBC mode. 
I want to decrypt output in a flutter, but get an error message:
"Invalid argument(s): Input buffer too short".
I saw #53 and #8 but cannot solve my problem.
Also, try to decrypt on the web and get success.
https://encode-decode.com/aes-256-cbc-encrypt-online/
txt = k2EfYozdaJudTbKjPj2WmQ==
eKey = &5P483usHDhA32JUj55@CdcrbupasysB

This is my code in Flutter:
```
void decrypt(String txt, String eKey) {

  final key = Enq.Key.fromUtf8(eKey);
  final iv = Enq.IV.fromLength(16);
  var ttt = utf8.decode(base64Decode(txt));

  final encrypter = Enq.Encrypter(Enq.AES(key, mode: Enq.AESMode.cbc));
  final input = Enq.Encrypted.fromUtf8(ttt);
  final decrypted = encrypter.decrypt(input, iv: iv);
  print(decrypted);
}

```
Thanks for the help. @leocavalcante

**Comment by mmojbo** [comment]
can anyone help me?
@yapcwed @shutup @Jethro87 @benittopremkumar

**Comment by leocavalcante** [comment]
Hi @mmojbo 
Is your decrypted string `{"opr":1}`?
Try:
```dart
final key = Key.fromUtf8('&5P483usHDhA32JUj55@CdcrbupasysB');
final encrypter = Encrypter(AES(key, mode: AESMode.cbc));
print(encrypter.decrypt64('k2EfYozdaJudTbKjPj2WmQ==', iv: IV.fromLength(16)));
```

**Comment by mmojbo** [comment]
Thank you so much, Leo, it's working!

**Comment by joumduk** [comment]
Can you share how to encrypt data in php ?

**Comment by leocavalcante** [comment]
@joumduk see if this helps https://github.com/leocavalcante/encrypt/issues/87#issuecomment-549619391

**Comment by HimanshuSaikia** [comment]
Please help/guide me to decrypt an encrypted mp4 file in dart. The file was encrypted using PHP OpenSSL encrypt with AES-256-CBC mode.

**Comment by leocavalcante** [comment]
Hi @HimanshuSaikia, it will be like in https://github.com/leocavalcante/encrypt/issues/87#issuecomment-549619391 but instead of using a argument from the command line input, you should use Dart's IO File reader.

**Comment by sandeepsoni25** [comment]
how can i encrypt/decrypt my pdf file?

**Comment by leocavalcante** [comment]
@sandeepsoni25 load the file as bytes and use encrypt bytes.

**Comment by HimanshuSaikia** [comment]
> 
> 
> Hi @HimanshuSaikia, it will be like in [#87 (comment)](https://github.com/leocavalcante/encrypt/issues/87#issuecomment-549619391) but instead of using a argument from the command line input, you should use Dart's IO File reader.

Thanks a lot for your instant reply. So, according to your logic, I successfully encrypted a file in php, decrypted the file in php too. Although text decryption is working in dart, But when i try to decrypt a video file in dart, it's not working. The output file is not recognised as any format by the player. also the file size is larger than the original as well as the encrypted file. 

'filePath' contains the php encrypted video file.
My decryption code is:
//***********************
import 'package:encrypt/encrypt.dart' as enc;
//**********************
Future<String> decryptFile(filePath) async{
    var encodedKey = base64.encode(utf8.encode('*********Same Plain String*********'));
    var encodedIv = base64.encode(utf8.encode('*********Same Plain String**********'));
    var text = new File(filePath).readAsStringSync();
    final key1 = enc.Key.fromBase64(encodedKey);
    final iv = enc.IV.fromBase64(encodedIv);
    final encrypter = enc.Encrypter(enc.AES(key1, mode: enc.AESMode.cbc));
    final decrypted = encrypter.decrypt(enc.Encrypted.fromBase64(text), iv: iv);
    final filename = '${p.basenameWithoutExtension(filePath)}.mp4';
    final directoryName=p.dirname(filePath);
    final newFilePath=p.join(directoryName, filename);
    List<int> bytes = utf8.encode(decrypted);print(bytes);
    var newFile = new File(newFilePath);
    await newFile.writeAsBytes(bytes);
    return newFilePath;
  }

**Comment by leocavalcante** [comment]
@HimanshuSaikia 
Read the file as binary and do not pass its content through base 64 decoding (i.e.: `enc.Encrypted.fromBase64(text)`) it's not saved as base 64, its plain binary.

**Comment by HimanshuSaikia** [comment]
> 
> 
> @HimanshuSaikia
> Read the file as binary and do not pass its content through base 64 decoding (i.e.: `enc.Encrypted.fromBase64(text)`) it's not saved as base 64, its plain binary.

Bro, But decrypt function ```encrypter.decrypt()``` returns a string!!

**Comment by leocavalcante** [comment]
Bro, checkout `encryptBytes` and `decryptBytes`: https://pub.dev/documentation/encrypt/latest/encrypt/Encrypter/encryptBytes.html ;)

**Comment by HimanshuSaikia** [comment]
> 
> 
> Bro, checkout `encryptBytes` and `decryptBytes`: https://pub.dev/documentation/encrypt/latest/encrypt/Encrypter/encryptBytes.html ;)

**BRO, YOU ARE AMAZING.** Thank you so much for the much needed support. I owe you.
**Finally I did the php encryption and dart decryption successfully for a video file.**
 There was a slight trick though, and that was, ```openssl_encrypt()``` does a base64 encoding to the final output which is then saved to the file. So, in dart, before passing to ```decryptBytes``` we need to do a base64 decoding first of the string first. I am providing my code open here. Thanks once again Leo Cavalcante.

** PHP Encryption code**
I am using the following key and iv in php.
$key='FCAcEA0HBAoRGyALBQIeCAcaDxYWEQQPBxcXHgAFDgY=';
$iv='DB4gHxkcBQkKCxoRGBkaFA==';
The encryption& decryption functions: 
```php
function encryptFile($encKey, $encIV, $inPath, $outPath) {
        $sourceFile=file_get_contents($inPath);
        $key = base64_decode($encKey);
        $iv = base64_decode($encIV);
        $path_parts = pathinfo($inPath);
        $fileName=$path_parts['filename'];
        $outFile=$outPath.$fileName.'.himu';
        $encrypter = 'aes-256-cbc';
        $encryptedString = openssl_encrypt($sourceFile, $encrypter, $key, 0, $iv);
        if(file_put_contents($outFile, $encryptedString)!= false) return 1;
        else return 0;
    }
```
**PHP Decryption**
```php
function decryptFile($encKey, $encIV, $inPath, $outPath) {
        $encryptedString=file_get_contents($inPath);
        $key = base64_decode($encKey);
        $iv = base64_decode($encIV);
	$path_parts = pathinfo($inPath);
        $fileName=$path_parts['filename'];
        $outFile=$outPath.$fileName.'.mp4';
        $encrypter = 'aes-256-cbc';
        $decrypted = openssl_decrypt($encryptedString, $encrypter, $key, 0, $iv);
        if(file_put_contents($outFile, $decrypted)!= false) return 1;
        else return 0;
    }
```

**DART Decryption**
```dart
Future<String> decryptFile(filePath) async{  //'filePath' contains the php encrypted video file.
    var encodedKey = 'FCAcEA0HBAoRGyALBQIeCAcaDxYWEQQPBxcXHgAFDgY=';
    var encodedIv = 'DB4gHxkcBQkKCxoRGBkaFA==';
    var encryptedBase64EncodedString = new File(filePath).readAsStringSync();
    var decoded = base64.decode(encryptedBase64EncodedString);
    final key1 = enc.Key.fromBase64(encodedKey);
    final iv = enc.IV.fromBase64(encodedIv);
    final encrypter = enc.Encrypter(enc.AES(key1, mode: enc.AESMode.cbc));
    final decrypted = encrypter.decryptBytes(enc.Encrypted(decoded), iv: iv);print("2");
    final filename = '${p.basenameWithoutExtension(filePath)}.mp4';
    final directoryName=p.dirname(filePath);
    final newFilePath=p.join(directoryName, filename);
    var newFile = new File(newFilePath);
    await newFile.writeAsBytes(decrypted);
    return newFilePath;
  }
```

**Comment by armandohackcode** [comment]
@[HimanshuSaikia](https://github.com/HimanshuSaikia)  thanks, it worked very well for me, I used it as a base to make my function to decrypt a text based on the same encryption logic done with php and Lumen

 ```dart
  import 'dart:convert';
  import 'package:encrypt/encrypt.dart' as enc;
  import 'dart:async';
  import 'package:php_serializer/php_serializer.dart';

  Future<String> decryptInfo(String data) async {
        var encodedKey = 'FCAcEA0HBAoRGyALBQIeCAcaDxYWEQQPBxcXH****** example';
        var decoded = base64.decode(data);
       var payload = json.decode(String.fromCharCodes(decoded));
       String encodedIv = payload["iv"]?? "";
       String value = payload["value"] ?? "";
       print(decoded);
       print(payload);
       print (encodedIv);
       final key1 = enc.Key.fromBase64(encodedKey);
       final iv = enc.IV.fromBase64(encodedIv);
      final encrypter = enc.Encrypter(enc.AES(key1, mode: enc.AESMode.cbc));
      final decrypted = encrypter.decrypt(enc.Encrypted.fromBase64(value), iv: iv);
      print(phpDeserialize(decrypted));
    return decrypted;
   } 
```

**Comment by udoy-touhid** [comment]
@leocavalcante @HimanshuSaikia 
Kudos to both you guys. This thread has really been helpful and save me after quite some headache.

**Comment by udoy-touhid** [comment]
@HimanshuSaikia I'm just confused in one line.

`     $encrypted = openssl_encrypt($text, $encrypter, $key, 0, $iv);
`

if $encrypted contains only binary data, why we need to base64 decode it first on dart?

```
encryptedBase64EncodedString = new File(filePath).readAsStringSync();
var decoded = base64.decode(encryptedBase64EncodedString);

```
Could you please clarify?

**Comment by Vidwath23** [comment]
Hii @HimanshuSaikia

can you please share a complete code it helps me a lot

**Comment by mohamaddoost** [comment]
hi, can anyone explain that how can encode in flutter and decode in php?
