### ISSUE TITLE
Block thread

### ISSUE THREAD

**Issue by fast0490f** [leocavalcante/encrypt#64]
Hi, I am using code, value - big variable
```js
encrypter.decrypt64(value, iv: iv)
```
I tried to wrap the code in the future, but to no avail. The main thread is blocked

```js
dec(value) {
  var completer = new Completer();
  completer.complete(encrypter.decrypt64(value, iv: iv));
  return completer.future;
}
```

**Comment by leocavalcante** [comment]
Dart async features works only for I/O operations. Like Node.js, Dart VM execute computations on a single-thread, then CPU-intensive tasks likes encryption, blocks this single thread.
Fortunetelly there ares Isolates! You should use them to really delegate a task to a different thread from the main.
