### ISSUE TITLE
AES does not support key with length 64

### ISSUE THREAD

**Issue by gustavosatheler** [leocavalcante/encrypt#68]
How I can to use a key of the length 64?
For example:

```dart
var myKey = HMAC256('my awesome message', 'my secret key 123') // 1a991c1e2984f20af91361f916a708b1fc7e247f8f4e6cc090b89fe0280d39ed
final key = Key.fromUtf8(myKey);
```

**Comment by leocavalcante** [comment]
Length 64 you mean 64 bytes, I guess, right?
[AES specification limits key sizes on 128, 192, or 256 bits](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard). A 64 bytes means a 512 bits key, which isn't supported by the algorithm itself.

Any way, the output of the `HMAC256()` you posted resembles a Hexdecimal string, to use this output, you should create a `Key` using the `fromBase16` constructor. This hexdec hash itself you posted (1a991c1e2984f20af91361f916a708b1fc7e247f8f4e6cc090b89fe0280d39ed) is 32 bytes (or 256 bits) which is supported by the AES algorithm, look:

```dart
import 'package:encrypt/encrypt.dart';

void main() {
  final key = Key.fromBase16('1a991c1e2984f20af91361f916a708b1fc7e247f8f4e6cc090b89fe0280d39ed');

  assert(key.bytes.length == 32);

  final iv = IV.fromLength(16);

  final encrypter = Encrypter(AES(key));
  final encrypted = encrypter.encrypt('Lorem ipsum', iv: iv);

  print(encrypted.base16); // cbd1b4ea592191d9d9b498303e29bfe0
}
```

**Comment by gustavosatheler** [comment]
Sorry, I didn't know that specification. Thank you very much.
