### ISSUE TITLE
Does not compile with DDC anymore

### ISSUE THREAD

**Issue by alextekartik** [leocavalcante/encrypt#74]
Thanks for the convenient plugin.

I have somes unit test on one project [sembast](https://travis-ci.org/tekartik/sembast.dart/builds/580880109) that recently failed (encrypt 3.3.0 fails while 3.2.0 succeeds).

I was able to reproduce the issue by creating a 'Bare bones Web App'. Once I add the following import in `lib/main.dart`:
```dart
import 'package:encrypt/encrypt.dart';
```

I get the following error trying to run the project:
```
[INFO] Building new asset graph completed, took 760ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Serving `web` on http://127.0.0.1:53322
[INFO] Running build completed, took 974ms
[INFO] Caching finalized dependency graph completed, took 87ms
[INFO] Succeeded after 1.1s with 11 outputs (1609 actions)
[INFO] ------------------------------------------------------------------------
[INFO] Updating asset graph completed, took 5ms
[WARNING]build_web_compilers:entrypoint on web/main.dart: Skipping compiling starter|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

encrypt|lib/encrypt.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings

[INFO] Running build completed, took 3.6s
[INFO] Caching finalized dependency graph completed, took 77ms
[INFO] Succeeded after 3.7s with 239 outputs (512 actions)
[INFO] ------------------------------------------------------------------------
```

This is just a warning but it actually make any web test ran using:
```
pub run build_runner test -- -p chrome
```
fails if `encrypt.dart` is imported.

There might be transitive io dependencies, if anything changed recently. Maybe here:
https://github.com/leocavalcante/encrypt/commit/410406382bdc6c17f5fdbdec9b184bfb681b590f#diff-539068640fca0ab0200b3f4d367d424c

It would be great if the existing lib could work as pure dart (i.e. no io dependencies) to allow usage in node/web environment. And if needed add a new `encrypt_io.dart` for code that requires io. Thanks!

**Comment by leocavalcante** [comment]
Please, update to [v3.3.1](https://pub.dev/packages/encrypt). Thank you for reporting.

**Comment by alextekartik** [comment]
That was fast. Thanks for the fix, it looks [all good](https://travis-ci.org/tekartik/sembast.dart/builds/580944717) on my side.
