### ISSUE TITLE
Is this a good library for file encryption?

### ISSUE THREAD

**Issue by VadimOsovsky** [leocavalcante/encrypt#76]
Is this library good for encrypting 10+ mb files?

**Comment by leocavalcante** [comment]
I don't think so, some people are having problems using PointyCastle implementations on large files. The DartVM isn't a good fit for that:
https://github.com/PointyCastle/pointycastle/issues/202
https://github.com/leocavalcante/encrypt/issues/40
It works, but takes a loooong time.

You can try Dart AOT or FFI+libsodium.

**Comment by VadimOsovsky** [comment]
@leocavalcante how much time does a 1mb decryption take on average?

**Comment by leocavalcante** [comment]
@VadimOsovsky I've didn't any benchmarks, but I think that 1mb should be ok (reasonable amount of time). By the issues people are getting problems with +30mb.

**Comment by phanirithvij** [comment]
@leocavalcante can you please elaborate on how one can use Dart AOT or FFI libsodium?
