### ISSUE TITLE
i need use encrypt content length not 16.

### ISSUE THREAD

**Issue by crny** [leocavalcante/encrypt#78]
i need use encrypt content length not 16.
`Unhandled exception:
RangeError (index): Index out of range: index should be less than 14: 14
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1      SICStreamCipher.processBytes (package:pointycastle/stream/sic.dart:61:39)
#2      StreamCipherAsBlockCipher.processBlock (package:pointycastle/adapters/stream_cipher_as_block_cipher.dart:31:18)
#3      AES._processBlocks (package:encrypt/src/algorithms/aes.dart:45:25)
#4      AES.encrypt (package:encrypt/src/algorithms/aes.dart:22:24)
#5      Encrypter.encryptBytes (package:encrypt/src/encrypter.dart:12:19)
#6      Encrypter.encrypt (package:encrypt/src/encrypter.dart:20:12)`
_Originally posted by @crny in https://github.com/leocavalcante/encrypt/issues/77#issuecomment-532022006_

**Comment by crny** [comment]
how to revise blockSize?

**Comment by leocavalcante** [comment]
Since you are not using padding, you **MUST** use inputs multiples of you key size (16 bytes). It is how block ciphers works: https://en.wikipedia.org/wiki/Block_cipher

**Comment by crny** [comment]
i know key must size 16 bytes. context is 14 bytes. has error.like this
`import 'package:encrypt/encrypt.dart';

void main() {
  final key = Key.fromUtf8('128bitkey16bytes');
  final iv = IV.fromLength(8);
  final encrypter = Encrypter(AES(key, mode: AESMode.ctr, padding: null));
  final encrypted = encrypter.encrypt('Hello world'.padRight(14), iv: iv);
}`
