### ISSUE TITLE
Input lenth error

### ISSUE THREAD

**Issue by benittopremkumar** [leocavalcante/encrypt#8]
input characters limited to 16,32,64 and so on otherwise it returns Input buffer too short.

**Comment by leocavalcante** [comment]
This is a "limitation" of the Block cipher specification, as the name says, it operate on blocks, fixed-length blocks, which means fixed-length sizes for both input and key. You should pad your input.
https://en.wikipedia.org/wiki/Block_cipher

If padding is a issue, you can try a Stream cipher, like Salsa20.

**Comment by benittopremkumar** [comment]
Thank you
