### ISSUE TITLE
I want to encrypt video file

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [leocavalcante/encrypt#81]
I want to encrypt video file. How can I do? Please help me.

**Comment by leocavalcante** [comment]
Read the file using [readAsBytes](https://api.dartlang.org/stable/2.5.2/dart-io/File/readAsBytes.html) then encrypt it using [encryptBytes](https://pub.dev/documentation/encrypt/latest/encrypt/Encrypter/encryptBytes.html).
