### ISSUE TITLE
AES/ECB/NoPadding for MiBand3 authorization

### ISSUE THREAD

**Issue by aytunch** [leocavalcante/encrypt#83]
Hi @leocavalcante 
Thanks for this great package. I am trying to communicate with my MiBand 3 using Bluetooth and the authorization requires to encrypt a key with **"AES/ECB/NoPadding"**. There are repos which accomplish this in Java, JavaScript, Python and Android. I am trying to port those in to Dart using your package. 
Authorization to the MiBand3 requires 3 steps. The first 2 steps, I can talk to the MiBand3 successfully but in the 3rd step the encryption comes in and I am having trouble. I shared my current encryption code and the working codes of others from different languages. As you can see from my output,

> randomkey(Message to be encrypted): 5b13c8a4ad4dcacedfe7ac58f1e16e42
> SECRET_KEY(used to encrypt): 01234567890122233445566778899002

are both 16 bytes. (All the letters are in HEX so it is 16 bytes right?)

> flutter: encrypted randomkey BASE16: ce557cbcb4bcd9473ee9cdd8a3fb002641b9152c4639922b7d5087ef21743689

**However, the encrypted value seems to be double the length(32 bytes)**. And I think maybe this is why it is not working. Where am I wrong? Is it possible to do AES/ECB with a 16byte key + 16byte data and get back the ciphered data as 32byte? Maybe I am failing at string - List\<int\> - hex encoded string conversions?

**_My Dart/Flutter code:_**
```
  import 'package:encrypt/encrypt.dart' as encode;
  List<int> aes128Encode(String randomkey) {
    print('randomkey: $randomkey');
    print('SECRET_KEY: $SECRET_KEY');

    final key = encode.Key.fromBase16(SECRET_KEY);   //Should I use fromBase16 here? I don't know what I am doing:(
    print('key BASE64: ${key.base64}');
    print('key BASE16: ${key.base16}');
    print('key BYTES:  ${key.bytes}');

    final iv = encode.IV.fromLength(8);   //what does this length do?? I guess Initializing Vector "IV" has no effect for ECB mode?
    final encrypter = encode.Encrypter(encode.AES(key, mode: encode.AESMode.ecb, padding: null));
    final encrypted = encrypter.encrypt(randomkey, iv: iv);   //should I pass randomkey as is? or make conversion first? I have seen thing like '.padRight(16)' maybe use them?
    print('encrypted randomkey BASE16: ${encrypted.base16}');
    print('encrypted randomkey BYTES:  ${encrypted.bytes}');

    return encrypted.bytes;   //I send this to the MiBand3
  }
```
**_Output of this method:_**

> flutter: randomkey: 5b13c8a4ad4dcacedfe7ac58f1e16e42
> flutter: SECRET_KEY: 01234567890122233445566778899002
> flutter: key BASE64: ASNFZ4kBIiM0RVZneImQAg==
> flutter: key BASE16: 01234567890122233445566778899002
> flutter: key BYTES:  [1, 35, 69, 103, 137, 1, 34, 35, 52, 69, 86, 103, 120, 137, 144, 2]
> flutter: encrypted randomkey BASE16: ce557cbcb4bcd9473ee9cdd8a3fb002641b9152c4639922b7d5087ef21743689
> flutter: encrypted randomkey BYTES:  [206, 85, 124, 188, 180, 188, 217, 71, 62, 233, 205, 216, 163, 251, 0, 38, 65, 185, 21, 44, 70, 57, 146, 43, 125, 80, 135, 239, 33, 116, 54, 137]

### JavaScript version:

> Encrypting this random number with our 16 bytes key using the AES/ECB/NoPadding encryption algorithm (from Crypto.Cipher import AES) and send it back to the Char (\x03\x00 + encoded data) from: [I hacked xiaomi miband3 and here is how I did it](https://medium.com/@yogeshojha/i-hacked-xiaomi-miband-3-and-here-is-how-i-did-it-43d68c272391)

```
let cipher = crypto.createCipheriv('aes-128-ecb', SECRET_KEY, '').setAutoPadding(false)
let encrypted = Buffer.concat([cipher.update(MESSAGE), cipher.final()])
```

### Java Version:

> from: [GadgetBridge GitHub](https://github.com/Freeyourgadget/Gadgetbridge/blob/c325ba1a22e60ef6ab6624b648d6f41f36f2417a/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/operations/InitOperation.java)

```
private byte[] handleAESAuth(byte[] value, byte[] secretKey) throws InvalidKeyException, NoSuchPaddingException, NoSuchAlgorithmException, BadPaddingException, IllegalBlockSizeException {
        byte[] mValue = Arrays.copyOfRange(value, 3, 19);
        Cipher ecipher = Cipher.getInstance("AES/ECB/NoPadding");
        SecretKeySpec newKey = new SecretKeySpec(secretKey, "AES");
        ecipher.init(Cipher.ENCRYPT_MODE, newKey);
        byte[] enc = ecipher.doFinal(mValue);
        return enc;
    }
```

### Python version:

> We first start by encrypting the MESSAGE(16 bytes) from the response using AES/ECB/NoPadding and the SECRET_KEY from: [miband2-part1-auth](https://leojrfs.github.io/writing/miband2-part1-auth/)

```
def encrypt(self, MESSAGE):
        aes = AES.new(SECRET_KEY, AES.MODE_ECB)
        return aes.encrypt(MESSAGE)
```

### Cordova version:

[cordova-ble-how-to-connect-to-mi-band-2](http://www.shewhocodes.ml/2018/05/cordova-ble-how-to-connect-to-mi-band-2) the paraghraph that starts with : **"The first three bytes ..."** explains the encryption process. And it might give an idea about the number of bytes much better in this version of this code.
Convert the received data from hex to decimal and then covert it to bytes. Then pass the bytes to app.encrypt() to encrypt the data to AES/ECB/NoPaddding.

> Below is the app.encrypt() function that will import the AES.js script then set the encrypt the bytes with key sent. It then will append the first two bytes {0x03, 0x08} to the encrypted bytes.

```
encrypt: function(textBytes){
$.ajax({
async: false,
url: "js/AES.js",
dataType: "script"
});

var key = [0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45];
var aesEcb = new aesjs.ModeOfOperation.ecb(key);
var encryptedBytes = aesEcb.encrypt(textBytes);
var u8 = new Uint8Array(2);
u8[0] = 0x03;
u8[1] = 0x08;
res = concatBytes(u8, encryptedBytes);
return res; 

function concatTypedArrays(a, b) { // a, b TypedArray of same type
var c = new (a.constructor)(a.length + b.length);
c.set(a, 0);
c.set(b, a.length);
return c;
}

function concatBytes(ui8a, bytes) {
var b = new Uint8Array(bytes.length);
for (var i = 0, len = bytes.length; i < len; i++) {
b[i] = bytes[i];
}
return concatTypedArrays(ui8a, b);
}
}
```

**Comment by aytunch** [comment]
Ok I found the problem,
instead of using `encrypter.encrypt(randomkey, iv: iv);` which assumes the randomkey(data) to be plain text/string, I needed to use `encrypter.encryptBytes(randomkeyuint8list, iv: iv);` and the output becomes 32 bit and MiBand3 likes it. Thanks for this awesome package. And for future I think it would be nice to use one function called, encrypt/decyrpt and have options for the parameters like, plain text/ hex/ base64 etc..

**Comment by Satyam-953** [comment]
thanks to you i am able to do this encryption . I hope this will help other . 
`  String decryptData(String encData) {
    final keyBytes = getByteFromHex(secretkey);//keyBytes =Uint8List
    final iv = IV.fromLength(8);   
    final encrypter = Encrypter(AES(Key(keyBytes), mode: AESMode.ecb, padding: null));
    final decry =encrypter.decryptBytes(Encrypted.fromBase16(encData),iv:iv);
      return byteToHex(Uint8List.fromList(decry)); //String
    }`
