### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by JoseGeorges8** [leocavalcante/encrypt#86]
Hi, so I started implementing the package, but I cannot make the app find my file

```
Unhandled Exception: FileSystemException: Cannot open file, path = 'assets/public.pem' (OS Error: No such file or directory, errno = 2)
E/flutter (14224): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
E/flutter (14224): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (14224): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (14224): #3      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (14224): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (14224): #5      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (14224): #6      Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter (14224): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
E/flutter (14224): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (14224): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (14224): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (14224): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (14224): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (14224): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (14224): 
```

I do have the assets folder inside the pubspec.yaml

and this is how im calling it:

`    final publicKey = await parseKeyFromFile<RSAPublicKey>('assets/public.pem');
`

**Comment by leocavalcante** [comment]
In Flutter, after adding assets to the project, you have to rebuilt it, just the hot reload or hot restarts won't take effect.

**Comment by JoseGeorges8** [comment]
That wasn't the issue, I solved it by calling the file like this: 

`    final key = await rootBundle.loadString('assets/public.pem');
`

**Comment by developmentkws** [comment]
//Problem
Flutter cant read File Path from asset folder,
//Solution
So we have to copy file to cache directory of app.

Here is Solution , Which working like a Charm .

//Solution

Future<void> writeToFile(ByteData data, String path) {
    final buffer = data.buffer;
    return new File(path).writeAsBytes(
        buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
  }

  generateSignature() async {
    var pubKey = await rootBundle.load("assets/publickey.pem");
    var priKey = await rootBundle.load("assets/privatekey.pem");
    String dir = (await getApplicationDocumentsDirectory()).path;

    writeToFile(pubKey, '$dir/publickey.pem');
    writeToFile(priKey, '$dir/privatekey.pem');
    final publicKey =
        await parseKeyFromFile<RSAPublicKey>(File('$dir/publickey.pem').path);
    final privateKey =
        await parseKeyFromFile<RSAPrivateKey>(File('$dir/privatekey.pem').path);

    final signer = Signer(RSASigner(RSASignDigest.SHA256,
        publicKey: publicKey, privateKey: privateKey));
    print(signer.sign('1').base64);
  }
