### ISSUE TITLE
openssl-pbkdf2 in Flutter (SHA1)

### ISSUE THREAD

**Issue by haizad** [leocavalcante/encrypt#89]
Hi all,

I would like to decrypt AES 256 CBC with a given password, salt, iv, iterations and key length by using Flutter.

I managed to decrypt by using PHP code as stated below, but I don't have a clue on how to do it on Flutter.

$prepared_key = openssl_pbkdf2($password, $salt, $keyLength, $iterations, "sha1");
$decrypted_message = openssl_decrypt(base64_decode($ciphertext_b64),"AES-256-CBC", $prepared_key,OPENSSL_RAW_DATA, $iv);

Could you please show me some guide on this issue. 
Many thanks.

Reference:
https://www.php.net/manual/en/function.openssl-pbkdf2.php

**Comment by leocavalcante** [comment]
You maybe have to use [PointyCastle ](https://pub.dev/packages/pointycastle) directly, there is no PBKDF2 implementation on encrypt package

**Comment by haizad** [comment]
Great! Thank you for your valuable time sir.
