### ISSUE TITLE
Got ArgumentError (Invalid argument(s): Key length must be 128/192/256 bits)

### ISSUE THREAD

**Issue by haizad** [leocavalcante/encrypt#92]
Got ArgumentError (Invalid argument(s): Key length must be 128/192/256 bits) message.

My code so far,

var base64 = CryptoUtils.hexToBytes(salt);
print(base64);

final keyone = prefix0.Key.fromUtf8("password").stretch(256, iterationCount: 1001 , salt: base64);
print(keyone.bytes.length);    
    
final iv = prefix0.IV.fromUtf8("433d5a0dfb31845f");
final encrypter = prefix0.Encrypter(prefix0.AES(keyone , mode: prefix0.AESMode.cbc));
final encrypted = prefix0.Encrypted.fromUtf8(id);
print(encrypted.bytes.length);
final decrypted = encrypter.decrypt(encrypted,iv: iv,);
print(decrypted);

![WhatsApp Image 2019-11-13 at 18 29 02](https://user-images.githubusercontent.com/23258127/68755657-c5d70500-0643-11ea-8a18-8bc5d28e051a.jpeg)

**Comment by FWeissenb** [comment]
Afaik desiredKeyLength is byte, not bit.

So try stretch(32, iterationCount: 1001 , salt: base64);

Am Mi., 13. Nov. 2019 um 11:32 Uhr schrieb rimauDB <notifications@github.com

**Comment by haizad** [comment]
Thanks. 
But I got another error..
**ArgumentError (Invalid argument(s): Input data length must be a multiple of cipher's block size)**

String salt = "****";

String id ="*****";

var base64 = CryptoUtils.hexToBytes(salt);
        print(base64);

final keyone = prefix0.Key.fromUtf8("cee493bed7abce66e11d397338ef46f1").stretch(32, iterationCount: 1001 , salt: base64);
         print(keyone.bytes.length);

final iv = prefix0.IV.fromUtf8("433d5a0dfb31845f");
        final encrypter = prefix0.Encrypter(prefix0.AES(keyone , mode: prefix0.AESMode.cbc));
        final encrypted = prefix0.Encrypted.fromUtf8(id);
        print(encrypted.bytes.length);
        final decrypted = encrypter.decrypt(encrypted,iv: iv,);
        print(decrypted);

![WhatsApp Image 2019-11-14 at 15 05 21](https://user-images.githubusercontent.com/23258127/68834228-3a677d80-06f0-11ea-88a4-6a25d3dcea38.jpeg)

**Comment by leocavalcante** [comment]
Can you share what `id` is? It's length should be a multiple of the key size.
Or can you share the encryption process that leads to `id`?

**Comment by haizad** [comment]
Here are the details...

id ="2JVtWNyL6Klx9OMml6HVhCZIjXxfb2ypZ7e1v3qTF3ri3IGyTdYjAA1bE3S0D7xbP+dLzxW91UZ/PZWnE0ZffQ==";

salt = "hY0wTq6xwc6ni01G";

Can you please spend your time on this?

Thank you so much..

**Comment by haizad** [comment]
Hi Sir,

I do not mean to be burdensome, but I still cannot manage to do the decryption.

So I would like to ask your help in debugging the code for me.

**The details of id and salt are :**

id = "2JVtWNyL6Klx9OMml6HVhCZIjXxfb2ypZ7e1v3qTF3ri3IGyTdYjAA1bE3S0D7xbP+dLzxW91UZ/PZWnE0ZffQ==";

salt = "hY0wTq6xwc6ni01G";

**My code so far :** 

String salt = "****";

String id ="*****";

var base64 = CryptoUtils.hexToBytes(salt);
print(base64);

final keyone = prefix0.Key.fromUtf8("cee493bed7abce66e11d397338ef46f1").stretch(32, iterationCount: 1001 , salt: base64);

final iv = prefix0.IV.fromUtf8("433d5a0dfb31845f");
final encrypter = prefix0.Encrypter(prefix0.AES(keyone , mode: prefix0.AESMode.cbc));
final encrypted = prefix0.Encrypted.fromUtf8(id);
final decrypted = encrypter.decrypt(encrypted,iv: iv,);
print(decrypted);

________________________________________

I’d be really grateful if you can help me to solve my problem. 

Your quick response would be appreciated.

Thank you so much.

**Comment by leocavalcante** [comment]
`id` is a valid 64 bytes length, its in base64, not utf8.

Can you share the encryption process?

**Comment by haizad** [comment]
The encryption process took place in Ionic , and I want to decrypt it on Flutter.

I can decrypt it on PHP, so I don't think there are any issues if I try to decrypt it on Flutter as well.

Here is the PHP code for the decryption process :

```
$id = "2JVtWNyL6Klx9OMml6HVhCZIjXxfb2ypZ7e1v3qTF3ri3IGyTdYjAA1bE3S0D7xbP+dLzxW91UZ/PZWnE0ZffQ==";

$password = "cee493bed7abce66e11d397338ef46f1";
$salt = "hY0wTq6xwc6ni01G";
$iv = "433d5a0dfb31845f";
$iterations = 1001;
$keyLength = 256;

$prepared_key = openssl_pbkdf2($password, $salt, $keyLength, $iterations, "sha1");
	
$decrypted_message = openssl_decrypt(base64_decode($id),"AES-256-CBC", $prepared_key,OPENSSL_RAW_DATA, $iv);

$decrypted_message = json_encode($decrypted_message);
$output= stripslashes($decrypted_message);   

if(strpos($output,'"')===0)$output=substr($output,1,(strlen($output)-1));
if(strripos($output,'"')===(strlen($output)-1))$output=substr($output,0,-1);
$decode = json_decode($output);
```

I’d be really grateful if you can remove this comment once you have seen it.

Thank you.

**Comment by leocavalcante** [comment]
I could grab the real password and salt, GitHub allows to see the edit history of a comment, and I saw that it is working on PHP. I'll try to port to Dart.

**Comment by leocavalcante** [comment]
**Got it**

The problem is that your salt shouldn't be treated as a hexdecimal string, you should use it as a regular utf-8 string, just like in PHP you don't hex-decode the salt before passing it to the `openssl_pbkdf2` function:

```dart
final encrypted = Encrypted.fromBase64(
    '2JVtWNyL6Klx9OMml6HVhCZIjXxfb2ypZ7e1v3qTF3ri3IGyTdYjAA1bE3S0D7xbP+dLzxW91UZ/PZWnE0ZffQ==');

final salt = 'hY0wTq6xwc6ni01G';

final key = Key.fromUtf8('cee493bed7abce66e11d397338ef46f1')
  .stretch(32, iterationCount: 1001, salt: Uint8List.fromList(salt.codeUnits));

final iv = IV.fromUtf8('433d5a0dfb31845f');

final encrypter = Encrypter(AES(key, mode: AESMode.cbc));
final decrypted = encrypter.decrypt(encrypted, iv: iv);

print(decrypted); // {"ekuponId":"EKS370","balanceRinggit":"0","balanceSen":"0"}
```

Also, in PHP the key-length is also in bytes, not bits. Change it to 32 like `$keyLength = 32;` and you will see it still works and its working already with 256 because openssl silently crops it, you are given a  256 **bytes** key to the openssl function, but it is croping to just the first 32 bytes portion.

Also in PHP, not sure you are doing all this quotes substitution, you could just `json_decode` right away:
```php
$decrypted_message = json_decode($decrypted_message);
var_dump($decrypted_message);

object(stdClass)#1 (3) {
  ["ekuponId"]=>
  string(6) "EKS370"
  ["balanceRinggit"]=>
  string(1) "0"
  ["balanceSen"]=>
  string(1) "0"
}
```

**Comment by leocavalcante** [comment]
Tell me if you fell uncomfortable about your sensitive data around this issue, its on the edit history even when you just created the issue. **I highly recommend you to change them** and we can keep this issue to help another people looking for something similar (like in a forum), but if you can't change it or even doing the change you want to delete this issue, I do, just ask.

**Comment by haizad** [comment]
**Many thanks for your big help. It works great.**

I would like to keep this issue as other people reference. But it would be really helpful if you can hide the sensitive data and delete the edit history.

so it would become similar like this :
```
final encrypted = Encrypted.fromBase64(
    '2JVtWNyL6Klx9OMml6HVhCZIjXxfb2ypZ7e1v3qTF3ri3IGyTdYjAA1bE3S0D7xbP+dLzxW91UZ/PZWnE0ZffQ==');

final salt = '****salt***';

final key = Key.fromUtf8('*****password********')
  .stretch(32, iterationCount: 1001, salt: Uint8List.fromList(salt.codeUnits));

final iv = IV.fromUtf8('****iv*****');

final encrypter = Encrypter(AES(key, mode: AESMode.cbc));
final decrypted = encrypter.decrypt(encrypted, iv: iv);

print(decrypted); // {"key1":"value1","key2":"value2"}
```

Thanks a ton!

**Comment by leocavalcante** [comment]
I can't erase the edit history, is a GitHub feature that repository owners have no control...

**Comment by haizad** [comment]
Understood sir. If so, please remove this issue.

Thanks again for your help.
