### ISSUE TITLE
the type <RSAPublicKey> show red error

### ISSUE THREAD

**Issue by chao9267** [leocavalcante/encrypt#93]
final publicKey = await parseKeyFromFile<RSAPublicKey>('test/public.pem');

**Comment by leocavalcante** [comment]
You need to specify as a type parameter (generics) what kind of key you want in return, if its a `RSAPublicKey` or `RSAPrivateKey`:
```dart
final publicKey = await parseKeyFromFile<RSAPublicKey>('test/public.pem');
final privKey = await parseKeyFromFile<RSAPrivateKey>('test/private.pem');
```
Note the `<RSAPublicKey>` after the function name and before parenteses.
