### ISSUE TITLE
FileSystemException

### ISSUE THREAD

**Issue by putheng** [leocavalcante/encrypt#95]
I got an error cannot option file, but file and directory already exists

`
Exception has occurred.
FileSystemException (FileSystemException: Cannot open file, path = 'assets/keys/public.pem' (OS Error: No such file or directory, errno = 2))
`

**Comment by leocavalcante** [comment]
Are you using it in Flutter? Did you added it to the assets section on the pubspec file?

Are you calling it like: `final key = await rootBundle.loadString('assets/keys/public.pem');` as stated in https://github.com/leocavalcante/encrypt/issues/86?

**Comment by developmentkws** [comment]
Solved Checkout : [Solution](https://github.com/leocavalcante/encrypt/issues/86#issuecomment-903473711)
