### ISSUE TITLE
The getter 'bytes' was called on null.

### ISSUE THREAD

**Issue by pathakvivek7865** [leocavalcante/encrypt#96]
String cipherText = "G2FsdGVkX196/DLHkI0K+u/wGT1ffTPTjYNen0dFtNA=";
  String myKey = "d45ad84d45c1d998d118a7cc6d88dba2";

  try {
    final key = Key.fromUtf8(myKey);
    final encryptedValue = Encrypted.fromUtf8(cipherText);

    final encrypter = Encrypter(
      AES(key, mode: AESMode.cbc),
    );

    // var iv = IV.fromLength(16);

    print("before");
    print(encryptedValue.base64);
    print(key.base64);

    final decrypted = encrypter.decrypt(encryptedValue);

    print(decrypted);
  } on Exception {
    print("unable to decrypt");
  }

**Comment by leocavalcante** [comment]
You are missing the IV:
```dart
final decrypted = encrypter.decrypt(encryptedValue, iv: iv);
```
