### ISSUE TITLE
How to use PKCS5 Padding

### ISSUE THREAD

**Issue by Dararii** [leocavalcante/encrypt#99]
Is there any way to use PKCS5 Padding in this library?
I already deployed an application with PKCS5 padding AES encryption, but I want to bring it to flutter. How I should overcome this issue?

**Comment by leocavalcante** [comment]
This is a wrapper around PointyCastle and there is no PKCS5 implementation there, sorry.

**Comment by nateshmbhat** [comment]
Pkcs7 should work for a server with PKCS5 padding.

I just tested it for my server which uses PKCS5 while using Pkcs7 padding at encryption.

Pointy castle guys say they both should work the same.
